### ISSUE TITLE
[Pop!_OS 21.04] Searching in app overview not working after installing this extension

### ISSUE THREAD

**Issue by insanegyros** [aunetx/blur-my-shell#100]
As the title says, I installed this extension and form then on, the overview search bar must be clicked before it starts searching. Sure it happened because of this, already posted on Pop!_OS Reddit with few more details.

https://www.reddit.com/r/pop_os/comments/od2uyh/bugged_application_menu_typing/

I'll be glad for any help resolving this issue.

Edit: So apperently it's not problem with any extension, rather with system.

**Comment by AMoonRabbit** [comment]
Are you still having the issue, I believe a system update may have resolved this as when I go into overview I don't have to click the search bar to enter a term.

**Comment by aunetx** [comment]
Sorry for the delay... Is this resolved now? I'm sorry if my extension caused any problem, but it looks like it was a gnome bug (although maybe my extension caused it to appear)

**Comment by aunetx** [comment]
If this is a problem with the system, I will close this, please reopen if needed
