### ISSUE TITLE
gnome-shell 40.2: Can not enable extension blur-my-shell: icon._dialog is undefined

### ISSUE THREAD

**Issue by ToxicDragon** [aunetx/blur-my-shell#101]
system: Fedora Rawhide
gnome-shell: 40.2
blur-my-shell installed from source (commit b7389dac02da89ff43c43308297808c92dbf01fa)

Problem description: When trying to activate blur-my-shell via the extension app, the error "icon._dialog is undefined" is shown and the extension is therefore not activatable / usable. See picture:

![image](https://user-images.githubusercontent.com/3375142/124366453-47800a00-dc50-11eb-9baf-9391f48fd1bb.png)

**Comment by aunetx** [comment]
Well, that's weird, it's all working for me... Could you give me the results of `sudo journalctl /usr/bin/gnome-shell|grep blur-my-shell`?

And in looking glass, could you give me the result of the following calls:

```js
Main.overview._overview.controls._appDisplay._folderIcons[0]
Main.overview._overview.controls._appDisplay._folderIcons[0]._dialog
```

**Comment by realiis** [comment]
I have the same problem

![Zrzut ekranu z 2021-07-04 03-43-31](https://user-images.githubusercontent.com/39202026/124370637-17e5f780-dc7a-11eb-9ce3-881d7839d56d.png)

**Comment by aunetx** [comment]
@realiis in looking glass (`alt+f2`, type `lg`), could you give me the result of the two calls I mentioned in last message?
And give me the journald logs too if possible

**Comment by rivenirvana** [comment]
I also get this error in the logs whenever I open the overview, but the extension doesn't get disabled.  _Only_ after I have to restart the shell because the current master branch of the Pop Shell extension crashes my overview and I'm forced to restart, but I don't think it's really related. With only blur-my-shell enabled, the icon._dialog error appears in the journal whenever I open the application grid, no crashes.

`sudo journalctl -b /usr/bin/gnome-shell | grep blur-my-shell` shows these repeated lines:
```
blur_appfolders/<@/home/rhaziz/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:57:13
blur_appfolders@/home/rhaziz/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:50:67
enable/<@/home/rhaziz/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:42:18
```

`Main.overview._overview.controls._appDisplay._folderIcons[0]` (dunno how to copy text from lg):
![image](https://user-images.githubusercontent.com/43519644/124380262-6208c080-dcee-11eb-9b73-c06ab7756bc5.png)

`Main.overview._overview.controls._appDisplay._folderIcons[0]._dialog`:
`undefined`

**Comment by realiis** [comment]
> @realiis in looking glass (`alt+f2`, type `lg`), could you give me the result of the two calls I mentioned in last message?
> And give me the journald logs too if possible

`sudo journalctl /usr/bin/gnome-shell | grep blur-my-shell` shows: 
```JS ERROR: Extension blur-my-shell@aunetx: TypeError: icon._dialog is undefined
blur_appfolders/<@/home/realiss/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:57:13
blur_appfolders@/home/realiss/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:50:67
enable@/home/realiss/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:39:18
enable@/home/realiss/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:47:33```

and

![Zrzut ekranu z 2021-07-04 16-09-54](https://user-images.githubusercontent.com/39202026/124388237-51eae400-dce2-11eb-9bfb-ddd82ddca0a7.png)

**Comment by aunetx** [comment]
You can now install master branch without problem, I moved developpement of this feature to another branch

**Comment by yochananmarqos** [comment]
This is happening with 2a39c0b:

```
❯ sudo journalctl /usr/bin/gnome-shell | grep blur-my-shell
                                          blur_appfolders/<@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:134:17
                                          blur_appfolders@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:132:67
                                          enable/<@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:127:18
                                          blur_appfolders/<@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:134:17
                                          blur_appfolders@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:132:67
                                          enable/<@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:127:18
Jul 21 09:15:19 serval gnome-shell[2169]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: icon._dialog is undefined
                                          disable/<@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:208:13
                                          disable@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/appfolders.js:207:67
                                          disable@/usr/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:70:31
```

**Comment by soorajsprakash** [comment]
I've the same issue in Manjaro gnome

**Comment by Boricua3** [comment]
I have this same issue. Running Fedora 34 Silverblue, Gnome 40 on Wayland.

**Comment by aunetx** [comment]
I will now keep track of the issue on #107, sorry for not fixing it before
