### ISSUE TITLE
Didnt work, I might need help

### ISSUE THREAD

**Issue by alvinbengeorge** [aunetx/blur-my-shell#102]
So i cloned and did make install, so basically what happened was 
```
glib-compile-schemas src/schemas
mkdir -p build/
cp -r src/* build/
rm -f build/prefs.ui~
rm -rf /home/alvinbengeorge/.local/share/gnome-shell/extensions/blur-my-shell@aunetx
mkdir -p /home/alvinbengeorge/.local/share/gnome-shell/extensions/blur-my-shell@aunetx
cp -r build/* /home/alvinbengeorge/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/
```
I restarted the device, it didnt work in Fedora 34
GNOME 40.2 btw what do i do?
Also it takes time after i did the installation, 3:15 min became 4:40 min to start
Could you please help me?
or help me uninstall it maybe

Thank you

**Comment by aunetx** [comment]
Hi, sorry for the inconvenience, I should use a developpement branch! My last commit was not really working, so it was not released yet... If you want to use the commit right before, which works, you can use:

```sh
git checkout cac14de64c604a5841787c424a96f0071747a12a
```

Just before installation

**Comment by alvinbengeorge** [comment]
Hi, Thank you for responding i added the checkout version that you gave and it looks beautiful, thank you for your contribution and for your help
It looks pretty amazing
![image](https://user-images.githubusercontent.com/69302420/124634051-8528a100-dea3-11eb-9c8e-795d182805fb.png)
