### ISSUE TITLE
Feature Request: Compatibility with window-list Extension

### ISSUE THREAD

**Issue by Saijin-Naib** [aunetx/blur-my-shell#103]
I love the aesthetic tweaks that this extension enables, and I think it really elevates the look of GNOME Shell on my system. In that line, I would love to see this extension be compatible with the [Window List extension](https://extensions.gnome.org/extension/602/window-list/) (from [GNOME Shell Extensions](https://gitlab.gnome.org/GNOME/gnome-shell-extensions)), as that would allow me to have a more unified and better looking shell.

Thanks so much for this amazing extension!

**Comment by aunetx** [comment]
Thanks for the issue! This could be a good idea effectively, as this is an official gnome-shell extension... I will see what I can do for this, although this is not my first priority tbh

**Comment by Saijin-Naib** [comment]
Absolutely understand!

I'm also not sure if the work needs to be done on their end or Blur My Shell's end, but regardless, thank you so much for even considering it.

**Comment by aunetx** [comment]
Hi, could you try installing from branch `window-list` on github? I implemented the compatibility (pretty well IMHO), could you please tell me what could be missing?

**Comment by Saijin-Naib** [comment]
> Hi, could you try installing from branch `window-list` on github? I implemented the compatibility (pretty well IMHO), could you please tell me what could be missing?
![Screenshot from 2021-07-29 00-19-16](https://user-images.githubusercontent.com/19295950/127431012-51168b5e-2878-4fb5-bc34-427a8ed64256.png)
Works great!

Only weird thing I noticed was that I had to toggle the transparency for the Window List on and off before it would take effect. I don't recall needing to do that for the other items as they just sort of were blurred once the extension was enabled.

**Comment by aunetx** [comment]
Yeah, I may not have tried correctly to enable the extension after Window List! I will correct this very soon.

The artifacts are however manager by the "artifacts hacks" in the preferences, when put to the last option the artifacts should disappear right away from the Window List widget :)

And for the windows indicators, which style would you like to have? I hesitated about keeping the same "old school" style button (with 3d apparence"), but it looked weird with the blur behind it ; so would you like me to try putting instead more modern style button?

**Comment by Saijin-Naib** [comment]
I suppose if you have an idea of what look you think would work best, then yeah, whatever that is sounds good!

**Comment by aunetx** [comment]
This should be all resolved with last commit!
I close and merge this now, and if you want this to look something else you can reopen this issue!
