### ISSUE TITLE
Feature Request: Blur "overview.cosmic-solid-bg" option.

### ISSUE THREAD

**Issue by slottwo** [aunetx/blur-my-shell#104]
I change the cosmic background for the application menu from opaque to transparent. But the overview blur option has no effect on it, could you add that option?

Changed file: `/usr/share/themes/<theme>/gnome-shell/gnome-shell.css`

```csl
#overview.cosmic-solid-bg` {
  /* background-color: #36322f; */
  background-color: transparent; }
```

System Information:
| Resource | Version |
| --- | --- |
| Pop!_OS | 21.04 |
| Gnome Shell | 3.38.4 |
| GPU | AMD® Radeon(tm) vega 8 graphics |
| CPU | AMD® Ryzen 3 3200g with radeon vega graphics × 4 |
| Xorg | X11 |
| Blur my Shell |19 |
| Pop COSMIC | 1 |
| Pop Shell | 2 |

**Comment by AMoonRabbit** [comment]
I just made an edit to the orchis dark red compact theme, and this extension is applying the blur OK. 
With your modification to the theme, does the overview screen actually show fully transparent?

**Comment by slottwo** [comment]
Yes, but I noticed something, the menu overlaps apps among others, it's not like the default overview workspaces.
[Pop-dark (edited).tar.gz](https://github.com/aunetx/blur-my-shell/files/6835483/Pop-dark.TAM.tar.gz)
![Pop Applications Overview](https://user-images.githubusercontent.com/41028091/126052303-03f132a7-1989-4b1f-b123-d928225ad050.png)
![Pop Workspaces Overview](https://user-images.githubusercontent.com/41028091/126052319-7347c232-0218-4934-a3ea-eab40a335400.png)

**Comment by AMoonRabbit** [comment]
I applied the theme you provided with gnome tweaks
![image](https://user-images.githubusercontent.com/3766988/126072976-46a38bf5-b9c5-4c06-8cb2-959bd6b287f9.png)

![image](https://user-images.githubusercontent.com/3766988/126072983-a2f80621-2e1b-41fe-ada7-e49673dbb859.png)
And mine seems to be okay. Just to confirm, these are your settings for the blur my shell component?

![image](https://user-images.githubusercontent.com/3766988/126073026-819b7325-dbad-46d4-8fd5-d912e26944d0.png)

**Comment by aunetx** [comment]
Sorry, still not installed pop_os on a vm to test cosmic... I will test it really soon (if I can), so that you don't need to install another theme for my extension to work

**Comment by slottwo** [comment]
@AMoonRabbit 

Yes, I even changed the settings to be exactly the same as yours, but it still has the same problem.

**Comment by aunetx** [comment]
Hi, I tried to implement this (and this is very messy...), and it looks to work for me.

Could you please try with latest github version, from `pre_40` branch? The dash should work too, see #99

**Comment by aunetx** [comment]
@slottwo @AMoonRabbit would it be possible for you to test this?

**Comment by AMoonRabbit** [comment]
@aunetx I can, though I haven't been able to reproduce the issue myself either.

**Comment by slottwo** [comment]
It is working yes! Thanks and congratulations

**Comment by aunetx** [comment]
OK thanks a lot! I will push to extensions.gnome.org asap

**Comment by AMoonRabbit** [comment]
Quick q, I just tried manually installing the pre-40 build, and whist it copies to the extensions folder okay, `gnome-extension enable blur-my-shell@aunetx` just results in "extension not found". Not the end of the world for me if these changes are also included in the 40 release as I don't use the 3.38 version in Pop.

**Comment by aunetx** [comment]
Well, that's weird for the `gnome-extensions` thing... I don't think this is due to the update (as the metadata do not change), maybe try to restart the computer, or enable the extension from the extensions app?

I will see what I can do about gnome 40's support for cosmic, although I not sure about it, as it is not a very good-looking commit (more like a hack), so I don't know about including it into the master branch (I honestly don't want to fix more issues than needed)...
But I will tell you if I choose to port the changes to gnome 40's extension!

**Comment by AMoonRabbit** [comment]
Sorry, I think I assumed the install widget on the page would do the version for gnome 40, but when I later checked the version with the `gnome-extension info blur-my-shell@aunetx` it came back with v19. Apologies.

**Comment by aunetx** [comment]
No worry!
If everything right then though?

**Comment by AMoonRabbit** [comment]
Yes, all is well. I cleared the extension pulled from the web, and then did
the make file again, rebooted and it finally appeared and is working fine

**Comment by aunetx** [comment]
Perfect, thanks a lot! I will push to extensions.gnome.org soon :)
