### ISSUE TITLE
Bluring effect does not work after locking the laptop on Fedora 34 wayland.

### ISSUE THREAD

**Issue by xtanion** [aunetx/blur-my-shell#108]
I'm using Fedora 34 with gnome 40 on Wayland, This extension works perfectly fine after Reboot but once I lock my pc and then unlock it again, this extension doesn't work at all.

**Comment by LambLeeg** [comment]
I experience the same issue on Fedora 34 Gnome Wayland

**Comment by Naim-Bijapure** [comment]
same issue not working after update

**Comment by N0Alex** [comment]
similarly, the problem is relevant (Fedora 34 Xorg)

**Comment by frigorifero-pipo** [comment]
Same issue. gnome-extensions gives me the following:
![immagine](https://user-images.githubusercontent.com/63809562/126772828-acacbeae-bcad-41fc-96f3-841dab8ce900.png)

**Comment by aunetx** [comment]
Looks like a duplicate of #108, I will try to fix this very quickly :)

**Comment by aunetx** [comment]
Mmm sorry, duplicate of #107 instead
