### ISSUE TITLE
Information exchange with gnome-shell-extension-blyr

### ISSUE THREAD

**Issue by ToxicDragon** [aunetx/blur-my-shell#11]
Hi,
@aunetx Thank your for you sweet extension; I really like using it!

This time no bug, just a recommendation:

There is another extension "in the market" for quite some time now and its latest branch also has enablement for gnome-shell 3.38 (so it works for gnome-shell 3.38): gnome-shell-extension-blyr (https://github.com/yozoon/gnome-shell-extension-blyr).

Maybe both of you can benefit from each other's code :+1: 

Keep up the great work!

**Comment by aunetx** [comment]
Thanks a lot!

I've actually seen this extension (and it inspired me to create this one), and I loved it! But I wanted to have dynamic blur, so I made Blur my Shell instead ^^

And some of my code for the overview implementation was heavily inspired from Blyr, before I cleaned it :)

But anyways, I love Blyr and find it actually a lot more stable than Blur my Shell!
