### ISSUE TITLE
Conflicts in Wallpaper Changing and between System Tray and Workspace

### ISSUE THREAD

**Issue by efefurkankarakaya** [aunetx/blur-my-shell#110]
The first problem is, after the changing wallpaper it does not affect ```overview``` 'till the option is ticked it again but not all wallpapers 'cause (?) like Manjaro default wallpapers. They effects on all.

![Screenshot from 2021-07-26 03-23-12](https://user-images.githubusercontent.com/49307777/126918407-2fca35d9-a625-4a94-81b1-e0d860b88fbf.png)

The second one is about workspaces. After the logging out they become looking like have rounded corners even ```bar``` option is enabled.

That's what expected and, at first what happened.
![border-radius-2](https://user-images.githubusercontent.com/49307777/126918323-6487f7ca-a912-402f-96ed-0ab14affe7fa.png)

That's the after logging out, shutdown etc.
![border-radius-1](https://user-images.githubusercontent.com/49307777/126918306-ece037d6-1595-4b1b-99f7-89b73d07535d.png)

```
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.1.0
Codename:	Pahvo
```
```GNOME Shell 40.3```

**Comment by aunetx** [comment]
I, thanks for the issue!

First, how do you change your wallpapers? Is this from the default gnome wallpaper chooser, or and external app for example which permit to change randomly between different wallpapers?

And for the rounded corners, what do you mean by "logging out"?

**Comment by efefurkankarakaya** [comment]
Hi,

Yeah, I use default gnome wallpaper chooser to set desktop background. There's no 3rd party wallpaper picker that I use, I only do ```Set as wallpaper``` for one picture.

Actually I mean whenever GDM closes. I've tried to log out after the customization for seeing what happens or any conflicts will happen, some extensions needs log out to be activated flawless in next session but ```blur-my-shell``` losing it's override on corners.

**Comment by aunetx** [comment]
Could you enable the option "debug mode" in extension preferences, and show me the result, before and then after changing wallpaper, of `sudo journalctl /usr/bin/gnome-shell|grep "Blur my Shell"`?

Ok, I see what you mean... Which other extensions do you use? I know that some don't like Blur my Shell hiding panel corners, and may re-enable them... I will make sure in next commit to re-hide them everytime they are showed.

**Comment by aunetx** [comment]
The panel corner thing should be gone in last commit :)

**Comment by efefurkankarakaya** [comment]
I enabled and changed the wallpaper, same thing happened and this time even notification bar color wasn't changed also and then I connected the secondary monitor and it fixed itself.

```
Jul 29 23:05:58 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:05:58 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:05:58 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:06:28 efk gnome-shell[1368]: [Blur my Shell] changed monitors
Jul 29 23:06:28 efk gnome-shell[1368]: [Blur my Shell] changed monitors
Jul 29 23:06:45 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:06:45 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:06:45 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
```

It's really weird. I tried the same thing as reverse (dual extended screen to single) it fixed itself again.

```
Jul 29 23:12:24 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:12:24 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:12:24 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:12:24 efk gnome-shell[1368]: [Blur my Shell] changed monitors
Jul 29 23:12:24 efk gnome-shell[1368]: [Blur my Shell] changed monitors
Jul 29 23:12:51 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:12:51 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:12:51 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
```

![Screenshot from 2021-07-29 23-15-33](https://user-images.githubusercontent.com/49307777/127559803-6308561e-250a-470d-bfe6-1bcb3bfba32b.png)
That's how it looks like after changing the wallpaper, as seen notification bar has the old wallpaper's transparent color. And outputs are regular again.

```
Jul 29 23:15:41 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:15:41 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
Jul 29 23:15:41 efk gnome-shell[1368]: [Blur my Shell] appfolders hack level 1
```

**Comment by efefurkankarakaya** [comment]
AppIndicator and KStatusNotifierItem Support, Dash To Dock, Pamac Updates Indicator, Desktop Icons NG (DING)

The other extensions that I use but in latest days I started to use Just Perfection to fix that corner problem.

And I haven't got the latest update yet.

**Comment by aunetx** [comment]
I will see about the logs you gave me, this looks very weird... I mean, the extension does not seem to get the wallpaper change signal, idk how I can test it

Thanks for the list of extensions, and I haven't pushed the extension to extensions.gnome.org yet, but you can test it from github with:

```sh
git clone https://github.com/aunetx/blur-my-shell
make install
```

And then restarting gnome-shell (by logout/login for example)

**Comment by efefurkankarakaya** [comment]
I've just tried the log out and re-log in to session and it fixed itself again. 
![Screenshot from 2021-07-29 23-32-58](https://user-images.githubusercontent.com/49307777/127562154-2687b0bb-4e06-4adc-bf28-8b3147ef47a8.png)

```
Jul 29 23:32:39 efk gnome-shell[4902]: [Blur my Shell] enabling extension...
Jul 29 23:32:39 efk gnome-shell[4902]: [Blur my Shell] blurring top panel
Jul 29 23:32:39 efk gnome-shell[4902]: [Blur my Shell] blurring overview
Jul 29 23:32:39 efk gnome-shell[4902]: [Blur my Shell] blurring lockscreen
Jul 29 23:32:39 efk gnome-shell[4902]: [Blur my Shell] blurring appfolders
Jul 29 23:32:39 efk gnome-shell[4902]: [Blur my Shell] extension enabled.
Jul 29 23:33:00 efk gnome-shell[4902]: [Blur my Shell] appfolders hack level 1
Jul 29 23:33:00 efk gnome-shell[4902]: [Blur my Shell] appfolders hack level 1
Jul 29 23:33:00 efk gnome-shell[4902]: [Blur my Shell] appfolders hack level 1
```

And you're right, it doesn't listen the events. It's only updates itself while reselecting the option or restarting the whole extension.

**Comment by efefurkankarakaya** [comment]
And I've just also tried the manjaro's default desktop pictures. Outputs are different, extension works like charm as I mentioned above.

```
Jul 29 23:55:05 efk gnome-shell[4902]: [Blur my Shell] updated background
Jul 29 23:55:05 efk gnome-shell[4902]: [Blur my Shell] updated background
```

Oh, I think I found something. Right click -> Set Desktop Wallpaper is working on Nautilus. 

![z](https://user-images.githubusercontent.com/49307777/127565014-81e195ac-c4d9-4101-86d0-d51cf42c7ff8.png)

There might be a difference between _Manjaro's Background Setter_ between Nautilus _Set As Wallpaper_ and may be that's the reason.

**Comment by aunetx** [comment]
Would it be possible for you to screen record the bug when changing wallpaper? I have a hard time understanding the exact breaking case, sorry :/

(by the way, what is your wallpaper if you don't mind? love it :p)

**Comment by efefurkankarakaya** [comment]
OK, I'll provide you a record when I'm available.

Lol, thanks =) Can be found as "minimalist nature wallpaper".

**Comment by aunetx** [comment]
Thanks a lot!

**Comment by aunetx** [comment]
Could you try to install from branch `tryfix-110` and tell me if this fixes anything?

After installing you will probably need to logout/login.

**Comment by efefurkankarakaya** [comment]
> Could you try to install from branch `tryfix-110` and tell me if this fixes anything?
> 
> After installing you will probably need to logout/login.

I've just tried with same wallpapers and it works as expected.
