### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by fene83** [aunetx/blur-my-shell#111]
hi im running fedora 34 gnome 40 and version 21 says error when downloaded from gnome extensions on browser.
I installed version 20 again but it doesnt see it (maybe it is the wrong path for the extensions). If you can help thanks

**Comment by harshkhandeparkar** [comment]
I have managed to fix these errors with a quick shell reload (`Alt +F2` and `r`)

**Comment by harshkhandeparkar** [comment]
I only encountered such errors with blur my shell though, needs investigation...

**Comment by harshkhandeparkar** [comment]
![image](https://user-images.githubusercontent.com/34770591/127349816-7be85062-6d4e-4ec4-ab67-c9f0d41bd678.png)
Here's you error. Gnome 40.3.0, Ubuntu 21.04 unofficial repo.

Reproduction steps:
1. Installed v20 manually and restarted.
2. Upgraded to v21 from the website.

Journalctl:
![image](https://user-images.githubusercontent.com/34770591/127350224-b1f69322-483c-499e-a84b-6ddeaaf15dc7.png)

**Comment by harshkhandeparkar** [comment]
A friend reported the same error on Pop!_OS COSMIC.

**Comment by aunetx** [comment]
Hi, have you tried restarting gnome after upgrading the extension?

**Comment by fene83** [comment]
> ![image](https://user-images.githubusercontent.com/34770591/127349816-7be85062-6d4e-4ec4-ab67-c9f0d41bd678.png)
> Here's you error. Gnome 40.3.0, Ubuntu 21.04 unofficial repo.
> 
> Reproduction steps:
> 
>     1. Installed v20 manually and restarted.
> 
>     2. Upgraded to v21 from the website.
> 
> 
> Journalctl:
> ![image](https://user-images.githubusercontent.com/34770591/127350224-b1f69322-483c-499e-a84b-6ddeaaf15dc7.png)

i installed v20 mannualy but when i put it in /home/usr/.local/share/gnome-shell/extensions the extension app doesnt see it

**Comment by aunetx** [comment]
What happens when you directly install version 21, and then restart your computer?

There is definitely an issue going on there, I will check this soon

**Comment by harshkhandeparkar** [comment]
Restart *fixes* the issue. This issue happens before restarting, when extensions.gnome.org upgrades the extension (w/o restarting)

**Comment by aunetx** [comment]
Yeah, it happens to me too, but I can't do anything about it, that's the gnome behaviour that changed at a moment, requiring a restart after upgrading extensions...

So that's not a blur my Shell issue, sorry about the inconvenience :(
