### ISSUE TITLE
Appfolder Blur Border

### ISSUE THREAD

**Issue by harshkhandeparkar** [aunetx/blur-my-shell#112]
![image](https://user-images.githubusercontent.com/34770591/127506040-f3e19c64-62cd-4d98-9c73-1479e86b7bcb.png)
Currently the app folder is indistinguishable from the background and hence changing pages and closing the folder by clicking is rather hard.

Perhaps the appfolders can be given a different opacity, brightness or a border?

**Comment by aunetx** [comment]
I fixed this in last commit, and may add a slider to choose the opacity later on :)
