### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by ric3cir121** [aunetx/blur-my-shell#114]
the extension is not working and it gives the following error:

The settings of extension blur-my-shell@aunetx had an error:
```
TypeError: this._sigma_scale is null

Stack trace:
_init@/home/ric3cir121/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:33:9
buildPrefsWidget@/home/ric3cir121/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:152:12
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by aunetx** [comment]
Which gnome shell version do you use, which version of blur my Shell and how did you install it?

And could you please give me the results of:

```sh
sudo journalctl /usr/bin/gnome-shell|grep blur-my-shell
```

**Comment by ric3cir121** [comment]
my gnome shell version is 3.38.5 and that command gives me many errors:
![image](https://user-images.githubusercontent.com/61619987/127568622-823e0a8a-6d49-4ec5-8da1-4bb3df84b405.png)
![image](https://user-images.githubusercontent.com/61619987/127568665-3633010d-0735-4ee1-8e8f-c78fa5586c67.png)

**Comment by aunetx** [comment]
Did you install from github or the aur? The version you are using seems to be the one intended for gnome 40, if you want to use the right version you can install from extensions.gnome.org or from the `pre_40` branch on github!

**Comment by aunetx** [comment]
I checked again, and you definitively are using a Blur my Shell version incompatible with your gnome-shell version... I close this issue, but if you need help installing the right version don't mind comment on it again!

**Comment by ric3cir121** [comment]
well now it is working but it's not blurring everithing, things like my terminal are not being blurred and result in a non blurred transparent terminal, how can i blur it?

**Comment by aunetx** [comment]
There is no way to blur it with my extension, you can try with Blur Me (a fork which blurs applications too) but it does not work for me and may use a lot of cpu

**Comment by ric3cir121** [comment]
ok, thanks for help
