### ISSUE TITLE
Arch Linux / Gnome 40 extension stopped working.

### ISSUE THREAD

**Issue by xircon** [aunetx/blur-my-shell#118]
![image](https://user-images.githubusercontent.com/1316691/128597057-a26b25a4-fd97-4541-96d4-becebe989e90.png)

Installed form the extensions web site, anything else needed, let me know.

**Comment by xircon** [comment]
Manual install from here seems to have fixed it.

**Comment by xircon** [comment]
Nope, the same problem is back, I spoke too soon

**Comment by aunetx** [comment]
Which settings do you use for screen locking (like, does the screen lock after some time, or not)?
I did not expect `Main.screenShield` to be null sometimes, maybe you are using an incompatible extension?

**Comment by xircon** [comment]
I am not using anything for screen locking, I am using sddm and not gdm.  Which extensions are incompatible?

**Comment by aunetx** [comment]
That could be caused by sddm, I never tested it with Blur my Shell... But the extensions should not interfere from what I saw, I will test as much as possible when I can

**Comment by aunetx** [comment]
I will fix this this afternoon, sorry for the delay!
