### ISSUE TITLE
Blur breaks when switching wallpapers

### ISSUE THREAD

**Issue by EvanWashkow** [aunetx/blur-my-shell#12]
The desktop blur breaks when switching wallpapers. I noticed it because I use an automatic wallpaper switcher extension like Random Wallpaper or Bing Wallpapers. Every time it syncs, it breaks the desktop blur.

**Comment by aunetx** [comment]
Thanks for the issue! I will try to resolve this soon (and I understand the burden it must be to have the blur broken for overview, I'm sorry :/)

**Comment by aunetx** [comment]
(see #13)
