### ISSUE TITLE
no blur updating in Wayland

### ISSUE THREAD

**Issue by LukeVader-IV** [aunetx/blur-my-shell#127]
I created an animation for my background using a similar method to what fedora uses for the default dynamic background, it's an .xml file that goes though a series of images

While under X it updates in real time, under Wayland it never updates and the blur is static

Fedora 34 Gnome 40.4.0

Under X:
https://user-images.githubusercontent.com/15455108/133140315-a9272a79-83df-4919-8bcf-8933cd06a4dc.mp4

Under Wayland:
https://user-images.githubusercontent.com/15455108/133140342-247de0af-25f0-4793-8390-4c04f993ec8b.mp4

this wouldn't only have effect on stupid edge cases where people are using a hack to get an animation to work, but also for dynamic backgrounds where it updates depending on external factors like time, weather, etc

PS: i love your extension, i don't know why the ugly gray is default in gnome, great work (:

**Comment by aunetx** [comment]
Thanks for opening the issue! I honestly don't know why the behaviour would differ between wayland and xorg...

I will try to contact some real gnome developers to ask them if this is normal or not, but I suspect this is not intended (as xorg and wayland should behave in the exact same way for the end-user, and even for an extension developer -- everything is managed by mutter in theory).

**Comment by aunetx** [comment]
Could you try by installing from branch `tryfix-110` on github? This is not intended to fix this issue, but may as well do the job :)

**Comment by LukeVader-IV** [comment]
yup, sure enough that did fix the issue
the animation gets properly blurred on my second screen in wayland

**Comment by aunetx** [comment]
Cool, thanks for the follow-up! I will clean this code (to add less overhead on gnome) and push it to gnome-extensions in some days :)
