### ISSUE TITLE
GNOME 41 compatibility

### ISSUE THREAD

**Issue by frandieguez** [aunetx/blur-my-shell#130]
In some days GNOME 41 will be released and I have tested your extension by simply adding the new version to the `src/metadata.json` file.

```
    "shell-version": [
        "40",
        "41"
    ],
```

It will be awesome to have your extension compatible on day-one.

**Comment by aunetx** [comment]
Is there any bug you noticed on gnome 41? I don't have the time to install gnome 41 and check myself :/

If everything's ok I will simply update it in extensions.gnome.org!

**Comment by aunetx** [comment]
I added compat in github, will probably upload it to extensions.gnome.org while merging #129

**Comment by aunetx** [comment]
I will push to ego tomorrow, closing this :)

**Comment by frandieguez** [comment]
No bugs so far in GNOME 41, thanks for the quick update
