### ISSUE TITLE
Don't override folder color

### ISSUE THREAD

**Issue by LinuxLlama** [aunetx/blur-my-shell#133]
I'd prefer if this extension didn't change the app folder background. Please add an additional option for this.

With extension:
![Screenshot from 2021-10-02 11-53-27](https://user-images.githubusercontent.com/29968331/135728686-2ce4d803-e0b8-4066-a667-52652f4c8e66.png)
Without extension:
![Screenshot from 2021-10-02 11-53-55](https://user-images.githubusercontent.com/29968331/135728688-5415309b-fe29-4f87-821d-bf3e445efb57.png)

**Comment by aunetx** [comment]
Sorry, I though I already disabled this css change when not blurring overview... Will fix this asap

**Comment by aunetx** [comment]
This is now fixed in latest commit, will push to extensions.gnome.org soon
