### ISSUE TITLE
Blur effect crashed when `sudo apt-get install [PACKAGE NAME]`

### ISSUE THREAD

**Issue by VNGamerGit** [aunetx/blur-my-shell#134]
By crashed, I meant that the extension lost the blur effect whenever I ran `sudo apt-get install [PACKAGE NAME]`, so I have to go to the Extensions menu and restart the whole thing again (turn it off, then on again). It only happens to the panel though, other things like overview, app folders, dash still have the blur effect

**Comment by aunetx** [comment]
Does this happen consistently? And what kind of packages were you installing?

I don't really know why this would happen, except ofc if this was updating gnome packages, but then I can't really do anything...

**Comment by VNGamerGit** [comment]
> Does this happen consistently? And what kind of packages were you installing?
> 
> I don't really know why this would happen, except ofc if this was updating gnome packages, but then I can't really do anything...

Any kind of packages, from Firefox, Reversi, Zoom, etc..., just any kind. Strangely, it's fine when updating GNOME packages

**Comment by aunetx** [comment]
I'm wondering what I could have done wrong, but I see nothing ; probably a gnome bug after all. Could you tell me if it stops at a moment?

**Comment by VNGamerGit** [comment]
> I'm wondering what I could have done wrong, but I see nothing ; probably a gnome bug after all. Could you tell me if it stops at a moment?

If you meant "stop at a moment" as in when it crashed again, then see [https://github.com/aunetx/blur-my-shell/issues/134#issuecomment-934261026](url)

**Comment by CorvetteCole** [comment]
I tried to replicate this on Ubuntu and failed. I'm not sure this is valid. Will close for now
