### ISSUE TITLE
Another wake from sleep null error.

### ISSUE THREAD

**Issue by jenschurchill** [aunetx/blur-my-shell#137]
After waking from sleep, journal displays this repeating 2 times...
```
Oct 20 11:19:20 <redacted> gnome-shell[1324]: JS ERROR: TypeError: bg is null
                                            update_wallpaper@/home/<redacted>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:147:13
                                            enable/<@/home/<redacted>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:70:18
                                            destroy@resource:///org/gnome/shell/ui/background.js:703:34
                                            _updateBackgrounds@resource:///org/gnome/shell/ui/layout.js:469:33
                                            _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:539:14
Oct 20 11:19:20 <redacted> gnome-shell[1324]: JS ERROR: TypeError: background is null
                                            update_backgrounds/<@/home/<redacted>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:53:13
                                            update_backgrounds@/home/<redacted>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:50:37
                                            enable/<@/home/<redacted>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:24:18
                                            destroy@resource:///org/gnome/shell/ui/background.js:703:34
                                            _updateBackgrounds@resource:///org/gnome/shell/ui/layout.js:469:33
                                            _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:539:14
```

Happened while using only the laptop monitor.  
I do have a dock with separate monitors, but laptop has not been connected to that since last restart.
```
➜  ~ xrandr 
Screen 0: minimum 16 x 16, current 2560 x 1440, maximum 32767 x 32767
XWAYLAND0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   2560x1440     59.96*+
```

Running wayland gnome 40.4
```
➜  ~ neofetch 
             .',;::::;,'.                <redacted>@<redacted> 
         .';:cccccccccccc:;,.            ------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora 34 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: <redacted> ThinkPad X1 Carbon 6th 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.14.11-200.fc34.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 1 hour, 33 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2051 (rpm), 6 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.8 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2560x1440 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 40.4 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i7-8650U (8) @ 4.200GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel UHD Graphics 620 
.:cccccccccccccccccccccc:;,..            Memory: 5533MiB / 15865MiB 
  '::cccccccccccccc::;,.
                                                                                                                               
```

I really only use this for the overview display, which still seems to work without issue.

**Comment by Rishabh672003** [comment]
i am having the same issue, when my system  goes to sleep and then wakes up i get the error "actor is null"
but after restart it gets fixed
![image](https://user-images.githubusercontent.com/53911515/140600522-d4bd31db-0c63-44cc-8e7a-0c51648630ca.png)

**Comment by aunetx** [comment]
Sorry for the delay, investigating right now! And thanks a lot for the detailed logs :)

**Comment by galen1423** [comment]
Always failed to launch ... same error

**Comment by aunetx** [comment]
There should be no error in last commit, but the overview/panel may not be blurred properly...
If you want to try it, hopefully everything works

**Comment by jenschurchill** [comment]
Have since upgraded to fedora 35, gnome 41.

Error remained, have tried checking out tryfix_137; make install.
Reboot, journalctl --follow, suspend, resume.

Now I get, but the bg/background null error seems to have disappeared.

```
Nov 10 21:49:16 jmc-x1c6 gnome-shell[1341]: JS ERROR: ReferenceError: monitor is not defined
                                            update_wallpaper/<@/home/jmc/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:156:46
                                            setTimeout/<@/home/jmc/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/utilities.js:10:13
Nov 10 21:49:16 jmc-x1c6 gnome-shell[1341]: JS ERROR: ReferenceError: monitor is not defined
                                            update_wallpaper/<@/home/jmc/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:156:46
                                            setTimeout/<@/home/jmc/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/utilities.js:10:13

**Comment by Razer0123** [comment]
Got the same issue on Arch and 41.1, i mean the "bg is null"

**Comment by Razer0123** [comment]
Any news? had this today

**Comment by aunetx** [comment]
I'm extremely sorry, I really took a lot of time to even look at it...

I did a very stupid mistake (copy/paste that I did not intend), but this should work better with last commit from `tryfix_137` @jenschurchill  :)

And @Razer0123 if you can install from #148 (branch `tryfix_137`), the error should be resolved -- or at least, no more `bg is null` right?

**Comment by Razer0123** [comment]
> I'm extremely sorry, I really took a lot of time to even look at it...
> 
> I did a very stupid mistake (copy/paste that I did not intend), but this should work better with last commit from `tryfix_137` @jenschurchill :)
> 
> And @Razer0123 if you can install from #148 (branch `tryfix_137`), the error should be resolved -- or at least, no more `bg is null` right?

Thanks for helping

I do not know what to do to test that fix, if you tell me I'll try

**Comment by aunetx** [comment]
To test this, go to terminal and enter:

```sh
git clone https://github.com/aunetx/blur-my-shell
cd blur-my-shell
git checkout tryfix_137
make install
```

And then logout from gnome and login again, and you can delete the `blur-my-shell` folder in your home directory if you want.

Tell me if anything good happens, or if you have any error!

**Comment by Razer0123** [comment]
> To test this, go to terminal and enter:
> 
> ```shell
> git clone https://github.com/aunetx/blur-my-shell
> cd blur-my-shell
> git checkout tryfix_137
> make install
> ```
> 
> And then logout from gnome and login again, and you can delete the `blur-my-shell` folder in your home directory if you want.
> 
> Tell me if anything good happens, or if you have any error!

Installed yesterday, so far so good

**Comment by aunetx** [comment]
Thanks a lot! I merge this and will push it to extensions.gnome.org soon then :)
