### ISSUE TITLE
Changes the wallpaper in overview 

### ISSUE THREAD

**Issue by tanaybhomia** [aunetx/blur-my-shell#139]
I have a slideshow wallpaper set up using shotwell and it changes wallpaper I guess in 30 minutes but when you go into overview itt just shows the wallpaper which was their when you first turned the monitor on 

Just check it 
![Screenshot from 2021-10-30 08-18-57](https://user-images.githubusercontent.com/71910027/139517751-7bb3ead2-355b-4f29-a4c7-837851517de5.png)
![Screenshot from 2021-10-30 08-19-01](https://user-images.githubusercontent.com/71910027/139517758-99edee3e-c089-4dd1-a4e2-891047920f48.png)

So I hope you update this, also I am not using gnome 40, I am using gnome 3.38.

**Comment by aunetx** [comment]
Thanks for opening the issue, which program are you using to change the wallpaper?

**Comment by Deottive** [comment]
I think its Shotwell

**Comment by aunetx** [comment]
Sorry, I did not fully read your first message... Will see what I can fix here!

**Comment by aunetx** [comment]
Is it working now @tanaybhomia? Sorry for the late ping, but a lot has changed in the extension since this issue was opened, including how the wallpaper is chosen :)

**Comment by aunetx** [comment]
Closing this because it should now work correctly, especially with #546 coming soon :)
