### ISSUE TITLE
Allow to change panel background colour

### ISSUE THREAD

**Issue by jmaris** [aunetx/blur-my-shell#141]
Hi,

When I enable panel blur in the extension, my panel (which is usually a semi-transparent white) becomes completely transparent with a blur effect applied. I have set brightness to 100%

Is this normal behavior, and is there any way to keep the colour of my panel ?

**Comment by Tygrain** [comment]
Did you try to uncheck this checkbox?
![image](https://user-images.githubusercontent.com/50624811/140604376-38a9ab94-f483-4530-b96d-cb4b2f1f76dd.png)

**Comment by jmaris** [comment]
Hi Tygrain, When I uncheck this box it removes blur entirely, my goal is not to remove blur, but rather to have blur but not remove the colour of the panel.

In short: my theme has a semi-transparent white panel, i want the panel to stay semi transparent and white, but for blur to be applied without getting rid of the semi-white colour.

**Comment by aunetx** [comment]
I think I understand your request, but I can't do a lot of things right now, except giving you a quick hack! But for that, could you tell me the version of gnome you use? (so I can know which version of the extension you have)

**Comment by jmaris** [comment]
Hey, thanks or the reply, i'm currently running on 40.5 (Manjaro)

**Comment by aunetx** [comment]
You can try changing the file `.local/share/gnome-shell/exrensions/blur-my-shell@aunetx/stylesheet.css`, and remove the part:

```css
 ​#​panel​.​transparent-panel​ { 
 ​    ​background​:​ transparent; 
 ​    ​transition-duration​:​ ​500​ms​; 
 ​}
```

And then reload the shell, but this change will only last until next extension's update

**Comment by jmaris** [comment]
Thank you ! Should I leave this issue open or close it ?

**Comment by aunetx** [comment]
You can leave it open for others to see it, I will need to add a config option anyway :)
