### ISSUE TITLE
Yesterday commit makes many artifacts

### ISSUE THREAD

**Issue by FiestaLake** [aunetx/blur-my-shell#146]
https://github.com/aunetx/blur-my-shell/commit/e616b2a8c0b6d2cba8350cfde3afcb4cb5fef4df
This commit makes many artifacts in Gnome 40.5, Arch Linux.
Reverting this helped eliminating artifacts in my situation.

![photo_2021-11-09_23-29-02](https://user-images.githubusercontent.com/68979855/140942478-380a41c6-c5aa-4a17-9e10-1e51da12e22d.jpg)

**Comment by aunetx** [comment]
Thanks for the info, I don't know why this would cause artefacts (it only prevents callbacks from crashing, no regression should occur here... I will push a commit in a minute, could you tell whether this works again for you?

**Comment by aunetx** [comment]
This may fix it

**Comment by FiestaLake** [comment]
Will try now

**Comment by FiestaLake** [comment]
Yeah it works fine now. Thanks.

**Comment by aunetx** [comment]
Thanks a lot!
