### ISSUE TITLE
Only works on Overview with Sigma in 0

### ISSUE THREAD

**Issue by lucioeiras** [aunetx/blur-my-shell#150]
I'm using Ubuntu 21.10 with GNOME 40 and the blur affects the topbar normally, but only applies on Overview when I change the Sigma value to 0.

![image](https://user-images.githubusercontent.com/67290471/141796950-2b0fc4af-d86e-4ca4-9419-091ad9313da8.png)

![image](https://user-images.githubusercontent.com/67290471/141797046-066ef5ea-fd66-4749-92cc-ad1abe893849.png)

**Comment by nilsoffermann** [comment]
I'm having the same issue. Though only every other time. Sometimes it blurs with sigma =/= 0, but the behavior is really inconsistent :/

**Comment by dolpa** [comment]
same with my system ubuntu 21.20

**Comment by Awoolyx** [comment]
@lucioeiras Off-Topic but, can I have a link to that beautiful background please

**Comment by aunetx** [comment]
This seems to be a duplicate of #40, closing this so I know where to work!
