### ISSUE TITLE
Blur multiple panels (Dash to panel)

### ISSUE THREAD

**Issue by Sultech** [aunetx/blur-my-shell#152]
I have 3 monitors and only the primary monitors panel gets blurred. Would it be possible to blur all of the panels.

![1](https://user-images.githubusercontent.com/30802163/143257826-09ae2d49-c8b3-415a-ba84-30c84701d449.png)

![2](https://user-images.githubusercontent.com/30802163/143257843-82fba7b9-1ff4-4110-808f-e0a6356c6f70.png)

![3](https://user-images.githubusercontent.com/30802163/143258031-8df7f2cc-a4e4-435d-af24-0a2b0307a71f.png)

**Comment by PixsaOJ** [comment]
#68 Duplicate

**Comment by PixsaOJ** [comment]
Instead Main.panel in panel.js. It should be using array from global.dashToPanel.panels

Maybe not duplicate but here is solution, I just dont know how to implement it.

**Comment by aunetx** [comment]
Thanks @PixsaOJ, using this solution will be straightforward :) I will see to implement it tomorrow!

**Comment by aunetx** [comment]
It is, actually, not so straightforward, as my current implementation does not take into account the possibility that I could create multiple blur widgets... But with some work, this should be fixed soon!

**Comment by PixsaOJ** [comment]
> It is, actually, not so straightforward, as my current implementation does not take into account the possibility that I could create multiple blur widgets... But with some work, this should be fixed soon!

Yeah, I remember the code was oriented towards connecting 1 panel with signals and applying effects to it.  Whereas now it needs to do things with an array of panels.

**Comment by aunetx** [comment]
No, sorry, I am very busy with my exams, and I spend my free time either on Panel Corners or on #180...

I will probably do this for gnome 42, in some months

**Comment by aunetx** [comment]
I actually quite progressed: you can try #306, it may work directly.

However, ...I've not tested it with multiple monitors yet :) so it may behave weirdly (or not work at all), however this will be quick from now on.

Note that even if it works right now, the implementation still lacks the ability to dynamically blur panels when a monitor is connected after the extension is loaded.
