### ISSUE TITLE
Visual artifacting in app grid folders when Blur My Shell is enabled

### ISSUE THREAD

**Issue by rdong8** [aunetx/blur-my-shell#156]
Using Blur My Shell on an AMD R7 5700U (iGPU) on Wayland. Opening the folders in the app grid while blur my shell is enabled causes visual artifacts. Please see the demo below. The screen recording is not actually able to capture the issue but you can try to reproduce it by following the steps I took.

https://user-images.githubusercontent.com/66289396/145504261-79038a1b-3853-4639-8841-0fac6997bf11.mp4

**Comment by aunetx** [comment]
Thanks for opening the issue, I will investigate!

**Comment by aunetx** [comment]
Closing this as this should have been fixed for quite a long time, please reopen if not!
