### ISSUE TITLE
Actor is Null Gnome 41.2 (Fixed)

### ISSUE THREAD

**Issue by VictoryPlayZx90** [aunetx/blur-my-shell#159]
![image](https://user-images.githubusercontent.com/79135460/147382137-db858d4c-7d6f-40cd-94f9-056722ed1914.png)

**Comment by VictoryPlayZx90** [comment]
GNOME in Arch Linux.
im a noobie so i don't know much about linux.

**Comment by VictoryPlayZx90** [comment]
It fixed itself.....

**Comment by blickers** [comment]
What do you mean by "It fixed itself" ?

The problem still exists.
Try to lock the screen, then unlock.
Blur my shell will crash with an error saying "actor is null ".
A quick restart of the shell (Alt + F2 and 'r') fixes the issue, but messes up my window placements of course.
Hopefully it can be fixed, cause I think this extension makes GNOME look beautiful.

**Comment by AI-ien** [comment]
It's not fixed, please change the title.

**Comment by aunetx** [comment]
Closing this as a duplicate :)
