### ISSUE TITLE
Blur gnome shell menus

### ISSUE THREAD

**Issue by titi8530** [aunetx/blur-my-shell#16]
Ajouter le blur sur les menus de la top bar.
Merci.

**Comment by aunetx** [comment]
Salut, j'aimerais beaucoup faire ça mais cela demanderait malheureusement beaucoup trop de maintenance...

Pour aller à ce niveau, il faudrait implémenter le blur en CSS pour qu'il puisse être utilisé n'importe où (ce qui signifierait que mon extension ne servirait plus à rien, et ce serait bien mieux).

Mais depuis mon extension, cela voudrait dire faire en permanence des boucles pour trouver à quels menus je dois appliquer le blur, trouver la meilleure manière (en supprimant le background, ou alors just lui appliquer le blur, quel type de blur mettre...)

Et c'est malheureusement trop de travail pour le maigre développeur que je suis, je suis désolé :(

Mais on peut surtout espérer que le blur sera natif d'ici Gnome 40 (ou Gnome 41, 42... c'est long)

**Comment by titi8530** [comment]
Je m'en doutais un peu !Merci encore pour cette extension. En espérant que la nouvelle implémentation de gnome 40 ne casse pas tout.Bonne continuation.
    Le mercredi 20 janvier 2021 à 13:25:35 UTC+1, Aurélien Hamy <notifications@github.com> a écrit :  
 
 


Salut, j'aimerais beaucoup faire ça mais cela demanderait malheureusement beaucoup trop de maintenance...

Pour aller à ce niveau, il faudrait implémenter le blur en CSS pour qu'il puisse être utilisé n'importe où (ce qui signifierait que mon extension ne servirait plus à rien, et ce serait bien mieux).

Mais depuis mon extension, cela voudrait dire faire en permanence des boucles pour trouver à quels menus je dois appliquer le blur, trouver la meilleure manière (en supprimant le background, ou alors just lui appliquer le blur, quel type de blur mettre...)

Et c'est malheureusement trop de travail pour le maigre développeur que je suis, je suis désolé :(

Mais on peut surtout espérer que le blur sera natif d'ici Gnome 40 (ou Gnome 41, 42... c'est long)

**Comment by aunetx** [comment]
Merci c'est gentil ! J'attends avec impatience gnome 40, donc si l'implémentation casse je la fixerai le plus vite possible :)

A bientôt !
