### ISSUE TITLE
Double background in dash to dock with blur my shell

### ISSUE THREAD

**Issue by hackingguy** [aunetx/blur-my-shell#162]
I am experiencing double background issue with dash to dock on gnome 41 after enabling blue my shell extension with it!

![Screenshot from 2022-01-03 13-46-36](https://user-images.githubusercontent.com/28388650/148195274-0027595c-0ca1-45b7-b348-087eb013916e.png)

System Info:
```
Gnome: 41
WM: Wayland
Theme: WhiteSur-gtk-theme
Distro: Manjaro 21.2.0
Kernel: 5.15.7-1
```

Dash to dock working perfectly on disabling Blur My Shell!

**Comment by aunetx** [comment]
This is a mix of #8 (no way to round the corners of the blur effect, not fixable by me), #154 (that I am trying to fix now) and the fact that you need to disable the opacity in dash-to-dock settings to see the blur effect in action! (and set square corners too, else #8 will give you ugly corner semi-rounded corners)

**Comment by hackingguy** [comment]
Sad part is I cannot use two of the best extensions simultaneously 🥲🥲

**Comment by aunetx** [comment]
Sorry for this :( but you can still try with square corners, it's pretty once you get used to it (but definitively does not mimic macos)!

For the scaling bug (#154), this should be fixed soon
