### ISSUE TITLE
extensions stopped working after update to v 27

### ISSUE THREAD

**Issue by teahwiz** [aunetx/blur-my-shell#173]

**Comment by aunetx** [comment]
Have you tried to restart the shell (by logout/login)?

**Comment by TomasGlavina** [comment]
Yup same here, tried to restart the shell, restart the pc, unninstall the extension and install from source. But it isnt working anymore. First after the update, it gave error. Then it turns on and seems its fine but it doesn't do anything

**Comment by b-swarniim** [comment]
same issue. not working after update v27. ready to provide any details that might be useful to fix this issue.

**Comment by TomasGlavina** [comment]
No idea what changed, but today is working perfectly :+1:

**Comment by teahwiz** [comment]
started working after a restart

**Comment by b-swarniim** [comment]
started working after a system reboot. sorry for bothering.

**Comment by aunetx** [comment]
No worry, thanks!
