### ISSUE TITLE
Feature request: blur search bar

### ISSUE THREAD

**Issue by pesader** [aunetx/blur-my-shell#174]
Since the dash and the search bar have the same color on GNOME by default, I think being able to blur the search bar as well would add a much more consistent (and more beautiful) look to the blurred shell.

| Default | Blurred|
| ----------|------------|
| ![image](https://user-images.githubusercontent.com/65264536/150061824-bb6b7417-97b4-47f2-8b86-5a5cf87aec14.png) |  ![image](https://user-images.githubusercontent.com/65264536/150061833-d14de7a5-73c4-424c-b837-57e43208e503.png)|

Perhaps this could be achieved by tweaking the transparency of the search bar, as mentioned in issue #60, while letting the Overview background take care of the blurring itself.

And thanks a lot for Blur my Shell! It made my desktop truly stunning :star_struck: 

Edit: could the search result cards also be blurred with a similar approach?

**Comment by aunetx** [comment]
This is a good idea, I will permit this once the preferences are rewritten completely! This will be soon normally :)

And thanks a lot! For the search results of course, I will permit this in next update!

**Comment by aunetx** [comment]
I will implement this in #180 I think, so it may take some time to get this merged (as this PR is very very big), but it should be easier to manage :)

**Comment by pesader** [comment]
No hurry at all! I appreciate that you're taking your time to "iron out" the application, it makes a world of difference :)

Either way, thanks a lot for the updates!

**Comment by aunetx** [comment]
Hello again, I more or less fixed this in last commit, now the search bar uses the same opacity as the dash.

I will use a separate setting soon, but I don't really want to clutter more the current extension, as everything I do will need to be done again in order to merge #180, and that is a lot of work...

**Comment by aunetx** [comment]
This is fully fixed with #180, with a separate setting for this :)
