### ISSUE TITLE
Double dock background in Gnome 41 (Fedora) 

### ISSUE THREAD

**Issue by OlaoluwaM** [aunetx/blur-my-shell#176]
Here is the issue from the `dash-to-dock` repo. Does blur-my-shell cause this?

micheleg/dash-to-dock#1623

**Comment by CorvetteCole** [comment]
Looking at the code... I wouldn't think so. does turning it off fix it?

**Comment by OlaoluwaM** [comment]
Do you mean `blur-my-shell`? Yes turning that off fixes the issue

**Comment by OlaoluwaM** [comment]
Without `blur-my-shell`

![image](https://user-images.githubusercontent.com/37044906/150721026-1f876397-61af-4ffe-9b59-cc965307d183.png)

**Comment by OlaoluwaM** [comment]
With `blur-my-shell`

![image](https://user-images.githubusercontent.com/37044906/150721079-586c93fb-aa3d-48de-9f53-f6c20381f90e.png)

**Comment by OlaoluwaM** [comment]
Take a look at the edges of the second picture

**Comment by CorvetteCole** [comment]
ah, yeah. we can't blur curved things yet :(. Gnome only supports rectangles. I have a few ideas for hacky workarounds but nothing yet on paper

**Comment by CorvetteCole** [comment]
this is a duplicate of #8, will close and you can follow there :)
