### ISSUE TITLE
Blur with rounded corners

### ISSUE THREAD

**Issue by CorvetteCole** [aunetx/blur-my-shell#185]
Putting this here just to track it. I have a crazy idea to make this happen using masking and it might just work. I will test it and update this later

**Comment by aunetx** [comment]
Cool, keep me updated if anything works :)

**Comment by stpnwf** [comment]
> Putting this here just to track it. I have a crazy idea to make this happen using masking and it might just work. I will test it and update this later

Would this affect the blur on rounded docks (such as Floating Dock)? If so, I was about to create an issue saying that the blur (in version 22 on Gnome 3.38) treats the docks as a rectangle... Glad you guys are working on it!

**Comment by CorvetteCole** [comment]
yes, unfortunately all blur is rectangular right now. I've done some initial testing and I've got a rough prototype with curved blurring working, but it's very rough. I'm continuing to work on ways to refine this so I can feel comfortable merging it

**Comment by aunetx** [comment]
Thanks a lot @CorvetteCole! I hope it will work :)

I will see what I can do about blurring panel corners (as I maintain them, now they are removed from gnome 42, see https://github.com/aunetx/panel-corners); I had an interesting conversation with @Schneegans on matrix about it

**Comment by CorvetteCole** [comment]
Main problem right now is it causes even more artifacts. like we need more of that. even the paint vfunc doesn't help :/. I've got a few more ideas to fix it

**Comment by CorvetteCole** [comment]
@aunetx have you seen this? https://github.com/yilozt/mutter-rounded

Pretty wacky that a patched mutter is the easiest available solution as of now.. still working on my janky solution but it really doesn't work well

**Comment by aunetx** [comment]
I have seen it, and that looks really overkill for what we want to have...

When you can, please share me your solution; I opened #265 with the intent to fix it too -- I have some ugly glsl effect to create corners; and the only solution I really see right now (other than creating a lot of dummy actors to mimic a curb, which may be what you tried) would be to create a custom blur effect which integrate directly this effect.

**Comment by LokiFawkes** [comment]
Would absolutely love to see this fixed. There a testing branch for that feature? I’d just dig for it but it can’t hurt to ask too.

**Comment by CorvetteCole** [comment]
closed in favor of #8 as duplicate
