### ISSUE TITLE
Weird Visual Artifacts on Apps

### ISSUE THREAD

**Issue by GalacticHog** [aunetx/blur-my-shell#19]
I'm using this, master compiled from here on Ubuntu 20.10 with Gnome 3.38.
My machine has a Nvidia GPU, mentioning this for obv reasons.

Basically when I open an app like gnome tweaks for example and move the mouse around within the app, elements of the app that would animate completely disappear and I can see my background through the chunks that have disappeared.

I can't take a screenshot as it makes gnome shell crash, sorry :(

**Comment by Saren-Arterius** [comment]
Try use the bad perf option and re-enable the extension.
![image](https://user-images.githubusercontent.com/4948919/109101805-6f230b00-7762-11eb-806a-b2c8d87adbdb.png)

For the crash problem, either apply https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1673 to gnome-shell yourself or wait for the patch to land.

**Comment by GalacticHog** [comment]
Yeah I've tried this already but I just did again to make sure, the bug still triggers with "no artifacts, bad perfs" checked.
Also this bug is triggering for me even with all other extensions turned off, so I can rule out a conflict.
Here's a video showcasing it in case it's helpful:

https://user-images.githubusercontent.com/7698035/109179413-c5537680-7781-11eb-9019-05b8483776a7.mp4

**Comment by GalacticHog** [comment]
Yeah I'm already using that option, and the bug is triggering for me even with other extensions off so I can rule out a conflict.
Here's a video showing off what the bug actually looks like:

https://user-images.githubusercontent.com/7698035/109181805-3dbb3700-7784-11eb-86b7-b4f63a3ad275.mp4

**Comment by aunetx** [comment]
Ouch, that's nasty... I really don't know how my extension do that (I don't touch to anything about GTK or other windows), so I don't know where to begin...

Does your shell outputs some logs? (you can use `sudo journalctl /usr/bin/gnome-shell`, and see if there are some errors or logs from my extension)

**Comment by GalacticHog** [comment]
It's all dated February 13th which is before I even switched to this extension, so I'm guessing that means there's no mention of anything from this extension.
With that said, here's the pastebin: 
https://pastebin.com/f7VfAx3B

**Comment by aunetx** [comment]
Thanks a lot! But (and it's a problem with journalctl), this is only the first things stored by journald... There are probably a lot of logs after this (probably up to 50k lines, maybe more): to get the last ones (where my extension could have created logs, which it does anyway on startup), you can press the 'get me down' key on your keyboard (so you don't have to scroll down everything)

**Comment by GalacticHog** [comment]
Is there a way to just head straight to the bottom, it seems there's some issue with Ubuntu Dock (even though I don't use it) and there are seemingly never-ending lines of the same thing relating to that.

**Comment by TecCheck** [comment]
I noticed this bug too. Just wanted to add that if you move the window around a bit the artifacts are gone. At least on my machine.

**Comment by andrewaclear** [comment]
Ya I have the same as @TecCheck

**Comment by aunetx** [comment]
OK, I got the bug on my new laptop.

One simple thing I did which removed the bug is installing this extension : https://extensions.gnome.org/extension/545/hide-top-bar/

I don't know how it removes the glitches, but I will try to investigate asap

**Comment by genericusername3** [comment]
I've had that bug for quite a while too.
I have played around with this a little and want to add a little more detail on when exactly the bug occurs:
- A newly opened window is the only window on a workspace (minimized windows don't count towards this)
- The window is not maximized
- The window uses GTK
    - it happens with Sublime Text too, I don't know if Sublime uses GTK
    - I don't know whether this is specific to GTK3 or if GTK2 is also affected, I've tried a few apps that I think are GTK2 — they seem fine
- The window has not been dragged or resized yet
- The mouse moves over a GTK widget
    - I'm guessing this makes GTK re-render widgets, as it primarily happens on widgets that have hover states

The bug goes away on windows that:
- Have been on the same workspace with another window
- Have been moved or resized
- Have been minimized
- Have been maximized

While I'm fairly certain that none of these logs are of help, here is the output of `sudo journalctl /usr/bin/gnome-shell` in the few minutes around an occurrence of this bug:

```
Mar 08 18:53:16 hostname gnome-shell[66075]: g_hash_table_foreach: assertion 'version == hash_table->version' failed
Mar 08 18:53:16 hostname gnome-shell[66075]: Ignoring length property that isn't a number at line 1350, col 24
Mar 08 18:53:26 hostname gnome-shell[66075]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Mar 08 18:54:07 hostname gnome-shell[66075]: g_hash_table_foreach: assertion 'version == hash_table->version' failed
Mar 08 18:54:22 hostname gnome-shell[66075]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```
(no, my PC is not actually named `hostname`)

Here is some more info about my PC: 
Manjaro 20.2.1, Wayland, Gnome shell 3.38.3, Radeon RX 590 with video-linux drivers

**Comment by TecCheck** [comment]
I'd like to add that the bug still occurs when I have multiple windows but on different screens.

**Comment by genericusername3** [comment]
> I'd like to add that the bug still occurs when I have multiple windows but on different screens. But only one window per screen.

I can confirm this, however, only the newest/topmost window is affected

**Comment by aunetx** [comment]
Sorry for the bug guys... Do you experience the bug with version 5 (before overview animations were fixed)?
I suspect it as the overview is pretty buggy when you play with its opacity, but I have no idea why!

If it is the case, I may be able to correct it (as it reduces a lot where I need to search...), but else I don't have any idea for the moment!

**Comment by aunetx** [comment]
If you still experience this bug with Gnome 40, please tell it to me :)

**Comment by GalacticHog** [comment]
I've just come back to add that I've been using the GNOME 40 version of this add-on since it was released and the bug hasn't shown up since for me, I'd go so far as to say this is the best experience I've had with the extension, so thank you.

**Comment by GalacticHog** [comment]
I no longer experience this issue since the GNOME 40 version, it's running very well and looks great!

**Comment by aunetx** [comment]
Cool thanks a lot, closing this issue then :)
