### ISSUE TITLE
Broken on Gnome 42 main / 42.beta

### ISSUE THREAD

**Issue by VitalyAnkh** [aunetx/blur-my-shell#191]
After building the latest gnome-shell and gjs, blur-my-shell reports `Main.panel._leftCorner is undefined`. Maybe it's caused by the mozjs, which updates from version 78 to version 91.
![image](https://user-images.githubusercontent.com/24508452/154922999-1b7f609b-370d-407a-9166-7af2f956f36b.png)

**Comment by VitalyAnkh** [comment]
Oh it's reported already but not as a standalone issue: https://github.com/aunetx/blur-my-shell/pull/186#issuecomment-1030506997.

**Comment by aunetx** [comment]
Fixed by #189, will push to eog :)
