### ISSUE TITLE
Dark corners appear in gnome 42 with version 28

### ISSUE THREAD

**Issue by SViN24** [aunetx/blur-my-shell#192]
![image](https://user-images.githubusercontent.com/51864332/155073969-bddd11dc-a3b2-4b8c-b57b-ebe0f8092116.png)

**Comment by retrixe** [comment]
Not occurring with me on Fedora 36 Prerelease with gnome-shell and Mutter 42.rc:
![image](https://user-images.githubusercontent.com/6884828/158803814-91cde8c6-e27b-4b77-931d-e478b44a9101.png)

**Comment by aunetx** [comment]
Hello @SViN24, could you test again with latest version of gnome? There is no reason why this could happen, except if you have another extension installed to show the panel corners

**Comment by SViN24** [comment]
![image](https://user-images.githubusercontent.com/51864332/160569877-5e28c4fa-65da-4ca1-a41d-789e92f7079f.png)
can confirm it does not seem to happen in gnome 42

**Comment by aunetx** [comment]
OK, cool! Closing this, reopen later if needed
