### ISSUE TITLE
Blur applied on dock is not stable

### ISSUE THREAD

**Issue by MohammedAijaaz** [aunetx/blur-my-shell#2]
The blur applied to the dock flickers at times and then goes back to normal when hovered on the dock.

**Comment by aunetx** [comment]
Yeah I have noticed this issue too... I will try to fix this, but that will not be entirely fixed until gnome-shell itself is patched

This is due to the shadows created by hovering the dock being animated, so I can't "just" repaint the effect everytime the mouse enters or leaves a button :(

**Comment by MohammedAijaaz** [comment]
ah cool, great work by the way. You should definitely extend it to cover context-menus etc. as well.

**Comment by aunetx** [comment]
Thanks a lot! I really hope that all of this is fixed soon :(

I think about theming some context menu actually, but this is a lot harder than all I did for the moment if it is not implemented in gnome itself so...
