### ISSUE TITLE
Blur the background of the window selection screen in the gnome42 screenshot

### ISSUE THREAD

**Issue by nexryai** [aunetx/blur-my-shell#202]
It would be nice to have the ability to blur the background of the window selection screen in the gnome42 screenshot.
![img](https://i0.wp.com/9to5linux.com/wp-content/uploads/2022/02/gss-5.webp?ssl=1)

**Comment by aunetx** [comment]
Done in 91cc5e7, that was surprisingly easy :)

If you want to test, you can use the branch `preferences-rewrite`, this will be available when #180 is merged!
