### ISSUE TITLE
Issue rendering folders in application grid

### ISSUE THREAD

**Issue by logant547** [aunetx/blur-my-shell#205]
HI! Just noticed this bug now with Fedora 36 Workstation, and the corners on the folders look buggy. I have attached a screenshot below.
![Screenshot from 2022-03-30 15-22-01](https://user-images.githubusercontent.com/45543257/160741117-32b0129b-d4b7-49b4-bacb-fd92eae9e6e5.png)

**Comment by theodormoroianu** [comment]
This was mentioned in #200 too. You can fix it by following the steps mentioned [here](https://github.com/aunetx/blur-my-shell/issues/200#issuecomment-1069551001)

**Comment by logant547** [comment]
OK, thanks for the info.
