### ISSUE TITLE
maximized application blur too small

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#206]
when I maximize a window the blur doesn't cover the whole application background 
![Screenshot from 2022-04-02 18-25-21](https://user-images.githubusercontent.com/51063733/161403289-ec43e71d-64ab-4c6b-ba23-1929ec66cc96.png)

**Comment by aunetx** [comment]
Thank you, is it happening consistently?

**Comment by andrewaclear** [comment]
No problem. Ya it is.

**Comment by andrewaclear** [comment]
Looks like it is working now! Thanks guys!

**Comment by andrewaclear** [comment]
Ya it seems all good! I'll close this issue.

**Comment by aunetx** [comment]
Cool, thank you :)

**Comment by andrewaclear** [comment]
Thank you!
