### ISSUE TITLE
application blur disabled in overview

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#207]
this may have been on purpose, but I feel it would look a lot better if the applications were still blurred in the overview
![Screenshot from 2022-04-02 18-27-35](https://user-images.githubusercontent.com/51063733/161403355-f94b483f-8505-40f9-b17e-5ab4b38b65dd.png)

**Comment by aunetx** [comment]
This is of course not on purpose, but I don't know how to do this :) I will try more when I have some time!

**Comment by andrewaclear** [comment]
No worries at all. For sure :)

**Comment by aunetx** [comment]
Hello, I know the blur position isn't right, but I can't do much about it for the moment...
As the original bug is fixed, I close this issue; and the issue you described is now in #375.
