### ISSUE TITLE
Errors out on latest extension version on Gnome shell 41.5

### ISSUE THREAD

**Issue by sjaks** [aunetx/blur-my-shell#208]
I am running on Fedora 35 with Gnome shell version 41.5. The plugin cannot be installed after an update released on extensions.gnome.org today.

![image](https://user-images.githubusercontent.com/44066308/161606755-e47042d1-d636-4497-8311-20a47839e9c2.png)

**Comment by aunetx** [comment]
Hello, thanks for the issue! Have you restarted gnome after the update? Gnome shell weirdly does not support updating most extensions seamlessly

**Comment by sjaks** [comment]
Thanks! A refresh with `alt+F2` + `r` helped.
