### ISSUE TITLE
Window blur issue when changing workspaces

### ISSUE THREAD

**Issue by JavkhlanK** [aunetx/blur-my-shell#209]
Just got version 30 to test out the experimental app window blur, and it works! :tada: (at least partially).

I found out it's glitching when switching workspaces. For example, having gnome-terminal (must put `gnome-terminal-server` into prefs) blurred, then changing workspaces, and going back to Terminal's workspace can result in this:

https://user-images.githubusercontent.com/40118124/162307409-fe411641-5d25-44b0-957f-9114f65ab16d.mp4

Sorry for the terrible video quality, but I think GNOME Shell's built-in tools only encodes in VP8, and probably with a low bitrate too.

**Comment by JavkhlanK** [comment]
Oh and this is probably important too: I ran that on GNOME 42, with the currently latest updates for Fedora 36.

**Comment by aunetx** [comment]
Thanks for opening the issue, and especially for testing the extension!

To be honest, the applications blur is kinda beta, I will put a warning about it in the preferences before finally releasing it to extensions.gnome.org...

I don't really know how I could (reliably) blur the apps during the workspace switch, or in overview, but it is the finality of that feature, of course. I think @CorvetteCole may be better than me about it, and @ckissane too obviously if he has some tips (he is the maintainer of Blur Me, which already blur the applications, although quite differently).

I can't do a lot of things myself right now to be honest, but if somebody wants to try something, don't hesitate about sending a PR!

**Comment by aunetx** [comment]
Hello, this should have been fixed in last versions, is it the case?

**Comment by JavkhlanK** [comment]
Seems fixed! (Fedora Workstation 39, GNOME 45.1)
