### ISSUE TITLE
Application blur and window list extension not working in gnome 42 (Arch)

### ISSUE THREAD

**Issue by KCGD** [aunetx/blur-my-shell#210]
As far as i know, these are the only issues

**Comment by aunetx** [comment]
For the applications blur, does following #214 works? I will need to explain more in the preferences :)

And I did not even test window list extension, sorry for this :/ I will do when I can!

**Comment by aunetx** [comment]
Window list seems to be working for me, please re-open if needed.
I also changed some artifacts options to remove artifacts even with the default option.

**Comment by KCGD** [comment]
Just wanted to comment to say I found the issue. Nothing was wrong with the extension. It just switched from a blacklist to a whitelist, in relation to which windows to blur. If you go to the application section of the extension's settings, you can enter the program's WM class in the whitelist field, after that it'll start to blur it.
