### ISSUE TITLE
Latest commit breaks the app folder opening.

### ISSUE THREAD

**Issue by FiestaLake** [aunetx/blur-my-shell#213]
https://github.com/aunetx/blur-my-shell/commit/88bdf0d0e159461f0d3dc29d561adc3cd9bbf633
Gnome extension app says: 'invalid assignment to const 'EaseTimeouts'

**Comment by aunetx** [comment]
Oh yeah sorry I forgot about it... I was trying to correct something but did not try it, and pushed it just not to lose anything, but I forgot that the master branch is actually used by arch user repository etc

I will remove this soon

**Comment by aunetx** [comment]
Done :)
