### ISSUE TITLE
What does "application" box do when checked?

### ISSUE THREAD

**Issue by Fenimoure** [aunetx/blur-my-shell#214]
I used whitesur theme and the transparent parts of windows weren't blurred.

**Comment by aunetx** [comment]
Hello, that box does two things (that should be more explicit):
- adds blur to the applications that explicitly ask for (via the `blur-provider` mutter hint)
- permits the user to add applications name in the whitelist, for example `Gnome-terminal` for the default pre-42 terminal. You can get the name of the window you want with `xprop|grep WM_CLASS` and then clicking on the window you want, if you are under x11 (not tested this with wayland). Of course there will be a nice UI to explicitly choose which windows, etc to blur, but for the moment this is the best I can do :)

This is pretty beta and does not work properly when in overview, workspace change, ... but you can test this!

**Comment by aunetx** [comment]
I explained in preferences description, closing this.
