### ISSUE TITLE
Odd boxes in apps groups

### ISSUE THREAD

**Issue by mcardia** [aunetx/blur-my-shell#215]
When you open a gnome application group in the launcher, some box apears (like in the screenshot)

![image](https://user-images.githubusercontent.com/11967511/162725376-b570d5ba-db1d-4513-a0a5-cf98e21956d5.png)

I'm using the latest version for gnome 41.5 (fedora)

Thanks

**Comment by aunetx** [comment]
Sorry, can you try with last version (from github)? I was actually trying to remove these entirely, so more appeared during the development :)

**Comment by aunetx** [comment]
Closing this as it should be resolved with last commit, and soon in eog.

**Comment by aunetx** [comment]
Closing this as it does not seem to happen any more (at least not for me, and the bug has not been mentioned again)
