### ISSUE TITLE
error after upodate the extension

### ISSUE THREAD

**Issue by ivaang94** [aunetx/blur-my-shell#216]
I update the extension today, and I get an error message from the gnome-shell-extensions page.
![image](https://user-images.githubusercontent.com/13439236/162803181-ca8d9c9f-5326-41a9-b940-2af1523c29ae.png)
Im tried to re-install the extension without success. 

i attach my system specs:
![image](https://user-images.githubusercontent.com/13439236/162803377-58de6f94-9209-438e-b3a5-217dcf157d06.png)

**Comment by aunetx** [comment]
Hello, did you try to restart gnome after installing the extension? Logging out and in again for example

**Comment by ivaang94** [comment]
Hello! I was trying with the alt+2 and running the r command without success, but after logging out and in again, it works.
Thanks

**Comment by aunetx** [comment]
Okay thanks!
