### ISSUE TITLE
Add option to blur top bar only when windows are not maximized or tiled

### ISSUE THREAD

**Issue by geodro** [aunetx/blur-my-shell#217]
I like to have my top bar integrate with apps and have it permanently on screen. But it looks better black when windows are maximized. You be great to have it blurred only when desktop is free.

![image](https://user-images.githubusercontent.com/289809/162910316-3cfd8049-98f7-4df5-a6d0-7e7ece252f59.png)

![image](https://user-images.githubusercontent.com/289809/162910584-28f5783f-0af6-4dc2-a970-d1bbe4601d40.png)

**Comment by aunetx** [comment]
This look very similar to #90, is this the same request?

I'm sorry, I tried to work on this at one time -- but it is quite hard to do, so I will need some time...

**Comment by geodro** [comment]
Yes, it looks similar with that requests. Closing.
