### ISSUE TITLE
add noise texture option 

### ISSUE THREAD

**Issue by fadihajjej** [aunetx/blur-my-shell#218]
blur might look bad on older screens with lower contrast ratios due to the very small incremental hue changes, Windows combats this with some noise on to of the blur so it evens it out and makes it look smoother also noise on top of blur might look nice even on high end screens.

**Comment by aunetx** [comment]
That's a good idea! That will require quite a lot of work, but I would love to provide this as an option indeed :)

**Comment by JugadK** [comment]
Do you have an example of how much noise they use? It should not be too hard to implement with something like #230, though I feel like you would want to redo how the effects are added to make it easier to add and swap more effects in the future.

**Comment by aunetx** [comment]
Done :)

**Comment by fadihajjej** [comment]
amazing
