### ISSUE TITLE
Error (version 32): "child" is of undefined type

### ISSUE THREAD

**Issue by torculus** [aunetx/blur-my-shell#220]
When disabling the extension (version 32), the following error code is thrown `Expected an object of type ClutterActor for argument 'child' but got type undefined`

**Comment by aunetx** [comment]
Could you give me more detailed logs with `sudo journalctl /usr/bin/gnome-shell|grep blur-my-shell`?

This way I see exactly the line that caused this to happen

**Comment by torculus** [comment]
Yeah, sorry about that. Here's the output:
```
JS ERROR: Extension blur-my-shell@aunetx: Error: Expected an object of type ClutterActor for argument 'child' but got type undefined
                                            disable/<@/home/torculus/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:111:19
                                            disable@/home/torculus/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:110:44
                                            disable@/home/torculus/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:117:31
```

Seems to be [here](https://github.com/aunetx/blur-my-shell/blob/585cc5e75315337e3f77cd38a266243db97e2c4b/src/components/screenshot.js#L111)

**Comment by aunetx** [comment]
Thank you! I don't know why it break, but at least that's easy to prevent :) will do soon!

**Comment by aunetx** [comment]
Fixed in last commit, sorry for the delay!
