### ISSUE TITLE
Error: Expected an object of type ClutterActor for argument 'child' but got type undefined

### ISSUE THREAD

**Issue by lcbravo** [aunetx/blur-my-shell#225]
Dear developers, 

Since I upgraded to gnome 42 I've been getting random crashes on the extension. It just stops working and I need to start another session in order for it to work again.

The error message that I get is somewhat generic and I wasn't able to nail it down to a specific cause:

>sudo journalctl /usr/bin/gnome-shell | grep blur-my-shell

> abr 20 18:00:11 xxxxxx gnome-shell[18331]: JS ERROR: Extension blur-my-shell@aunetx: Error: Expected an object of type ClutterActor for argument 'child' but got type undefined
>                                             disable/<@/home/xxxx/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:111:19
>                                             disable@/home/xxxx/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/screenshot.js:110:44
>                                             disable@/home/xxxx/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:117:31

This seems to be related to #220, but in my case it happens randomly and not only when I try to disable the extension.

I'm using Arch Linux and Gnome 42 on Wayland

EDIT: I've already tried to reinstall the extension, but the crashes persist.

Thank you for developing this extension and for your support,

**Comment by lcbravo** [comment]
I've found out that this error occurs when I unlock the screen. This is the same cause of issue #224, but the error I get is quite different.

**Comment by aunetx** [comment]
Thank you for the issue, I don't know why it caused this issue -- like if the extension tried to disable an already-disabled component.

Alas, fixed now :)
