### ISSUE TITLE
Getting an error after new gnome update on Manjaro Gnome

### ISSUE THREAD

**Issue by jakethelizard99** [aunetx/blur-my-shell#236]
here is the error that it gives me any help appreciated. Gnome version: 41.5

TypeError: prefsModule.buildPrefsWidget is not a function

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by oscfdezdz** [comment]
Which version of Blur my Shell are you using? Latest compatible version with GNOME Shell 41.5 is 29.

**Comment by jakethelizard99** [comment]
> Which version of Blur my Shell are you using? Latest compatible version with GNOME Shell 41.5 is 29.

version 33 is what it says

**Comment by aunetx** [comment]
You should actually use version 29 indeed.

If you don't mind having no preferences at all (except if you want to change them using gsettings), you can use the last versions too; but the preferences panel is not compatible.

**Comment by aunetx** [comment]
(btw, how did you install it? maybe there's a bug in extensions.gnome.org)
