### ISSUE TITLE
Support for Gnome 40

### ISSUE THREAD

**Issue by aunetx** [aunetx/blur-my-shell#24]
The extension still does not support Gnome 40:
  - no GTK4 preferences windows
  - no idea how it looks in it, as overview/dash changed

**Comment by RandomnessRobin** [comment]
Hoping to see this extension work in gnome 40 soon. Not sure of that will happen. But i am hoping it does.

**Comment by aunetx** [comment]
I hope too, and of course it will happen!
For the moment, those are the bugs I have:

- [ ] settings need to be ported to GTK4 (should be OK)
- [ ] blur needs to be restored to the top panel after leaving the overview (it is currently not the case in gnome 40)
- [ ] proper animations should be added to the panel
- [ ] overview should be blurred: for this, I need to be able to add an image as a background of the overview (so that I can blur it after, which is easy one the image is there). It would look something [like this](https://redd.it/mtd057)

**Comment by aunetx** [comment]
Panel is done, overview should be OK soon. However, I have a problem with the preferences (I can't open any preference of extension in my testing VM, so I don't know if mine is working...)

**Comment by aunetx** [comment]
Nearly good, it works really better than for gnome 3.38 actually :)
I just need to make sure settings work, and it's good for gnome 40!

To test it, install from the branch "gnome-40"

**Comment by Saren-Arterius** [comment]
Will the new design be like this? https://www.reddit.com/r/gnome/comments/mtd057/in_love_with_this/

**Comment by aunetx** [comment]
Exactly like this yes :)

**Comment by Saren-Arterius** [comment]
That would be holy! Glad to hear! Thanks

**Comment by Saren-Arterius** [comment]
@aunetx I see the panel blur working, but overview's background is still plain color instead of blurred wallpaper. Am I missing something? Or is it gnome theme dependent? Thanks

**Comment by aunetx** [comment]
@Saren-Arterius are you sure that you switched to the "gnome-40" branch?

**Comment by Saren-Arterius** [comment]
Sure

在 2021年4月19日週一 19:37，Aurélien Hamy ***@***.***> 寫道：

**Comment by aunetx** [comment]
If you want to try with this version (you can install it with `gnome-extensions install blur-my-shell@aunetx.zip --force`):
[blur-my-shell@aunetx.zip](https://github.com/aunetx/blur-my-shell/files/6336042/blur-my-shell%40aunetx.zip)

**Comment by Saren-Arterius** [comment]
It is working now. I had to untick and tick overview however. I guess leftover perf caused this.

By the way, lockscreen's blur is affected regardless of the tick.

**Comment by aunetx** [comment]
Thanks for the report!

I had the overview issue too, I don't know why... I guess it is because my extension grabs the wallpaper before it is created, so it gives something weird after login

I did not try lockscreen for the moment, I have a lot of issues with my VMs...
The "no artifacts" option is broken too, because of a depreciation of the `paint` signal which I used a lot...

**Comment by aunetx** [comment]
Thanks for trying @not-a-dev-stein ! I'm sorry I will do it quickly (nearly 1am, time to go to bed) :)

If you want to test with the latest github version (from branch gnome-40, then doing `make pkg` and taking the package from there, or just `make install`), maybe some bugs are fixed now: normally the artifacts selection is better (although selecting the "no artifacts" option will make the extension crash on restart), and the settings are maybe better connected...

But to be honest, I still need to take some more time to figure out all the remaining bugs, and I did not test either dash or lockscreen for the moment.

And thanks for reminding me of the second monitor bug, I forgot to implement it when I rewrote the overview blur! At least this one will be easy to catch tomorrow :)

**Comment by 500InternalError** [comment]
> If you want to try with this version (you can install it with `gnome-extensions install blur-my-shell@aunetx.zip --force`):
> [blur-my-shell@aunetx.zip](https://github.com/aunetx/blur-my-shell/files/6336042/blur-my-shell%40aunetx.zip)

The extension randomly fails with something like "background_parent.getparent() is null" in log.Changing this.background_parent.get_parent().remove_child(this.background_parent); to this.background_parent.remove_child(this.background_parent); fixes the issue(at least for me).
Also the extension doesn't live happy with dash to dock beta with an error "actor is null".No idea about how to fix this.

**Comment by 500InternalError** [comment]
Btw can you please add a dedicate switch to control whether to blur the dash to dock?Switching the dash option on makes the dock looks like a transparent one in overview.So I think switching the dash option off while enabling dash to dock blur might be better.

Great thanks for your work on this,can't wait for it to be completed

**Comment by aunetx** [comment]
@500InternalError could you give me the error log? And did this error happen when you disabled the extension only, or on loading?
I don't really understand why it would bug this way, it seems weird... but gnome is weird anyway :)

And I don't understand your request sorry! Would you want to be able to blur the dash-to-dock dock, but not remove the blur when in overview?
If yes, I could try to add an option for this of course! And for the moment (as I will not work on it now), you can comment lines 138 and 142 of extension.js (`this._dash_to_dock_blur.hide();` and `this._dash_to_dock_blur.show();`)

**Comment by 500InternalError** [comment]
@aunetx  When I just installed the extension and re-login it shows nothing,but when disabling the extension and trying to reenable it gnome shows 
![2021-04-20 18-21-15 的屏幕截图](https://user-images.githubusercontent.com/39024699/115381234-f1312c80-a205-11eb-96d0-f6b5a7627ff7.png)
in log (I don't know how to get more detailed log as I'm not a developer.Really sorry for that)

And if I both enable the dash option and dash to dock,reenable this extension and gnome says
![2021-04-20 18-38-11 的屏幕截图](https://user-images.githubusercontent.com/39024699/115383035-ee373b80-a207-11eb-9e41-696443e5fbff.png)

**Comment by 500InternalError** [comment]
> @500InternalError could you give me the error log? And did this error happen when you disabled the extension only, or on loading?
> I don't really understand why it would bug this way, it seems weird... but gnome is weird anyway :)
> 
> And I don't understand your request sorry! Would you want to be able to blur the dash-to-dock dock, but not remove the blur when in overview?
> If yes, I could try to add an option for this of course! And for the moment (as I will not work on it now), you can comment lines 138 and 142 of extension.js (`this._dash_to_dock_blur.hide();` and `this._dash_to_dock_blur.show();`)

Sorry for my poor description. What I want to say is that blurring both overview and dash makes it look like this
![2021-04-20 18-42-00 的屏幕截图](https://user-images.githubusercontent.com/39024699/115383448-70276480-a208-11eb-922a-1dd483d23579.png)
feels kind of weird.So I think blurring the dash-to-dock but removing the blur in overview might be better

**Comment by 500InternalError** [comment]
@aunetx Oh I found the log:

[Blur my Shell] blurring dash
[Blur my Shell] searching for dash
[Blur my Shell] dash to dock found, blurring it
clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
JS ERROR: TypeError: actor is null
connect@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/connections.js:32:18
blur_dash_from@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:118:26
try_blur@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:80:35
blur_existing_dashes/<@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:69:18
blur_existing_dashes@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:68:37
enable@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:61:14
_connect_to_settings/<@/home/zhenzhe/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:82:41

**Comment by 500InternalError** [comment]
> When disabling the extension:
>[Blur my Shell] disabling extension...
>[Blur my Shell] removing blur from top panel
I guess the extension crashes because it tries to remove blur from panel even if it hadn't blur it(I didn't enable the blur for panel before)

**Comment by carlocastoldi** [comment]
> I guess the extension crashes because it tries to remove blur from panel even if it hadn't blur it(I didn't enable the blur for panel before)

that is indeed the problem.
Commenting out the following line fixes for me:
https://github.com/aunetx/blur-my-shell/blob/b4c941ad856dff70a1e003278fe2ddb3e1874af8/src/extension.js#L60

**Comment by aunetx** [comment]
Ok, I understand why it bugged. Do you use dash-to-dock?
I still not support this extension with gnome 40, and did not test it either...

**Comment by carlocastoldi** [comment]
I do not.
I use no extensions that changes the bottom panel in the overview

**Comment by RandomnessRobin** [comment]
I use dash to dock. But that extension in itself has things not working like icon sizing and opacity. But i mean the blur would be coming from your extension and not the dock so I don't know.

**Comment by 500InternalError** [comment]
Oh, the dash_to_dock.js file misled me😂

**Comment by aunetx** [comment]
To be honest I feel kind of lost... I can't even distinguish bugs between them :/

**Comment by aunetx** [comment]
Oh man I just understood... I forgot to turn my brain on this morning sorry :)
Just like @500InternalError said, I disable the blur eventhough it does not exist... Will fix this asap

**Comment by aunetx** [comment]
That should be fixed in last commit, could you test it and tell me?

**Comment by RandomnessRobin** [comment]
Will try it when I get home in a few hours 2 or 3 and post about it here.

**Comment by carlocastoldi** [comment]
> That should be fixed in last commit (the disabling crash), could you test it and tell me?
> I will try to add support for dash-to-dock soon

that does indeed fix it! Thank you ^^

**Comment by aunetx** [comment]
Added support for dash-to-dock, so no error on enabling either :)

**Comment by aunetx** [comment]
Added support for dash-to-dock, so no error on enabling either :)

**Comment by aunetx** [comment]
Support for gnome 40 is complete, apart from sparse bugs (and of course #31, but I will investigate this separately)
Please reopen an issue if there is any other bug! :)

**Comment by carlocastoldi** [comment]
one small thing I might want to report is that after restarting the shell, dash opacity is not taken into account. It's full opaque.
I actually need to move the slider a little to have it properly set

**Comment by aunetx** [comment]
@carlocastoldi with dash-to-dock? I noticed something similar, but it should normally go away either within 3 seconds (as I settled up a timer to remove it due to a race with dash-to-dock), or when you change workspace

If not, please open another issue so I can keep track of this more easily!

**Comment by carlocastoldi** [comment]
I'm using the default dock.
I'll have to try the extension out for a little longer to see if what you are saying applies to me as well.
If not, I will open a new issue. Thanks ^^

**Comment by RandomnessRobin** [comment]
So the blur on the dash to dock makes the outer shape rectangle. I think someone mentioned but not sure. At least it works. Is disabled Dash to dock for now. 

Also do see some artifacts when hovering over the items in the top panel but that might be normal.

**Comment by aunetx** [comment]
@RandomnessRobin yes, sadly I can't make rounded blur for the moment so the dash is a rectangle... Honestly it's the main reason why I don't use it anymore ^^

And the artifacts are "normal" (because of a gnome bug), but I will try to resolve this very quickly :)

**Comment by 500InternalError** [comment]
Great the fix works. Thanks :)

**Comment by aunetx** [comment]
Cool, thanks a lot for trying :)

**Comment by RandomnessRobin** [comment]
Yes i think part of the reason why Gnome doesn't want to make the dock visible in the home screen is cause they don't want to be similar to Mac OS  even tho it kinda is a least a little bit
