### ISSUE TITLE
Blur layer is too big and doesn't fit the window shape. Sometimes cover the window.

### ISSUE THREAD

**Issue by LMFuture-Me** [aunetx/blur-my-shell#242]
System: openSUSE 20220519
GNOME: GNOME42.1
Blur My Shell Ver. 35
**ON WAYLAND**
![Screenshot from 2022-05-13 14-56-03](https://user-images.githubusercontent.com/36117602/168229192-daa0dfca-9861-4769-8bcb-547ccf4d37b9.png)
![Screenshot from 2022-05-13 14-56-14](https://user-images.githubusercontent.com/36117602/168229272-8690e227-8fd4-4855-af20-30b091e1e651.png)

**Comment by CorvetteCole** [comment]
strange! this is a bug with applications blur and the shadows being considered part of the window. I'm pretty sure I fixed that in the past. I'll look at this soon
