### ISSUE TITLE
this.effect.actor.get_content() is null

### ISSUE THREAD

**Issue by Razer0123** [aunetx/blur-my-shell#249]
Hello, i am getting this error

`this.effect.actor.get_content() is null`

It happened right after i woke up my PC from sleep

How can i help debug this issue?

**Comment by aunetx** [comment]
Hello, what is the version of the extension? I though I removed this bug some time ago, maybe I forgot some part of the code.

Just after the bug occured, could you also tell me the complete logs with `journalctl /usr/bin/gnome-shell|grep blur-my-shell`?

**Comment by aunetx** [comment]
Hello, as I did not hear from it again and the code does not appear any more in blur-my-shell, I close this issue. If it is still appearing, don't hesitate to reopen it please!
