### ISSUE TITLE
Floating Dock Blur

### ISSUE THREAD

**Issue by Zany-Zachary1** [aunetx/blur-my-shell#25]
As of now, this blur takes the shape of a normal dock, and adapts itself to dash to dock's settings.  There is an extension that I particularly love to use, called Floating Dock.  However Blur My Shell doesn't like it.  I would appreciate it if you could add floating dock mode, where you can add rounded corners, and allow it to float off the bottom of the screen.

**Comment by aunetx** [comment]
I'm sorry, rounding corners is something that I really can't do, especially with the time I can spend now... Gnome has not implemented a way to give a particular shape to the blur, so the best I can do is rectangular!

Allowing it to float off the bottom of the screen could be doable, but what is it doing now? Normally, it should have the exact same height as the dock, so if this is not the case, it means that I would need to change a bunch of things so it stays compatible with vanilla dash to dock...

**Comment by aunetx** [comment]
Could you test with latest commits on the gnome-40 branch? As dash-to-dock is now floating, it may works now

**Comment by CorvetteCole** [comment]
I have a few ideas for how to shape blur I was experimenting with for #39 . It might be a possibility, just wanted to put that out there

**Comment by CorvetteCole** [comment]
rounded corners issue can be found in #8  by the way

**Comment by aunetx** [comment]
I'm closing this, as I only plan to add support for very used extensions (Dash to Dock, Dash to Panel, ...) or official gnome extensions (such as Window List), because the work would be too much for me else...

You can contact the official maintained of Floating Dock if needed, it is very easy to add blur from within its extension (but pretty hard from another extension, such as Blur my Shell). He--or you-- can contact me if you need help implementing blur in this extension, although I'm pretty sure there will be no way to get rounded blur with the current gnome implementation.

**Comment by matfantinel** [comment]
I wanna add that I was able to mimic rounded corners with Floating Dock by doing the following:

* In Blur my Shell settings, set Brightness to max, and Sigma to a low value (I kept it at 15)
* In Floating Dock settings, I set Opacity to 60%. This way it mimics a lower blur brightness.

Matched with a fitting wallpaper, it looks like the dock blur is rounded:

![image](https://user-images.githubusercontent.com/24247035/155149663-36fbb695-2a3d-41d4-97be-2d80465ad613.png)

Keep in mind that the 100% brightness might make the panel/overview blur look bad. In my case, I only enable blur for the dock, so it looks pretty good.

**Comment by mwmw1221** [comment]
> I wanna add that I was able to mimic rounded corners with Floating Dock by doing the following:
> 
> * In Blur my Shell settings, set Brightness to max, and Sigma to a low value (I kept it at 15)
> * In Floating Dock settings, I set Opacity to 60%. This way it mimics a lower blur brightness.
> 
> Matched with a fitting wallpaper, it looks like the dock blur is rounded:
> 
> ![image](https://user-images.githubusercontent.com/24247035/155149663-36fbb695-2a3d-41d4-97be-2d80465ad613.png)
> 
> Keep in mind that the 100% brightness might make the panel/overview blur look bad. In my case, I only enable blur for the dock, so it looks pretty good.

nice
