### ISSUE TITLE
Dash and Top Panel Background

### ISSUE THREAD

**Issue by andrewaclear** [aunetx/blur-my-shell#254]
I have styled the top panel as well as the dash with transparency in my gtk style. Could you please put an option to not override the gtk backgrounds for both the top panel and the dash (I think you did for the dash already)?

**Comment by andrewaclear** [comment]
The new updates you guys have been doing are amazing! Thank you! Regarding this issue, you do allow me to not override the background of the dash which is perfect because I have styled it, but can you please add this option for the panel too? I have styled the panel as well but my background always gets removed.

**Comment by aunetx** [comment]
I will do this right now, thanks for the reminder

**Comment by aunetx** [comment]
Fixed in last commit

**Comment by andrewaclear** [comment]
Blessss! Thanks dude.
