### ISSUE TITLE
Blur the panel is not working properly if the panel have border radius

### ISSUE THREAD

**Issue by jefer94** [aunetx/blur-my-shell#263]
Settings
![image](https://user-images.githubusercontent.com/3018142/170629137-343e786f-8e7b-4673-87f4-1d84ea29c871.png)

Case 1
![image](https://user-images.githubusercontent.com/3018142/170628896-9d8b4ab9-2270-45a9-8582-6671e6401321.png)

Case 2
![image](https://user-images.githubusercontent.com/3018142/170628989-4ccba666-1c60-47db-8f68-cafb45e455af.png)

Case 3
![image](https://user-images.githubusercontent.com/3018142/170629028-7cce8ee5-04b0-482e-b3fa-f8bde296ab33.png)

Check the border (it is not transparent), the sigma is necessary that should not be applied in the borders

**Comment by tamaki03** [comment]
same with me , but it gets worse when I move the dock to the left
![image](https://user-images.githubusercontent.com/90030004/170662743-dd109618-a20d-43af-975b-ad9b3c6a4db4.png)

**Comment by aunetx** [comment]
Hello and thank you for the report, unfortunately this is an already known limitation: see #8 and #185...

I very recently tried to address this recently in #265, but unfortunately this does not work when using with the blur effect itself.

I will put more infos on this PR, and closing this as a dup :)

**Comment by jefer94** [comment]
Maybe open a issue in Gnome should be util in this situation, but i don't know where is the main repository, the team of Gnome is traditional and they not have the repo in Github
