### ISSUE TITLE
Not working after Manjaro Gnome 42.1 wayland upgrade

### ISSUE THREAD

**Issue by aloksharma2** [aunetx/blur-my-shell#268]
Hi,

Blur my shell not working with Manjaro gnome 42.1 wayland update.
Previously it was working perfectly fine.
Here's the video of the same:
https://user-images.githubusercontent.com/54803227/170814880-4f45d42e-745c-47a7-afd7-827cd04ccc3b.mp4

**Comment by ArchitektApx** [comment]
At least on the testing branch everything seems to work properly:

https://user-images.githubusercontent.com/21159658/170816522-8917c139-201f-4287-904e-96bc0c455fcd.mp4

**Comment by aunetx** [comment]
Could you tell me what are the preferences you've got for the extension? It looks like it might be working, but just with a quite dark colour...

**Comment by aloksharma2** [comment]
> Could you tell me what are the preferences you've got for the extension? It looks like it might be working, but just with a quite dark colour...

Please find the attached screenshot of the same.


![Screenshot from 2022-05-30 09-14-12](https://user-images.githubusercontent.com/54803227/170913663-48f83655-d964-4f5d-b6a6-902e9b33c044.png)

![Screenshot from 2022-05-30 09-14-26](https://user-images.githubusercontent.com/54803227/170913675-314095a8-0ddd-43a4-b96a-3049fe3363b9.png)

![Screenshot from 2022-05-30 09-14-35](https://user-images.githubusercontent.com/54803227/170913691-7bc79c60-2324-4ee4-80e1-9bd8f05a3520.png)

![Screenshot from 2022-05-30 09-14-43](https://user-images.githubusercontent.com/54803227/170913701-1c596cdd-cb62-4fd5-886c-a4c68b27ceae.png)

![Screenshot from 2022-05-30 09-14-51](https://user-images.githubusercontent.com/54803227/170913721-9e2c672c-8a1c-44e2-b086-35c9780e961b.png)

![Screenshot from 2022-05-30 09-14-59](https://user-images.githubusercontent.com/54803227/170913749-938feb08-4886-4ccb-8b12-5498bd057fd9.png)

Let me know what i can do to resolve this. 
Appreciate your help in this, Thanks @aunetx

**Comment by aunetx** [comment]
Could you try to set the brightness (first screenshot) to a higher level?

**Comment by aloksharma2** [comment]
> 

HI

**Comment by aloksharma2** [comment]
> Could you try to set the brightness (first screenshot) to a higher level?

**Yes, It was the issue with the brightness** and now working fine. But if you see on DASH, there are black edges which is not looking good. I can disable it using "DASH TO DOCK BLUR"  and DASH will go into default not bluring

![Screenshot from 2022-05-30 13-59-25](https://user-images.githubusercontent.com/54803227/170952470-f0e77f47-ddcb-4687-ae1b-0207e189aa50.png)

**Comment by aunetx** [comment]
Cool, thanks!

For the corners, see #8... I can't blur this properly for the moment, sadly :/

**Comment by aloksharma2** [comment]
> Cool, thanks!
> 
> For the corners, see #8... I can't blur this properly for the moment, sadly :/

No worries...I will keep using it without that until anyone got a good idea to fix it. Thanks for your help buddy @aunetx and keep it up
