### ISSUE TITLE
Overview blur for gnome 40 doesn't work on second monitor

### ISSUE THREAD

**Issue by GabMus** [aunetx/blur-my-shell#28]
It's easier to see in the screenshot, the blur effect only works for one monitor, plus the part of the wallpaper being blurred in the primary one is the one pertaining to the secondary monitor.

![Screenshot from 2021-04-20 07-54-19](https://user-images.githubusercontent.com/1358527/115344591-e2b72680-a1ad-11eb-9caa-2d0cac893893.png)

**Comment by rnd-ash** [comment]
Same can be viewed on other multi-monitor setups

![image](https://user-images.githubusercontent.com/14551965/115348751-f319d200-a1aa-11eb-8722-e2b9b1d656c9.png)

**Comment by aunetx** [comment]
Thanks for trying the extension :)

I will update this very soon (probably next commit), but I don't know how to choose the right wallpaper!
@GabMus do you use an extension to have a different wallpaper on each monitor?

**Comment by aunetx** [comment]
I think I get the right wallpapers now, but can't find a way to get a second monitor working in virtualbox, so no way to do the required tests... Looks like I will need to install gnome 40 directly on my computer! :p

**Comment by aunetx** [comment]
Done! ;)

**Comment by GabMus** [comment]
> Thanks for trying the extension :)
> 
> I will update this very soon (probably next commit), but I don't know how to choose the right wallpaper!
> @GabMus do you use an extension to have a different wallpaper on each monitor?

nope, an app I made, it's called hydrapaper, you can find it on flathub. by the way thanks for the extension, will test the latest changes and see if they work!
