### ISSUE TITLE
No JS module 'workspaceAnimation' found in search path

### ISSUE THREAD

**Issue by FledPaul** [aunetx/blur-my-shell#287]
### Description
When I install **blur-my-shell** via Git clone and Cmake, then activate it I get the following error: `No JS module 'workspaceAnimation' found in search path`.

I'm using ZorinOS 16.1.

# Screenshots
![Image](https://i.postimg.cc/Pr5xCJnW/Screenshot-from-2022-06-19-22-14-10.png)

**Comment by aunetx** [comment]
Hello, sorry for the delay, could you post the error found with `sudo journalctl /usr/bin/gnome-shell` when the error occurs?

I don't know zorin os very well, but this may be caused by a difference between zorin and vanilla gnome, in which case I'm not sure how to handle it

**Comment by FledPaul** [comment]
Sorry for my delay.

Unfortunately I am no longer a Linux user, so I can not test if the error still occurs.

I will try it again (when I have the option to) and then open a new issue.
