### ISSUE TITLE
The "Disable when a window is near" option is enabled, but the panel is still blurry when switching workspaces from the overview.

### ISSUE THREAD

**Issue by JBlinkLU** [aunetx/blur-my-shell#289]
Hi there!
There's a setting in the extension called "Disable when a window is near", inside the panel section, which disables the panel blur when a window is maximized or touches the panel.

That option works except on one particular situation:
When you are in a workspace with no windows (or with windows that are NOT touching the panel) > open the activities overview > switch to a workspace with a maximized window or with a window touching the panel.

The panel will stay blurry, even though it is not supposed to be like that.
Here's a video showing an example of what I'm trying to say:
[Kooha-07-01-2022-23-35-10.webm](https://user-images.githubusercontent.com/29048285/176971787-bc2b1d85-3bb5-4c07-9a0b-02ceaabd5fab.webm)

**Comment by aunetx** [comment]
Just fixed this in last commit, will push to extensions.gnome.org soon :)
