### ISSUE TITLE
Application blur not working

### ISSUE THREAD

**Issue by bdreaves04** [aunetx/blur-my-shell#292]
I have alacritty set in my white list but the blur effect is not applied
![image](https://user-images.githubusercontent.com/63303767/178056068-8119c147-d0c0-426c-b866-a4253f38674c.png)

![image](https://user-images.githubusercontent.com/63303767/178056019-9915a85a-f0bf-42f3-b129-80ea8a51cde7.png)

doesn't work for any other application either
![image](https://user-images.githubusercontent.com/63303767/178056390-8de55007-5671-4228-b19f-4ad5c336ba1c.png)

**Comment by ThomasLobker** [comment]
Same here, but I would like to add that I can see some blur background behind the window. The window itself is just not transparent so you won't really see the blur. Also, you can see straight corners behind the window's rounded corners.

**Comment by aunetx** [comment]
You can try with an application that has transparency, for example gnome-terminal.

I will try to add the transparency to blurred apps soon.

**Comment by dsadsadasdasdas** [comment]
I have the same issue as above. It's not working for gnome-terminal either.

**Comment by bertin0** [comment]
You need to set the background as transparent

**Comment by dsadsadasdasdas** [comment]
Yeah, after downloading gnome-terminal-transparency from the AUR it works, but only for the terminal ofc.

**Comment by TanawatJukmongkol** [comment]
What I found out is that you have to set a low sigma value like 1 - 6, since the blur is too strong. Also make sure the class name is correct. Open up the application you want to add the blur to, then open up Gnome's looking glass (press Alt + F2), and then type `lg` into the prompt, then open the `windows` tab and find the property `wmclass` of the app you want to add. Make sure all the lower and upper case all match.

**Comment by dsadsadasdasdas** [comment]
I tried this but the class name is the same as before. The blur _is_  working but only for apps with transparency. I can see it behind apps sometimes, but there is no transparency so guess i'll have to wait for it to get added :)

![bæ](https://user-images.githubusercontent.com/46232819/185928469-65475bd4-e25e-4629-b886-e1ae58fc2c23.png)

**Comment by aunetx** [comment]
Hello, this have been fixed with last release (soon on extensions.gnome.org).

I added the ability to make windows transparent, so that you can effectively see the blur behind them.
