### ISSUE TITLE
Dash to Panel is not blurred when using the original panel too

### ISSUE THREAD

**Issue by SnoutBug** [aunetx/blur-my-shell#295]
When using Dash to Panel v50 and Blur my Shell v39 on Gnome 42 the blur is only applied to the top bar not the panel itself 
![image](https://user-images.githubusercontent.com/71790678/179006238-768c52d0-00c6-41ec-abfb-6ca2429510d9.png)

DTP Settings:
![image](https://user-images.githubusercontent.com/71790678/179007432-4714a36c-8445-44e2-9f92-0e102b403ffe.png)

BMS Settings:
![image](https://user-images.githubusercontent.com/71790678/179007982-c5f2854f-555c-483e-a73a-4a378a061ad0.png)
Does not work with either static blur turned on or off

If necessary I will attach some logs if you tell me where I can find them :D

**Comment by aunetx** [comment]
Hello, this is due to the option "keep the original panel" in "personalisation" in Dasht to Panel preferences. BmS does not support multiple panels for the moment, so it will blur only the original one!

You can either disable this option, or wait until #171 is merged (I still have not worked on this, sorry) :)

**Comment by SnoutBug** [comment]
Ah I see, thanks for the heads up

**Comment by aunetx** [comment]
@SnoutBug if you want, you can try #306, tailor-made for you :)

**Comment by SnoutBug** [comment]
Awesome, works like a charm on my ThinkPad! I will try this on my main machine later and report any issues should there be any.

**Comment by aunetx** [comment]
Thank you very much! You can also try it with multiple monitors, but for the moment this should not work well
