### ISSUE TITLE
Setting application blur _MUTTER_HINTS=blur-provider.... ignored?

### ISSUE THREAD

**Issue by christianparpart** [aunetx/blur-my-shell#300]
Hey blur-my-shell developers!

I am developing an application that already does support blur-behind for KDE (kwin) right out of the box without any user-modification. Now I would like to add the same for GNOME-shell, and learned that blur-my-shell seems to be the go-to-way for doing that.
I did read that an application can request blur-behind proactively by setting the X11 property `_MUTTER_HINTS=blur-provider=sigma:60,brightness:0.9` (example taken out of your README). That however does not seem to work under gnome-shell with your extension installed.

It does however work when adding the `WM_CLASS` to the settings view, but that's a step I'd prefer the user not to require to, so requesting blur-behind effect on the app's window from the app itself would be awesome.

I was reading that the support is experimental and breaks, but I would like to know if I'm doing it at least right or not, if not testable yet. So far it's hard to tell if it's my problem that it is not yet working or not. 

If you have a look here:

https://github.com/contour-terminal/contour/pull/772/files#diff-a57b3460b3555f9a2c934432ec2f051f3115c6c74658dae37aa67b5311f0d27bR40

you should see also how I'm doing it with respect to KDE's KWin (5 lines above), and how I'd like to get that enabled for GNOME shell via your extension. But that part is not working, not sure if it's my fault yet, sadly.

What do you think?

p.s.: I'm not a GNOME user, so please bare with me. :)

**Comment by aunetx** [comment]
Hello, thank you for opening this issue, I'm sorry I'm not very available currently but I will see what does not work ASAP.

You seem to use this correctly so it's not your fault, definitely a bug on my side!

**Comment by christianparpart** [comment]
> Hello, thank you for opening this issue, I'm sorry I'm not very available currently but I will see what does not work ASAP.
> 
> You seem to use this correctly so it's not your fault, definitely a bug on my side!

Great to hear (just objectively!). So I can actually merge this PR with the reference to that tracker ticket here. And you should have one (or one more) app that you could use for testing your code changes. Only one will know. ;-)

Thanks for the great work,
Christian.

**Comment by christianparpart** [comment]
Sorry for the disturbance @aunetx . I fixed the problem on my end, the root cause was that I was using some Qt function `QWindow.setProperty(name, value)`  believing that this has anything to do with native window properties. But it doesn't. I've now fixed that. It seems to work on GNOME shell using your extension now. Many thanks for the great work. ;)
