### ISSUE TITLE
"Disable when window is near" for Panel not working

### ISSUE THREAD

**Issue by weiameili** [aunetx/blur-my-shell#301]
Hi, I have a window in the background which is maximised and an active window that is not, at this point the panel is black as expected, but when I close the active window from the overview and choose the maximised window, the blur is no longer available.

Video of an example:

https://user-images.githubusercontent.com/74808990/183282241-7e3f4506-040c-4fb4-b155-eaf5604814e8.mp4

**Comment by aunetx** [comment]
Thank you for opening this issue, unfortunately I'm having a hard time debugging it... I will see what I can do in the future, this needs to be improved a lot anyway

**Comment by aunetx** [comment]
Is it working now @weiameili? It looks like I can't reproduce this issue anymore

**Comment by weiameili** [comment]
Nope, still having the same issue unfortunately.

To reproduce:
- Open chrome as a maximised window
- open terminal
- go to overview
    - close terminal
    - click on chrome's window

**Comment by aunetx** [comment]
Could you tried with the latest git commit by installing from there? I though it was definitely done :/

**Comment by weiameili** [comment]
Hi, sorry I couldn't look into this earlier since I was quite busy. 

Anyways just noticed this issue seems to be solved as of version 43. Thanks for all the work :)
