### ISSUE TITLE
Settings window getting blank when interacting with dropdowns

### ISSUE THREAD

**Issue by danuhr** [aunetx/blur-my-shell#309]
The settings window gets completely blank when I am about to change the Hack level. Same happens under the Overview tab when interacting with the Overview components style dropdown.
[Kooha-2022-08-20-15-17-13.webm](https://user-images.githubusercontent.com/12256895/185748079-f8a4c24f-0f30-4689-bcb5-0b0b7d1ccb0c.webm)
.

**Comment by aunetx** [comment]
Hehe, that's #285 coming back :)

I can't do much about it tbh, but to fix it for the preferences, you can simply remove `org.gnome.Shell.Extensions` from the blurred applications whitelist (or add it to the blacklist if you have enabled all applications to be blurred)

**Comment by aunetx** [comment]
(closing this as duplicate)
