### ISSUE TITLE
Blur my shell not working

### ISSUE THREAD

**Issue by tamaki03** [aunetx/blur-my-shell#316]
![image](https://user-images.githubusercontent.com/90030004/185941476-5c0c7604-0fb6-429a-bade-902c3b949419.png)
****
I not really sure why it happened , maybe after lock screen  ?
Gnome 42.2

**Comment by kleinHeiti** [comment]
It's the same for me. At the first boot everything is fine - after logging off and on again the error message from above appears.

**Comment by Coeur-Noir** [comment]
No locking screen here, but the error appears after a while.

Relaunch the session seems ok, but some moments later, error again.

Ubuntu 22.04 on Xorg though.

**Comment by eeeeeio** [comment]
same

**Comment by tomas-tavella** [comment]
I'm having the same issue on Fedora 36 and GNOME 42.4. It breaks when I unlock the screen, though it also breaks by itself after a while.

**Comment by sekurilabs** [comment]
Confirming on Ubuntu 22.04.1 (Xorg session) with this error:
```
JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.service is undefined
disable@/home/<username>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/components/applications.js:442:9
disable@/home/<username>/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:117:33
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:123:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:537:45
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:537:24
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:663:14
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:203:14
pushMode@resource:///org/gnome/shell/ui/sessionMode.js:164:14
activate@resource:///org/gnome/shell/ui/screenShield.js:652:34
_onLongLightbox@resource:///org/gnome/shell/ui/screenShield.js:373:18
onComplete@resource:///org/gnome/shell/ui/lightbox.js:198:18
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:153:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:240:64
```

**Comment by oveeauki** [comment]
Same with me. fix please!

**Comment by qwertychouskie** [comment]
Look like a fix was merged (https://github.com/aunetx/blur-my-shell/pull/314) but there hasn't been a new release tagged that includes the fix yet.

**Comment by aunetx** [comment]
I just uploaded the new version to extensions.gnome.org, pending approval.

Sorry for the delay before uploading, I did not have my pc with me and was planning to go off for a couple of days :/

**Comment by aunetx** [comment]
Finally released :)
