### ISSUE TITLE
Blur My Shell got deactivated after logging out and logging in again.

### ISSUE THREAD

**Issue by kienmatu** [aunetx/blur-my-shell#317]
Blur My Shell got deactivated after logging out and logging in again.
After logging in again, I have to reload the shell by ALT + F2: then enter r.

My system: 
- Ubuntu 22.04LTS
- GNOME 42.2

**Comment by kleinHeiti** [comment]
see #316

**Comment by oveeauki** [comment]
Same for me! fix please

**Comment by aunetx** [comment]
Fixed
