### ISSUE TITLE
applications blur all disable toggle not functional

### ISSUE THREAD

**Issue by CorvetteCole** [aunetx/blur-my-shell#318]
Not sure how easily reproduced this is, will check later. On my laptop, applications blur was blurring behind everything even with the toggle for this set to off. I turned off applications blur entirely to fix this for now.

Just putting this here for now to make you aware in case this actually is an issue

**Comment by aunetx** [comment]
Thanks, when you can, could you try it again? I'm not able to reproduce it in any way

**Comment by CorvetteCole** [comment]
very busy, will get to it this week. might not be a real problem, we will see

**Comment by CorvetteCole** [comment]
cannot reproduce. will investigate further later but will close for now
