### ISSUE TITLE
blur on alacritty sometimes ugly

### ISSUE THREAD

**Issue by ericleman** [aunetx/blur-my-shell#319]
I configured Blur my shell to blur Alacritty.
Alacritty is blurred.
However, when I move another window in front of Alacritty, it gets messy until I focus again on Alacritty.
I am on X11.

https://user-images.githubusercontent.com/26767717/186394523-4b451991-a5b9-493c-902e-5be4250d405a.mp4

**Comment by aunetx** [comment]
What is your "hack level", in the general tab? When selecting "default" or especially "high quality" and then restarting the extension, it should look better.

**Comment by ericleman** [comment]
Thank you Aurélien.
Whatever the hack level I put, it creates artefacts anyway.
It seems related to the issue you openen on gitlab: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2857
So not sure it can be fixed for now.

**Comment by aunetx** [comment]
Hello again, this is fixed now if you use the "No artefact" option for hack level with the last version :)

This may deteriorate the performances of gnome shell, but at least the blur effect is entirely fixed with this
