### ISSUE TITLE
his.background_parent.get_parent() is null

### ISSUE THREAD

**Issue by Dziban-dev** [aunetx/blur-my-shell#32]
It worked flawlessly in gnome40 until a few minutes ago, Fedora34 came up with a system update, and now blur-my-shell is disabled **this.background_parent.get_parent() is null**

**Comment by Dziban-dev** [comment]
I'm closing this issue because logging out and logging back in fixes the issue

**Comment by aunetx** [comment]
Glad it worked! Hope you like it ;)
