### ISSUE TITLE
Dock panel is fluctuating.

### ISSUE THREAD

**Issue by iamkranthi** [aunetx/blur-my-shell#321]
when opening any app in dock panel. The complete dock panel is fluctuating Initially I thought it was a bug from fedora but when I turned off blur my shell dock panel worked fine. So the problem is with blur my shell extension. please fix the issue.

**Comment by aunetx** [comment]
Hello, could you try to post a screencast? I'm having a hard time understanding exactly

**Comment by iamkranthi** [comment]
Basically when I try to open an application on the dock panel it flickers. Initially, I thought it was a bur my shell extension bug later I figured out it was my GPU driver issue. I solved this issue. Now It's working fine.

![Screenshot from 2022-08-28 14-56-59](https://user-images.githubusercontent.com/75005151/187067278-4241d254-ea0e-42f0-92e1-d3f73d2b7fb7.png)

**Comment by aunetx** [comment]
Ok thanks a lot for the follow-up!
