### ISSUE TITLE
Blur in Overview is only applied to one monitor

### ISSUE THREAD

**Issue by CorvetteCole** [aunetx/blur-my-shell#33]
As you can see in the below screenshot, blur in the overview is applied properly to the primary monitor, but the secondary monitor retains the default gray background. Btw, I also was one of the first to build a blurring extension in Gnome, so I may come help out with the project if I have time :)

![Screenshot-2021-04-20,16-14-53](https://user-images.githubusercontent.com/19213965/115459859-8972e580-a1f5-11eb-928a-003268764312.png)

**Comment by aunetx** [comment]
Thanks a lot!

Have you tried the very last commits? I just fixed #28, but maybe my implementation was not good enough!
And are your two monitors the same dimensions? Mine aren't, so that's maybe the problem (as it's working great for me)

And thanks for blur-provider, that's really a great extension ;)

**Comment by CorvetteCole** [comment]
@aunetx oh well let me eat my own damn words I should've pulled the latest commit! By the way, you could upload this gnome 40 version to extension.gnome.org whenever you want. The site will continue to serve the newest compatible version of the extension to clients on 3.36, 3.38, etc. I am a reviewer there so just tag me if you get stuck in review :)

**Comment by aunetx** [comment]
@CorvetteCole don't worry I pushed it very recently!

And that's really great for the extensions website!
I though to update it when I resolved #31, but after all maybe there's no need to wait!
So I just removed the option temporary, and will upload to extensions.gnome.org right now :)

**Comment by aunetx** [comment]
That's uploaded :)

**Comment by CorvetteCole** [comment]
Approved it!

**Comment by aunetx** [comment]
Thanks a lot!!!
