### ISSUE TITLE
Application background blur interrupt rounded-window-corners cornerradius

### ISSUE THREAD

**Issue by taiwbi** [aunetx/blur-my-shell#331]
I use [rounded-window-corners](https://github.com/yilozt/rounded-window-corners) extension to round my windows corners but when I add background blur to an application like nautilus, It interrupts round corners:
This is an screenshot when I don't use background blur on nautilus: 
![Screenshot from 2022-08-28 17-09-22](https://user-images.githubusercontent.com/85298827/187074610-b8896696-dfb5-4966-b18a-99eb34305496.png)

This is an screen shot when I use background blur on nautilus:
![Screenshot from 2022-08-28 17-10-35](https://user-images.githubusercontent.com/85298827/187074626-7b0307f4-74f7-45e7-9c84-fec1069f9884.png)

When I add this CSS code in gnome inspect application, my borders look like this:
```
window {
    border-radius: 10px;
}
```
![Screenshot from 2022-08-28 17-14-59](https://user-images.githubusercontent.com/85298827/187074809-ef251cf6-a493-4f5d-92bd-620c275ad0de.png)
also it only effect gtk applications not all applications.

**Comment by CorvetteCole** [comment]
unfortunately Gnome's blur does not support rounded corners (only rectangular shapes). Tracking this in #185, #8. Closing as duplicate

**Comment by aunetx** [comment]
I don't know if this is the same issue, it is more related to the fact that the blur effect either interrupts or is interrupted by other effects... I could investigate into this later, because a good this would be at least to have the rounded corners effect to work for the window, even if the blur behind is not rounded
