### ISSUE TITLE
Application Blur Issue

### ISSUE THREAD

**Issue by EmrecanKaracayir** [aunetx/blur-my-shell#335]
When the "Enable all by default" switch is enabled in the "Application" section, sometimes the blur layer rendered on top of the windows. Usually happens when clicked to "3 dot menus". Also Firefox is always unusable.

SYSTEM INFO: 
![image](https://user-images.githubusercontent.com/84916904/188242770-e22b6db1-0cb2-4596-b14b-14950d63387c.jpeg)

[Video Report](https://youtu.be/6ozF2ogkiqQ)

**Comment by aunetx** [comment]
Hello, to be honest I don't know why nothing seems to work now, for me it worked well two weeks ago, and now both firefox and vscode are not transparent, and their blur it not showing up either.

It seems like display unredirection is causing trouble, along with monitor scaling, along with wayland differing from xorg when it comes to handling all these things, along with some windows randomly choosing to change their widgets' ordering...

I will try to fix what I can, but to be honest I don't have much time for myself :/

**Comment by CorruptedPlazma** [comment]
CR on the terminal problem, I'm using Wayland and it appears the built-in Gnome screen recorder doesn't work for me.

**Comment by bubi-luka** [comment]
Have the same problem. It appears as the opacity&blur are applied to display the content of the window, not for window to be transparent and the background is blurred. It worked for a long time, now it is unusable. @aunetx: I hope you find the time to diagnose the issue and be able to fix it.
