### ISSUE TITLE
Add support for gnome 43

### ISSUE THREAD

**Issue by git-Hmmm** [aunetx/blur-my-shell#339]
title says it clear!

**Comment by aunetx** [comment]
Hello, I will do it this week end if there is nothing to fix, else someone else will need to provide a patch as I have absolutely no time for myself

**Comment by git-Hmmm** [comment]
> @aunetx Hello, I will do it this week end if there is nothing to fix, else someone else will need to provide a patch as I have absolutely no time for myself Thanks for the remainder :)

No problem :+1:, your reply was enough for my satisfaction.

**Comment by tinmarr** [comment]
For those who are impatient, it seems that updating the shell version in `/metadata.json` to 43 seems to do the trick. No apparent bugs as far as I can see (extremely light testing)

**Comment by carlwgeorge** [comment]
Another option besides editing the metadata.json file would be to toggle the dconf key `/org/gnome/shell/disable-extension-version-validation` to true.  This tells GNOME to try to load extensions regardless of the versions they claim to support.

**Comment by ipanamski** [comment]
I've been using it in **Gnome 43** for two days now. No problems so far.

**Comment by thgr4j** [comment]
I also changed `/metadata.json` and been using it for a few days, no issues.

**Comment by atarixle** [comment]
sorry to say that but nothing works on Fedora 37 Beta / GNOME 43. I downloaded the release, I installed as recommended in the README.md, but there is absolutely no change.

**Comment by thgr4j** [comment]
> sorry to say that but nothing works on Fedora 37 Beta / GNOME 43. I downloaded the release, I installed as recommended in the README.md, but there is absolutely no change.

As you can see from the README, the current release doens't support GNOME 43 natively. You have to install the extension, then update the shell version in `/metadata.json` to support GNOME 43 (just change the "42" to "43" e.g.).

**Comment by carlwgeorge** [comment]
> sorry to say that but nothing works on Fedora 37 Beta / GNOME 43. I downloaded the release, I installed as recommended in the README.md, but there is absolutely no change.

I'm using the extension right now on Fedora 37 and GNOME 43.0, and it works great once you either modify metadata.json or set the dconf key to disable extension version validation.

**Comment by atarixle** [comment]
I see.
I was thinking that "Release 43" was made for GNOME Shell 43.
Turning off version check did the trick. Thanks!

**Comment by carlwgeorge** [comment]
Yeah that's an unfortunate numbering that confused me at first too.  Hopefully those could be aligned for GNOME 44 going forward.

**Comment by aunetx** [comment]
Sorry for the big delay, I really have not found time to release it... If I have some this afternoon will try today, but I'm not sure I can :/

By the way, there is no possibility that gnome shell and blur my Shell will have the same version release: extensions are required to have integer numbers for release (v42, v43, ...) and sadly, I won't be able to "only" make one release for every gnome version, as this would mean a lot of bugs not being fixed

For example, between gnome 3.36 and 42 (5 gnome versions), I've made... 43 releases :)

**Comment by aunetx** [comment]
Hello, done, pushing to eog
