### ISSUE TITLE
"Disable when window is near" for Panel doesn't work with Desktop Icons NG (DING)

### ISSUE THREAD

**Issue by IvoryJam** [aunetx/blur-my-shell#341]
It just stays black, I assume it's because Blur My Shell is recognizing DING as a window

![image](https://user-images.githubusercontent.com/35709713/189206004-0a6fcf34-9c6c-43e7-9e2a-203d21570fc8.png)

**Comment by aunetx** [comment]
Thank you, fixed this

**Comment by IvoryJam** [comment]
Looks like it affects Wayland too
