### ISSUE TITLE
A lovecraftian horror whenever I open a folder in the app grid

### ISSUE THREAD

**Issue by MolassesLover** [aunetx/blur-my-shell#342]
# The Issue

I really don't know how to describe this one.

https://user-images.githubusercontent.com/60114762/189480228-e9071f7a-ee2a-41ae-bb34-42768568737a.mp4

# About

This is on Arch with GNOME 42. It's worth mentioning I also have this issue on Fedora 36.
My extensions are:
- [Alphabetical App Grid](https://github.com/stuarthayhurst/alphabetical-grid-extension)
- [Freon](https://github.com/Veske/gnome-shell-extension-freon)

I'm using:
- [Nordic GTK](https://github.com/EliverLara/Nordic)
- [Nordic Libadwaita](https://github.com/odziom91/libadwaita-themes)
- [Nordzy](https://github.com/alvatip/Nordzy-icon)
- [Nordzy Cursors](https://github.com/alvatip/Nordzy-cursors)

**Comment by aunetx** [comment]
Hello, what are the preferences you are using for the Hack level (in the general tab of the preferences)?

You might want to set it to "default" at least, but tell me if that does not work. If you want, you can also set "no artefacts", although this may increase power consumption and should not be necessary.

**Comment by MolassesLover** [comment]
Oh, I see! I had set it to "high performance" in the preferences. 

Raising the quality fixed it. Thank you!
