### ISSUE TITLE
Crash when opening transparent window

### ISSUE THREAD

**Issue by Araly** [aunetx/blur-my-shell#350]
Hey,

I'm running Gnome 42.4, with blur-my-shell 43. I also have rounded mutter if that's relevant (which rounds the corners of apps and blurs the transparent windows).
Whenever blur-my-shell is activated, and I start an app with transparency (I tested mostly kitty and guake), the entire gnome session breaks and crashes. I get sent back to the gdm greeter.

Let me know if there are logs I can give you.

**Comment by Giggigx** [comment]
Same thing happening to me, I tried to see if there were any errors on journalctl and there are lots of javascript errors when trying to open an application blurred by mutter-rounded.
I don't know if that's useful for this issue or not but i'm gonna paste it here anyways, sorry for the mega block of code
`Sep 26 10:00:52 giggig-laptop systemd[1381]: Started Application launched by gnome-shell.
Sep 26 10:01:24 giggig-laptop firefox.desktop[2682]: Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 4: Error: Invalid work id 4
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 5: Error: Invalid work id 5
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 6: Error: Invalid work id 6
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 7: Error: Invalid work id 7
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 8: Error: Invalid work id 8
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 9: Error: Invalid work id 9
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 10: Error: Invalid work id 10
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 11: Error: Invalid work id 11
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 12: Error: Invalid work id 12
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 13: Error: Invalid work id 13
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 14: Error: Invalid work id 14
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 15: Error: Invalid work id 15
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 16: Error: Invalid work id 16
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 17: Error: Invalid work id 17
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 18: Error: Invalid work id 18
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 19: Error: Invalid work id 19
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 20: Error: Invalid work id 20
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 21: Error: Invalid work id 21
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 22: Error: Invalid work id 22
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 23: Error: Invalid work id 23
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 24: Error: Invalid work id 24
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 25: Error: Invalid work id 25
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 26: Error: Invalid work id 26
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 27: Error: Invalid work id 27
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 28: Error: Invalid work id 28
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 29: Error: Invalid work id 29
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 30: Error: Invalid work id 30
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 31: Error: Invalid work id 31
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 32: Error: Invalid work id 32
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
Sep 26 10:01:24 giggig-laptop gnome-shell[1536]: JS ERROR: Invalid work id 33: Error: Invalid work id 33
                                                 queueDeferredWork@resource:///org/gnome/shell/ui/main.js:854:18
                                                 _queueRedisplay@resource:///org/gnome/shell/ui/dash.js:477:14
`

**Comment by Araly** [comment]
https://github.com/yilozt/mutter-rounded is the culprit here, it's not maintained anymore, the devs have moved on to https://github.com/yilozt/rounded-window-corners.

So, remove mutter-rounded, (add back in mutter), install the rounded windows extension instead, enable blur-my-shell again, and everything works anymore except for blur in terminals. Does anyone know how to blur terminals now ?
