### ISSUE TITLE
How to have blur my shell effect on second monitor ?

### ISSUE THREAD

**Issue by mindoodoo** [aunetx/blur-my-shell#356]
Hi,

I unfortunately couldn't find anything when googling around and looking through the options. Is there any way to have the effect applied on the second monitor ?

Please excuse me if this has already been asked.

**Comment by CCaroV** [comment]
It seems this is a bug rather than a enhancement option. The overview blur is only working in one monitor, and from time to time it works on both (Gnome 43). Never saw that happening on Gnome 42.

**Comment by CCaroV** [comment]
It seems this is a known issue using multi monitors on Wayland (#94 ).

**Comment by aunetx** [comment]
That's a bug, as it was mentioned, described in #94 :(
Unfortunately I can't fix it myself...

**Comment by mindoodoo** [comment]
This was a while back, I can report that running the latest version of gnome on wayland I do not have this bug anymore.

Thanks for the great addon !
