### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by carlwgeorge** [aunetx/blur-my-shell#364]
The [README.md file](https://github.com/aunetx/blur-my-shell/blob/master/README.md) file says that the software is licensed under the GPL version 2 or later.  The [LICENSE file](https://github.com/aunetx/blur-my-shell/blob/master/LICENSE) is the GPL version 3.  What is the intended license for this software?

- [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html)
- [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html)
- [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)

**Comment by aunetx** [comment]
Sorry for the delay, to be honest I did not pay attention to it, I guess it should be GPL version 3 or later then (hope that's to problematic)

**Comment by aunetx** [comment]
I fix this in the readme

**Comment by carlwgeorge** [comment]
Thanks!
