### ISSUE TITLE
Can't open settings menu

### ISSUE THREAD

**Issue by nicki419** [aunetx/blur-my-shell#365]

**Comment by nicki419** [comment]
Forgot to add description. Getting the following error code on any version:

`Error: Argument object may not be null

Stack trace:
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
  connect_to@/home/nick/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/preferences/customize_row.js:72:11
  General@/home/nick/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/preferences/general.js:35:43
  fillPreferencesWindow@/home/nick/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:35:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by aunetx** [comment]
Hello, is this still happening? I don't understand what may cause that to happen :/

**Comment by nicki419** [comment]
It's not happening anymore. I most likely had messed up files somewhere,
and have hence switched to a new distro where things work perfectly.

**Comment by aunetx** [comment]
Thanks!
