### ISSUE TITLE
add option to improve contrast on top bar

### ISSUE THREAD

**Issue by allaeddineomc** [aunetx/blur-my-shell#366]
in situations where the user chooses a high brightness setting and a bright wallpaper the top bar text becomes unreadable , a good solution will be adding an option to improve contrast by using this segmented look 
![Screenshot from 2022-10-21 17-17-27](https://user-images.githubusercontent.com/57415185/197243154-5dcb616e-d474-4c36-b411-2e14e5b5ff12.png)

**Comment by allaeddineomc** [comment]
here is the code for this style sheet


.workspace-background{
  border: 1px solid rgba(255, 255, 255, 0.03);
}

#panel{
  background-color: transparent;
  margin: 2px;
  height: 30px;
}

.panel-button,
.clock,
.clock-display StIcon{
color: #ffffff;
  border-radius: 14px;
  border: 3px solid transparent;
  background-color: #000000;
  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.03);
}
.clock-display StIcon{
  padding: 8px;
  margin: 0;
}
.panel-button:hover,
.panel-button:hover .clock{
color: #ffffff;
  background-color: #000000;
}
.panel-button:active,
.panel-button:overview, /* activites */
.panel-button:active .clock{
  background-color: #000000;
  color: #ffffff;
}
/* clock fix */
.clock-display{
  background-color: transparent !important;
  box-shadow: none !important;
  border: none !important;
}
.clock{
  margin: 0 !important;
}

**Comment by aunetx** [comment]
Hello, and thank you very much! I will test it right now

**Comment by aunetx** [comment]
I just added this :)
