### ISSUE TITLE
Bug on white list to blur

### ISSUE THREAD

**Issue by Neo-29** [aunetx/blur-my-shell#368]
Hello.
Could not pick window make sure that the extension is enabled.
So...I can't choose.
If I activate all it works.. But as stated... Not recommended.
I'm at a dead end.

**Comment by Neo-29** [comment]
@aunetx ?

**Comment by bubi-luka** [comment]
Hi!

I have the same problem. The extension worked for some time, but then I noticed I could not select windows to whitelist (or blacklist) any more. The red border appears around the selected application window, but after I click it, it is not selected (the class name is not entered into the whitelist field). I can still enter it manually.

|Application|Version|
|---|---|
|Blur My Shell|44.0|
|Gnome Shell| 43.2|
|Mutter|43.2|
|Wayland|1.21.0-1|
|Fedora|37|

**Comment by westcap** [comment]
Check out my temporary solution:
https://github.com/aunetx/blur-my-shell/issues/424#issuecomment-1532641474

**Comment by aunetx** [comment]
Hello, I just fixed this in last commit, so I close this. If in next release (or when you install the extension from github) this issue is still appearing, could you please re-open it?
