### ISSUE TITLE
Gnome 40 returns error "actor is null" and doesn't work at all

### ISSUE THREAD

**Issue by TimestaticYT** [aunetx/blur-my-shell#37]
Im using the Github version for Gnome 40. Already tested the version on extensions.gnome.org and it had the same Error. Settings menu works but it doesn't apply the background blur. Already logged out and in again and still didn't work

**Comment by aunetx** [comment]
Could you give me the output of `journalctl /usr/bin/gnome-shell|grep "Blur my Shell"` and `journalctl /usr/bin/gnome-shell|grep "blur-my-shell"` ?

And by the way, do you use other extensions with it? Especially dash-to-dock or dash-to-panel

**Comment by aunetx** [comment]
If you want to use the extension, I guess you will need to either disable the "blur dash" switch, or disable dash-to-dock (as I believe it is causing this)
I will try to update soon

**Comment by aunetx** [comment]
Added support for dash-to-dock (but that's not very beautiful as I can't do round corners)
Please reopen the issue if your bug is still present with last commits on gnome-40 branch

**Comment by TimestaticYT** [comment]
@aunetx Yeah i was using dash to dock. Sorry for taking so long to answer
