### ISSUE TITLE
With update to GNOME Shell 43.1, (admittedly) beta Application window blur breaks (EDIT:) In Wayland

### ISSUE THREAD

**Issue by juanejot** [aunetx/blur-my-shell#372]
I just accepted an updated from gnome-shell 43.0-2 to 43.1-1, and it seems to have broken Blur My Shell's application window blur beta functionality. The app window I had selected to blur, was no longer blurred, and editing your extension's preferences to select it, I was first told I'd have to select a window (which I had, and it was listed). So I deleted that entry, and couldn't re-create another one (either selecting the window with red boundaries around it, or typing it in).

This is probably a GNOME 43.1 change in functionality, and not a shortcoming of this beta feature in your otherwise working software. That said, I just wanted to let you know of the external change to GNOME Shell (whatever it is) that you may have to deal with (provided it's hopefully "finalized" for now).

EDIT: Further diagnosis: downgrading the gnome-shell package to the previous version did not reverse the behavior to "expected;" it still has broken functionality, manifesting in the same was as above. I don't see any other recently updated GNOME packages that _I_ (as a layman) consider likely to be contributing to the issue, but happy to search my logs if there's something in particular you think might have affected it. Also, maybe a .conf file that affects Blur My Shell's ability to identify blur-able application windows got changed with the GNOME Shell 43.1 update?

EDIT 2: It's only some windows (gnome-terminal is not blurred, but Firefox is) and only in Wayland (normal functionality in X11). This should be fun to track down a solution to whatever GNOME has changed from 43.0 to 43.1!

**Comment by Plyply99** [comment]
I wonder if it's tied to Mutter update to 43.1.  Gnome-shell and Mutter were both just update to 43.1  on Fedora. I'm on wayland and experience exactly what Juanejot experiences.

**Comment by juanejot** [comment]
> I wonder if it's tied to Mutter update to 43.1. Gnome-shell and Mutter were both just update to 43.1 on Fedora. I'm on wayland and experience exactly what Juanejot experiences.
> 
> Edit: Gnome terminal still has blur but only if you have Transparent background checked.

My Mutter appears to likewise have been updated to 43.1, in the same pacman run as gnome-shell got the same version upgrade.

Do you see similar behavior that everything works in X11, but not in Wayland, @Plyply99 ?

**Comment by Plyply99** [comment]
> > I wonder if it's tied to Mutter update to 43.1. Gnome-shell and Mutter were both just update to 43.1 on Fedora. I'm on wayland and experience exactly what Juanejot experiences.
> > Edit: Gnome terminal still has blur but only if you have Transparent background checked.
> 
> My Mutter appears to likewise have been updated to 43.1, in the same pacman run as gnome-shell got the same version upgrade.
> 
> Do you see similar behavior that everything works in X11, but not in Wayland, @Plyply99 ?

Haven't tried X11 yet. But what I did do is this.

Deleted all my blurred windows.
Turn on Enable All by Default and set Background Opacity to a lower value such as 150. You'll see that all windows do indeed blur. It's just not working the way it used to.

**Comment by Plyply99** [comment]
@juanejot 
Ok, I just downgraded Mutter from 43.1 to 43.04 and everything is working!
I can choose windows again and the blur looks proper.

**Comment by juanejot** [comment]
> @juanejot Ok, I just downgraded Mutter from 43.1 to 43.04 and everything is working! I can choose windows again and the blur looks proper.

Cool! I think I'm going to forgo downgrading, as the distro maintainers have taken some time to test that GNOME 43.x elements will work well together. That said, I hope it ends up something that aunetx can work around for version 45 of blur-my-shell.

Not closing because while my curiosity is sated & the rest of Blur My Shell works flawlessly, this (beta) issue with some application windows in Wayland stands. It does not appear to be a GTK3/GTK4 issue (feel free to ask about my testing), and it does not appear to be about GPU rendering the window or not (again, feel free to ask). That said, let me know if there's any further investigation or diagnostic logs I can provide about what's interacting differently between Blur My Shell 44 & Mutter 43.1 (vs. 43.04). Thanks!

**Comment by juanejot** [comment]
> @juanejot Ok, I just downgraded Mutter from 43.1 to 43.04 and everything is working! I can choose windows again and the blur looks proper.

Can confirm: downgrading to mutter 43.0 does bring functionality back, though the old reference to at least one window ("gnome-terminal") didn't work & I had to re-select it to restore functionality (upon which time, it was named "gnome-terminal-server," perhaps for better compatibility running on the same system as the newer gnome-console? This is getting into a lot of variables to track down…)
Of interest, when I re-upgraded to mutter 43.1, functionality was again broken for the selected "gnome-terminal-server" window in Wayland, **but, during transitions** (such as the animation of the "Show Applications" button on Dash/Dash-to-Dock), the window in question _briefly flickers_ with blur, and an attempt at "blur" (which appears to be a blurred rendering of the screenful of applications) shows up in that minimized window inside the desktop selectors near the top of the screen.
It appears to my completely lay/GUI use of the system, that with a proper, updated window name, Blur My Shell at least has now gotten the update about _which_ application window to blur, and does it until "overruled," I suppose you could say, by mutter 43.1.

If there are particular commands to get this Mutter 43.1/Blur-My-Shell 44 interaction started in the GUI from the command line (so we can get the trace of any errors), I'm happy to hear it & try.

**Comment by juanejot** [comment]
UPDATE: Following a few other updates (sorry that no amount of `grep`ing in pacman.log seems to reveal to my lay eyes what it might have been that changed things), a _kind_ of functionality has returned to the app window blur; it flickers on for more time per window selection now, still flickering back off, and generally remaining dark and sigma-ed out rather than blurred (no matter the sigma or opacity settings). Since this is not a Blur My Shell issue, but a whatever-is-going-on-with-GNOME/Mutter/etc. issue, I'm closing the issue. If considering whether to keep though, please archive in place so others who see app window flicker know they're not seeing things!
