### ISSUE TITLE
Blur applies to the top panel once more after each unlocking the desktop.

### ISSUE THREAD

**Issue by Fenimoure** [aunetx/blur-my-shell#373]
Noticed the top panel gets darker after I lock and unlock the screen.
The extension has been installed from extensions gnome org.

**Comment by Fenimoure** [comment]
Noticed the top panel gets darker after I lock and unlock the screen.

**Comment by aunetx** [comment]
Hello, I should have fixed this recently, please reopen this issue if this is not the case
