### ISSUE TITLE
[BUG] Blur stays applied on the top panel after the system wakes up from suspend state

### ISSUE THREAD

**Issue by notmde** [aunetx/blur-my-shell#377]
![image](https://user-images.githubusercontent.com/99078610/202848917-91cc27c5-8371-4857-906b-c4c1ce62dcf9.png)

Blur stays applied on the top panel after the system wakes up from suspend state. But this isn't a problem when system is in locked state.

Expected:
Blur not being applied on top bar, just like how it is in lockscreen.

What happens:
The blur shows up. Which looks very out of place.

**Comment by n3thshan** [comment]
was about to submit this issue! if lock screen blur is disabled, when locking device the panel is not blurred but when waking from suspend state the top panel is blurred giving a disproportionate blur between the top panel and lock screen.

**Comment by Saren-Arterius** [comment]
The blur stays even after disabling the extension. Need to restart gnome shell by logout and login to clear that. I suspect this bug costs extra GPU resources.

**Comment by Neo-29** [comment]
confirmes

**Comment by mattia-b89** [comment]
sometimes (1 over 10 times) it works:  topbar too get blurred;  
is there a way to enable verbose logging to debug this case?

**Comment by mattia-b89** [comment]
a little update: after I upgraded to gnome-desktop 43.1 I haven't experienced the issue anymore;  
any feedback?

**Comment by thisisheymde** [comment]
still issue for me in gnome 43.2 @mattia-b89

**Comment by Neo-29** [comment]
> still issue for me in gnome 43.2 @mattia-b89

Can confirm that the bug seems to be gone.

**Comment by mattia-b89** [comment]
Unfortunately, it still happens
Fortunately, it is less prone to

**Comment by Neo-29** [comment]
Still on gnome 43.4
What's the status of this issue?
Patch?

**Comment by aunetx** [comment]
I will need to work more on this, the only way to correctly fix it is to use "session modes" so that the extension is loaded in `unlock-dialog`.

I don't know at all how to do it though, and it would require some profound changes to the way the extension is loaded (which may be good though, as it is prone to crash right now...)

The second thing to do would then be to allow to enable/disable the panel in lockscreen too, so that disabling lockscreen blur would mean not blurring the panel either.

**Comment by pacho2** [comment]
Hello,

Some weeks ago while trying to understand the issue I was suffering in bug #452 I managed to get blur-my-shell to work after resuming from suspend by relying on unlock-dialog setting. I appended it to the metadata.json that ended up being like this:
```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Adds a blur look to different parts of the GNOME Shell, including the top panel, dash and overview.\n\nYou can support my work by sponsoring me on:\n- github: https://github.com/sponsors/aunetx\n- ko-fi: https://ko-fi.com/aunetx\n\nNote: if the extension shows an error after updating, please make sure to restart your session to see if it persists. This is due to a bug in gnome shell, which I can't fix by myself.",
  "name": "Blur my Shell",
  "original-authors": [
    "me@aunetx.dev"
  ],
  "settings-schema": "org.gnome.shell.extensions.blur-my-shell",
  "shell-version": [
    "42",
    "43",
    "44"
  ],
  "url": "https://github.com/aunetx/gnome-shell-extension-blur-my-shell",
  "uuid": "blur-my-shell@aunetx",
  "session-modes": ["user", "unlock-dialog"],
  "version": 46
}
```

After that, each time I resume, blur-my-shell handles the lock screen...

**Comment by aunetx** [comment]
@pacho2 thank you very much for this! Does everything works well when `unlock-dialog` is used? Last time I tried there seemed to be bugs (I don't remember what exactly), but if it is okay I will try to go this way!

**Comment by pacho2** [comment]
For me it seems to work :/ but of course there could be some side effects that I haven't noticed yet.

Anyway... I think the change could be tried

**Comment by nonresidentaliennico** [comment]
i tried appending  "session-modes": ["user", "unlock-dialog"] to metadata.json but i still get the same issue with the top panel staying when i lock/suspend my laptop. has anyone come up w another solution yet?

**Comment by jojommeke** [comment]
still having this issue on wayland with the app blur and others stop working on wakeup from suspend
