### ISSUE TITLE
Disable panel blur when a window is maximized or tiled

### ISSUE THREAD

**Issue by JoseExposito** [aunetx/blur-my-shell#378]
## Feature request:

Allow to disable panel blur when a window is maximized or tiled.

## Previous requests

I searched for similar requests and it looks like a PR was merged to add this feature:
https://github.com/aunetx/blur-my-shell/pull/272

However, I don't see the code in `master`. Was it reverted?

Thanks for this extension!

**Comment by aunetx** [comment]
Hello, sorry for the delay, the feature still exists in the preferences, when you expand "override background", you have the switch "disable when a window is near". Is it what you wanted?

**Comment by JoseExposito** [comment]
Thanks a lot, that's what I was looking for. I overlooked the expand arrow.
