### ISSUE TITLE
[BUG] Extension blur settings not respected by lock screen, even when lockscreen blur is enabled in extension, only when laptop is awaken when lid is open

### ISSUE THREAD

**Issue by n3thshan** [aunetx/blur-my-shell#384]
![image](https://user-images.githubusercontent.com/97467958/204814981-a7743370-6aed-4661-a317-38dca79549f0.png)
Expected behaviour : To have uniform blur in lock screen when laptop lid is open after suspend 

Actual behaviour : Top panel respecting blur but rest of lock screen using stock gnome blur effect not making blur uniform. Only happens if laptop is awakened from suspend when lid is closed and opened. Does not happen when manually locking screen or suspend toggles from quick settings panel. 

GNOME 43, Fedora Workstation 37

**Comment by zero-hugo** [comment]
I have the same problem.And it still happen when manually locking screen

GNOME43 ，Ubuntu 22.10,wayland

**Comment by kojq** [comment]
Why was this issue opened when there's #377?

**Comment by mattia-b89** [comment]
Same here w/ Arch Linux, GNOME 43.2, Xorg

**Comment by mattia-b89** [comment]
just to integrate my previous comment,  
today, for the first time since I have this extension installed, topbar got blurred on lock screen
![Screenshot from 2023-01-08 20-14-52](https://user-images.githubusercontent.com/545463/211219444-7b3293ee-cbad-4cbe-9510-4af35c97bfc7.png)

**Comment by aunetx** [comment]
dup of #377, thanks for the reports... I can't get it to work right
