### ISSUE TITLE
Weblate translation locked

### ISSUE THREAD

**Issue by flipflop97** [aunetx/blur-my-shell#393]
The translations on Weblate have been locked for a while with the following error. Translators are therefore unable to contribute via Weblate.

[```Pull request failed: You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.```](https://hosted.weblate.org/projects/blur-my-shell/blur-my-shell/#alerts)

**Comment by aunetx** [comment]
Hello, thanks for telling me, could you try again? Weblate now say I have fixed it but I'm not sure (it may come from some github tokens...)

**Comment by flipflop97** [comment]
Yes, it's working again now, thanks!
