### ISSUE TITLE
Application blur only works on Xorg, and doesn't respect the rounded corners

### ISSUE THREAD

**Issue by hrqmonteiro** [aunetx/blur-my-shell#396]
![Screenshot from 2023-01-04 16-28-55](https://user-images.githubusercontent.com/17055027/210634482-90c5b941-a2a5-4e2c-ba0f-ea790ac6d59a.png)

See the black squares on the rounded edges

**Comment by duckyondiscord** [comment]
Yeah, I can't stand that, KDE had the same bug, though I think they fixed it already

**Comment by IntoTheVoid-900** [comment]
![image](https://user-images.githubusercontent.com/74509183/221489890-9df9e2c4-9763-4c7b-8a1c-d0256659395c.png)
Seems to be working on Wayland for me

**Comment by hrqmonteiro** [comment]
> ![image](https://user-images.githubusercontent.com/74509183/221489890-9df9e2c4-9763-4c7b-8a1c-d0256659395c.png) Seems to be working on Wayland for me

It is not blurring, is just transparent.

**Comment by IntoTheVoid-900** [comment]
> It is not blurring, is just transparent.
Look closely, that is blur, not just transparency. It is most obvious in Web, where the yellow part of the wallpaper meets the purple.
