### ISSUE TITLE
Memory leak in overview blur

### ISSUE THREAD

**Issue by hcoggins** [aunetx/blur-my-shell#402]
## Description
I've noticed that showing the gnome overview or switching workspaces causes the allocated shared memory to increase when the background blur for the overview is turned on. Over the course of a working day, this can cause the allocated shared memory to be very high (upwards of 20GB on my machine), leading to performance problems. This memory leak does not occur when the background blur for the overview is turned off. 

I have observed this on two different machines and on both Wayland and X-org.

The shared memory can only be de-allocated by logging out in Wayland, or resetting the shell in X-Org (`Alt-f2 + r + Enter`).

## Demonstration

https://user-images.githubusercontent.com/40951916/216572079-e298af61-5a72-41a6-b82b-4b9efbf2d4f2.mp4

The above video shows how the memory leak occurs when blur is turned on. The plot shows the allocated shared memory of the system (output of `free | awk 'NR==2 { print $5 }'`) over time.

## System Info
**OS**: Arch Linux
**Kernel**: 6.1.9-arch1-1
**Gnome Shell**: 43.2
**Compositor**: Wayland

**Comment by hcoggins** [comment]
After a bit of playing around with the source code, I think it has to do with the background-actors in `src/components/overview.js`. I'll give an update if I find out more.

**Comment by DimitrisMilonopoulos** [comment]
Ah yes had the same issue. I disabled the extension completely.

I feel until another maintainer steps in, or main maintainers can allocate time.
This extension should be marked as unsuitable for use.

**Comment by aunetx** [comment]
Hello @hcoggins, thank you for your detailed issue, I will try to figure out what is wrong... I never noticed it before, even though I checked regularly for such leaks using system monitor, sorry :/

Would you mind sharing the code you used to show the memory graph? I don't know well gnuplot, and that's way better than just looking at the number to test it :)
I keep you updated!

**Comment by aunetx** [comment]
Could you try the PR #405 please? I think it should be fixed, but I'm not entirely sure (it does not increase the memory anymore for me, but it could just be something else)

**Comment by inthreedee** [comment]
I gave it a quick test. Before the test, I saw my shared memory going up a few MB every time I went into overview or swapped desktops. After a reboot, it stopped happening though so I suspect uptime might also be a factor?

In any case, after the patch, my shared memory doesn't appear to be increasing anymore on Wayland or Xorg. But I haven't done exhaustive testing and only left my system up for a day so far.

**Comment by hcoggins** [comment]
Hello @aunetx! Sorry for the late response. Thank you for the patch! I'll try it out and let you know how it works.

The small script to graph `shmem` in gnuplot is:

```
#!/bin/bash

# file to write shmem data to that gnuplot reads
FILEPATH=$HOME/Temp/shmem

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

while true; do
    LANG=en free | awk 'NR==2 {print $5}' >> $FILEPATH
    sleep 1
done &

gnuplot -p -e "
    set ylabel \"shmem (kB)\";
    set xlabel \"time (s)\";
    set title \"Shared Memory vs Time\";
    while (1) {
        plot \"$FILEPATH\" with lines lw 4; 
        pause 1; 
    }" 
&

wait %1 %2

```

**Comment by cpu012** [comment]
I have the same issue and found that disabling animations fixed the issue

**Comment by aunetx** [comment]
This now happens to me too, I can try to fix this (although this is visibly not directly an issue from blur-my-shell only, but rather from both the poor management of effects by this extension and a leak in cogl pipeline which makes destroying effects bleed ram).

I opened #480 to fix it, but this is a first iteration, which does NOT work at all yet (I think I must have mistyped something because nothing actually works), and might actually not fix everything... in the long term, this will probably require quite a lot of work.

For the moment, I have a quick question: do you have noise and color effects enabled? Because it looks like I bleed ram only with those enabled, although I'm not certain.

**Comment by aunetx** [comment]
Could you try #480? It should fix most of the memory leaks (some might still happen because the effects are actually not destroyed but simply reused, so there is a little overhead, but at least it is stabilized and should not take up more than a dozen megabytes)

**Comment by aunetx** [comment]
It is completely fixed for me with this PR, so I will close this and merge #480. If the problem still persists, please please reopen this!!!
