### ISSUE TITLE
noise effects are producing black dots on screen

### ISSUE THREAD

**Issue by lictex** [aunetx/blur-my-shell#406]
settings:
![image](https://user-images.githubusercontent.com/13201009/218253493-0807c81f-2f83-4375-8cb7-dbc241dbb344.png)

result:
![image](https://user-images.githubusercontent.com/13201009/218252972-179c526e-5cc8-44a1-aa57-16ef9c66e783.png)

this happens when the `noise amount` is any value greater than 0

**Comment by xyning** [comment]
[seems that sometimes this is `NaN`](https://www.shadertoy.com/view/ctSXWw)
https://github.com/aunetx/blur-my-shell/blob/2c4ecf0ec5f223af7d60d007db8c52e3cd53ff24/src/effects/noise_effect.glsl#L15

**Comment by aunetx** [comment]
Thanks a lot! Fixing right now
