### ISSUE TITLE
Switching to another workspace using the trackpad blurs entire screen

### ISSUE THREAD

**Issue by Senya247** [aunetx/blur-my-shell#407]
ubuntu 22.04.01
gnome shell 42.5
blur my shell 44

Switching to another workspace using the 3 finger sideways swipe blurs the entire screen. This doesn't happen when switching workspace with super+pg up/dn, or going into overview and clicking on another workspace.
Going into the overview, and clicking on another workspace seems to fix the blur, until I use the trackpad to switch again.
[Screencast from 11-02-23 06:36:46 PM IST.webm](https://user-images.githubusercontent.com/65822218/218259674-62adff8b-671f-483f-80dd-61754387db79.webm)

**Comment by EthanLatimerGB** [comment]
Having similar issues with Fedora 37. Dual monitors and switching workspaces will make programs to not render.

**Comment by Senya247** [comment]
Turns out it wasn't a problem with blur my shell, but mutter-rounded
