### ISSUE TITLE
I know why Application Blur not working.

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [aunetx/blur-my-shell#411]
This might be a "no shit" moment for you, but looked into the application blur code and found the `xprop` code, which is not compatible with wayland. 

Then on my wayland session I opened kitty forcing it to x11 and enabled application blur. All wayland apps didn't blur, but kitty did. 

One way to mitigate it is to find a way to use an xprop alternative to wayland. Might investigate further if I find something that makes sense.

**Comment by IntoTheVoid-900** [comment]
![image](https://user-images.githubusercontent.com/74509183/221489613-3bb2d86f-e877-468a-95c7-e31203e239a0.png)
This is all default settings on Vanilla OS.

**Comment by DimitrisMilonopoulos** [comment]
Wayland?

**Comment by IntoTheVoid-900** [comment]
As the terminal says, yes, that is on Wayland

**Comment by CorvetteCole** [comment]
application blurring is done by looking for a mutter hint attached to a window, which is not reliant on X11 or xprop. xprop may only work on X11, but that is just a simply way to set the mutter hint to  trigger application blur
