### ISSUE TITLE
Application blur

### ISSUE THREAD

**Issue by userjona** [aunetx/blur-my-shell#412]
The application blur doesn't detect new windows even if they are in the white list, it only works if you refresh the extension.

**Comment by DimitrisMilonopoulos** [comment]
@userjona is this on wayland or x11?

**Comment by userjona** [comment]
wayland

**Comment by IntoTheVoid-900** [comment]
You need to reboot for it to start fully working, and even then its inconsistent

**Comment by aunetx** [comment]
Could you try again now form last commit please? I fixed some issues so it may work better
