### ISSUE TITLE
multi monitor working like 50% of the time

### ISSUE THREAD

**Issue by Colon101** [aunetx/blur-my-shell#419]
im running on two displays and for some odd reason every couple of times the blur just goes away and on my 2nd display it never happend i tried changing the configuration of displays like one hooked up to igpu and 2nd not and both on gpu and like nothing changed 
i have an amd gpu and running gnome 43 if it changes anything 

https://user-images.githubusercontent.com/99831740/227308287-0070d294-e859-4950-896b-5f5d19b9eaad.mp4

**Comment by K4rakara** [comment]
After some experimentation, I've determined that its always the leftmost monitor that this happens on. For example:
![image](https://user-images.githubusercontent.com/40474474/227669565-531ac33e-3f28-4632-b440-5c1b1a3ee0d3.png)

**Comment by Colon101** [comment]
yeah same here honestly i cant change the positions of my monitors cause one of them is lower resolution is there any way to fix it or change that?

**Comment by Colon101** [comment]
i just found a temporary fix to my issue its not perfect and stuff but basically in gnome display settings make the buggy display go up like in this picture
![image](https://user-images.githubusercontent.com/99831740/227784826-ad4eb8c7-a367-4809-91c7-f325afc51f32.png)
and it fixed everything honestly i believe this is kinda stupid

**Comment by CorvetteCole** [comment]
This sounds like https://github.com/aunetx/blur-my-shell/issues/40

**Comment by osdamv** [comment]
> i just found a temporary fix to my issue its not perfect and stuff but basically in gnome display settings make the buggy display go down or the working display up like in this picture ![image](https://user-images.githubusercontent.com/99831740/227784826-ad4eb8c7-a367-4809-91c7-f325afc51f32.png) and it fixed everything honestly i believe this is kinda stupid

It just need to  out of alignment
![image](https://github.com/aunetx/blur-my-shell/assets/4120796/4775fd64-b23e-4199-9f8a-0a5bc6d9990b)
Weird weird bug
