### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by fMorales-97** [aunetx/blur-my-shell#42]
`The settings of extension blur-my-shell@aunetx had an error:
```
TypeError: this._sigma_scale is null
```

Stack trace:
```
_init@/home/francisco97/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:31:9
buildPrefsWidget@/home/francisco97/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:133:12
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`
I don't know what this means, I'm using Manjaro Gnome, the shell is 3.38 and all the gnome apps are version 40.

**Comment by CorvetteCole** [comment]
Hey there, can you please go to ~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/metadata.json and tell me the version number listed?

**Comment by fMorales-97** [comment]
> Hey there, can you please go to ~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/metadata.json and tell me the version number listed?

It says that the shell-version is 40

**Comment by fMorales-97** [comment]
> Hey there, can you please go to ~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/metadata.json and tell me the version number listed?

It says that the shell-version is 40

**Comment by CorvetteCole** [comment]
that shouldn't be the case if you are on Gnome 3.38. It sounds like you might have a dconf option enabled to allow you to run unsupported extensions. This would allow blur my shell to be upgraded on your Gnome 3.38 she'll. Try uninstalling the extension, then going to our extensions.gnome.org page and reinstalling. Make sure to explicitly select 3.38 in the drop-down box before installing. In the future, I recommend disabling the dconf option for unsupported extensions. I can take a look where that is if you don't know

**Comment by CorvetteCole** [comment]
please re-open this issue if the problem persists

**Comment by ArchitektApx** [comment]
@fMorales-97 had the same issue with the Version installed from AUR on Manjaro with Gnome 40. 
Getting the extension via the gnome-extensions website worked properly

**Comment by CorvetteCole** [comment]
Frankly, although I use Arch, I don't recommend installing extensions outside of extensions.gnome.org. Extension authors being in control of the distribution of their own creation is a big deal :)
