### ISSUE TITLE
"Add Window" does not select the terminal. (Fedora 37)

### ISSUE THREAD

**Issue by chtholine** [aunetx/blur-my-shell#424]
Hello! I wanted to blur my gnome-terminal and add it to the "whitelist". 
But selection with a mouse doesn't work, and it blurs only using "Enable all by default".

**Comment by Hioness** [comment]
Are you using gnome in xorg? The application blur and selection tool don't work in Wayland for me, or anyone else I think.

**Comment by chtholine** [comment]
> Are you using gnome in xorg? The application blur and selection tool don't work in Wayland for me, or anyone else I think.

I'm using Wayland, but "Enable all by default" works fine.
Is the problem in Wayland?

**Comment by westcap** [comment]
Here's a temporary solution as "Enable all by default" uses more hardware resources as it put a blur layer at the bottom of all windows.

Hit Alt+F2, type `lg`, hit enter and GNOME will drop a flyout window:
![image](https://user-images.githubusercontent.com/38320310/235865099-524814e9-03b6-4fd6-a6dc-0400d6aec04e.png)

Switch to the "Windows" tab, there you'll see a list of windows living on GNOME. You will need to take the `wmclass` value of the application you want to apply the blur on (it won't allow you to select text to copy/paste), then write that value back into the text field of manual "Select window" section next to the mouse cursor icon.

For example, I have a following list of running windows:
![image](https://user-images.githubusercontent.com/38320310/235866326-7b779cae-2777-4f09-b7c3-5127b7f8b0c6.png)

and I want to blur "Black Box" terminal app, so I need to take it's `wmclass` value, which is `com.raggesilver.BlackBox` and put it into the manual selecting window section:
![image](https://user-images.githubusercontent.com/38320310/235866799-df612cc8-ba1e-453b-b876-bc7aeea93dcb.png)
 
Ta-da! It works!
![image](https://user-images.githubusercontent.com/38320310/235867125-77b3aa9e-29ea-438d-8768-8c63e61fc097.png)

**Comment by chtholine** [comment]
Thank you for a detailed explanation! This works well!
