### ISSUE TITLE
The Blur All option doesn't work

### ISSUE THREAD

**Issue by RAinb0wStAr9938** [aunetx/blur-my-shell#427]
Here's an image:
Before:
![Screenshot from 2023-04-25 18-20-28](https://user-images.githubusercontent.com/125708947/234416783-319a4a84-3560-4b48-a6bc-dddf3bb32de2.png)
Edit: I have to change the opacity setting, but it's still a problem
After:
![Screenshot from 2023-04-25 18-25-03](https://user-images.githubusercontent.com/125708947/234417520-1575c2f4-8d92-47d0-9592-7e21bcbca594.png)

**Comment by aunetx** [comment]
I just fixed this in the last commit, will push soon to extensions.gnome.org for gnome 45
