### ISSUE TITLE
Artifact with Top Bar when using this extension

### ISSUE THREAD

**Issue by tdtooke** [aunetx/blur-my-shell#429]
It's hard to describe this so I'll just use images.  This is my desktop without this extension:

https://i.postimg.cc/T3RyBdWv/Screenshot-from-2023-04-29-10-42-43.png

And this is what happens when I turn this extension on:

https://i.postimg.cc/L6LY3ZYz/Screenshot-from-2023-04-29-10-43-19.png

Edit: Just for clarity, initially I just installed it from extensions manager but after observing this I got the latest from git and installed that via an Arch aur package.  Also I'm on gnome 43.4  Forgot to mention.  I'm also using Wayland.

**Comment by aunetx** [comment]
Hello, you seem to be using a custom theme, unfortunately it really is too hard for me to keep up with unofficial themes as the bounding boxes often are elongated (which is the case here, the extension believes your panel extends down).

If you really want to have this fixed on your system, you can try to change src/components/panel.js at line 330, and remove some pixels to the height.
