### ISSUE TITLE
Panel is transparent with visible black rounded corners when panel blur is disabled

### ISSUE THREAD

**Issue by GabMus** [aunetx/blur-my-shell#43]

**Comment by willgfx** [comment]
(Version 9)
![Screenshot from 2021-04-22 08-13-23](https://user-images.githubusercontent.com/21956520/115720398-a668ff00-a342-11eb-8dbc-6cdd574b1553.png)

**Comment by carlocastoldi** [comment]
I bisected the bug. it's 31dccd23019f4d0ce23f66a858969552f9e127e2's fault

**Comment by aunetx** [comment]
Sorry, just fixed this in last commit :)

**Comment by GabMus** [comment]
Sorry for the blatant OT, but @carlocastoldi are you the same Carlo that was in Cazzola's lectures with me?
