### ISSUE TITLE
glitch on icons 

### ISSUE THREAD

**Issue by Neo-29** [aunetx/blur-my-shell#435]
![image](https://github.com/aunetx/blur-my-shell/assets/90937180/fb26d67d-ecbc-4007-b69f-dd48dbbda856)

happens with `extension-manager` app too

Archlinux gnome 44.1 on x11

**Comment by sidevesh** [comment]
I see this too but this happens even with blur my shell disabled, are you sure @Neo-29 that this is due to blur my shell or some other extension ?

**Comment by Neo-29** [comment]
> I see this too but this happens even with blur my shell disabled, are you sure @Neo-29 that this is due to blur my shell or some other extension ?

It's the case for some extensions like extension manager too.
Don't know where it's coming from.

**Comment by CorvetteCole** [comment]
Seems like this is not a Blur My Shell issue, but it could be. Further information required, since it occurs elsewhere as well

**Comment by Neo-29** [comment]
> Seems like this is not a Blur My Shell issue, but it could be. Further information required, since it occurs elsewhere as well

Seems to be gone on gnome 45

This can be closed if you want.
