### ISSUE TITLE
Panel blur and Desktop icon NG

### ISSUE THREAD

**Issue by mi16087** [aunetx/blur-my-shell#438]
Blur my shell option to disable panel blur when window is near is always disabling blur when extension for desktop icons is activated (Desktop icons NG). Is there a way to ignore Desktop icon extension like it's not a window near?

**Comment by aunetx** [comment]
By the way, are you using X11? If so, it is still present under wayland?

**Comment by aunetx** [comment]
Hello, I fixed this in last commit, so closing this. If in next release (or in last commits from github), this bug is still appearing, could you reopen it?

**Comment by mi16087** [comment]
Sorry for not answering earlier. It's fine now. I don't know which distro i was on at that time, but now im on nobara os, which is practically fedora on steroids, so it's wayland, I think, and everything seems to be in order.
