### ISSUE TITLE
Add option to disable panel transparency to keep Adwaita's rounded corners

### ISSUE THREAD

**Issue by sk22** [aunetx/blur-my-shell#44]
With the extension off and using the default Adwaita theme, my panel looks like this (notice it is black and has rounded corners):

![image](https://user-images.githubusercontent.com/6217438/115785250-8166a180-a3bf-11eb-8c1a-8f080b9bfa6c.png)

Blur my Shell adds transparency and removes the special rounded corner style that Adwaita has:

![image](https://user-images.githubusercontent.com/6217438/115785383-a6f3ab00-a3bf-11eb-94f9-d646a3014d5c.png)

In overview, the panel is transparent (or at least not black), with or without the extension:

![image](https://user-images.githubusercontent.com/6217438/115785443-c25eb600-a3bf-11eb-972e-9be951f7b93e.png)
![image](https://user-images.githubusercontent.com/6217438/115785487-d0143b80-a3bf-11eb-92fc-ea495f76fb1c.png)

That said, it would be really cool to be able to turn off the transparency when not in the overview.

Thanks a lot for the extension!

**Comment by Dziban-dev** [comment]
i don't think this is possible since the "rounded" corners are appear to be just 2 images being rendered over the window. but it would be cool

**Comment by sk22** [comment]
> i don't think this is not possible since the "rounded" corners are appear to be just 2 images being rendered over the window. but it would be cool

well yeah, seems like it.. but couldn't it be possible to have the background color's and corner images' `opacity` properties animate from 0 (in overview) to 1 (on desktop)? maybe this could cause problems or would be hard to implement, i don't know

**Comment by aunetx** [comment]
Sorry, this was an unintended bug, just fixed in last commit :)
