### ISSUE TITLE
Random crashes of gnome-shell

### ISSUE THREAD

**Issue by sidevesh** [aunetx/blur-my-shell#445]
https://github.com/yilozt/rounded-window-corners/issues/121
There seems to be some issue maybe in combination with rounded window corners extension that causes the gnome-shell to crash every once in a while, killing everything on wayland and logging the user out, which is a big issue.
I have added the error details on the above issue.

**Comment by KCGD** [comment]
Im getting inconsistant crashes on login. Here's a snipped from journalctl:

`
Jul 21 12:42:41 b systemd[1109]: Started dbus-:1.5-org.freedesktop.FileManager1@0.service.
Jul 21 12:42:41 b gnome-shell[1331]: [Blur my Shell > extension]    enabling extension...
Jul 21 12:42:41 b gnome-shell[1331]: [Blur my Shell > overview]     blurring overview
Jul 21 12:42:41 b kernel: gnome-shell[1331]: segfault at 55eb2df7e000 ip 00007f01c57dac75 sp 00007ffefe12a550 error 4 in libst-12.so[7f01c57a5000+6b000] likely on CPU 4 (core 4, socket 0)
Jul 21 12:42:41 b kernel: Code: 05 00 48 85 db 74 5b 4c 63 e8 4c 89 e6 48 89 df ff 15 17 c9 05 00 48 85 c0 74 3c 48 8b 15 b3 ca 05 00 48 8b 2a 48 39 c3 74 0b <0f> b6 50 ff f6 44 55 01 01 74 10 42 0f b6 14 28 84 d2 74 19 f6 44
Jul 21 12:42:41 b systemd[1]: Created slice Slice /system/systemd-coredump.
`

**Comment by worldpe** [comment]
I had this issue too

**Comment by toppk** [comment]
@worldpe did you grab a coredumpctl gdb "bt full" trace?  I have this to, and want to see if the crash is in the same place.

**Comment by toppk** [comment]
I have the similar symptoms.  Looks to me like removing and empty style class name leads to corruption. 
 I filed an upstream bug here, but I'm just guessing, because the crash shows what looks to me to be a corrupt style class list, and an empty class name.   https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7152
