### ISSUE TITLE
Support for Dash To Panel

### ISSUE THREAD

**Issue by t0msk** [aunetx/blur-my-shell#447]
You already have support for Dash To Dock, but I use Dash To Panel (better imho) so I would be very happy if you could provide support for Dash To Panel too :)

Note: yes your extension blurs Dash To Panel, but it could be in settings on/off switch for it, because I would like to have Dash To Panel blurred but top bar I would like to have **not** blurred :) I would like to have blurred everything except top bar :)

**Comment by aunetx** [comment]
Done, will include in next update :)
