### ISSUE TITLE
Error when clicking the settings button in extensions menu

### ISSUE THREAD

**Issue by Boris00035** [aunetx/blur-my-shell#448]
Loving this extension, but recently a problem has surfaced. 

When I try to change the settings, I get the following stack trace:
[pastebin link](https://pastebin.com/DrWRUSHC)

I have tried reinstalling the extension, logging out and back in etc.

Running Manjaro with gnome 44 on wayland.

If there is need for more info, please let me know!

**Comment by aunetx** [comment]
Hello, I don't have any idea why this occurs, I just added a statement to prevent the crash (this disables the top-left menu if it is not loading correctly, but you do not lose in functionalities)

**Comment by Boris00035** [comment]
Thanks for maintaining this!
