### ISSUE TITLE
Signals are not properly disconnected, leading to duplicate callbacks

### ISSUE THREAD

**Issue by CorvetteCole** [aunetx/blur-my-shell#45]
It seems to me that if you call disable() in panel.js, it won't actually disconnect the signals at: https://github.com/aunetx/blur-my-shell/blob/f48d7bcdac060d31ece008eb2d8eff90ec256819/src/panel.js#L60 until the extension calls disconnect_all().

This would cause a potential bug where if a user where to disable and re-enable the panel setting it would create additional connections which has a performance implication.

It seems to me like the solutions to this at a glance would be to delete and recreate the _panel_blur object upon disable, disconnect the signals manually, or provide some kind of interface with the Connections class to disable all signals from a particular source (e.g. panel class). I am looking in to this as we speak.

**Comment by CorvetteCole** [comment]
If I am missing something obvious which explains this, please let me know. I am going to work on creating a solution to this

**Comment by CorvetteCole** [comment]
I think the easiest solution to this would be to hold a list of Connections classes in the main extension.js file, then iterate through those when we do an extension disable and call disconnect_all() on all of them. Then in each class we could call disconnect_all() in disable and that would only disconnect the signals from that class.

**Comment by CorvetteCole** [comment]
Also on that note, we aren't allowed to do anything in init(), including creating objects. See here: https://wiki.gnome.org/Projects/GnomeShell/Extensions/Review. We need to move these settings and connections object creations elsewhere anyways. I will implement these changes

**Comment by aunetx** [comment]
Sorry for the late responses, I really needed (and still need) to work :p and thanks for working so much on the extension!
You're right, the signal are not disconnected until the extension is disabled... I though that this was probably not too bad, as they were at least cleaned up after disabling the extension, but this is obviously not a clean solution
I guess the simplest thing would be to create a different `Connections` class for each element, and then make sure to remove all of them when extension is disabled!

For the `init()` part, sorry I though it was ok to create objects if they did not do anything to the shell! Do you think we will need to create them in `enable()` then?
