### ISSUE TITLE
Native Ubuntu apps (like Settings and Nautilus) no longer blurred

### ISSUE THREAD

**Issue by nightlyte-dev** [aunetx/blur-my-shell#451]
I'm on Ubuntu 22.10 running X11. I also am running the Fluent GTK theme, with the specific "blur" version for Blur My Shell installed. 

While I was on Ubuntu 22.04, I was able to get application blur to work perfectly on Nautilus (gnome gui file explorer) and the Settings window, but after upgrading to 22.10, the blur no longer works or is even applied at all to any native Ubuntu applications.

As you can see, both Dash to Panel and my terminal window are blurred perfectly and respond to Blur My Shell settings changes in real time, but the file explorer and settings windows are completely opaque and have no blur effects whatsoever.
![Screenshot from 2023-06-18 13-28-46](https://github.com/aunetx/blur-my-shell/assets/131328638/9948ee8d-1cb4-4839-9430-b6e6a1fb39e1)

I have tried rebooting, uninstalling and rebuilding from source, installing from the Gnome Extensions website, and reloading the Gnome shell through `alt+F2` and `r`. None of those have fixed the issue.

Is there a fix for this? Should I continue upgrading to Ubuntu 23.04 and maybe that will help somehow?

**Comment by nightlyte-dev** [comment]
Nevermind, got it! Just had to copy files from the theme's `gtk-4.0` folder to `~/.config/gtk-4.0`.

**Comment by mrkkr** [comment]
> Nevermind, got it! Just had to copy files from the theme's `gtk-4.0` folder to `~/.config/gtk-4.0`.

Hello @nightlyte-dev  I have same issue now. how you resolve this exactlty?
