### ISSUE TITLE
incompatibility with desktop icons

### ISSUE THREAD

**Issue by dr3mro** [aunetx/blur-my-shell#454]
when using desktop icons extenstions the blur myshell consider them as a window and it keeps the panel opaque even if no window near by , so would you please add feature to exclude windows from opaqing the panel if near by

**Comment by aunetx** [comment]
I tried Desktop Icons NG, and do not have this behaviour... Is is the extension you are using? If so, consider closing this issue in favour of #438

**Comment by aunetx** [comment]
Hello, I just fixed this in last commit. I close this issue, but if it is still appearing after the next release or when you install the extension from github, could you reopen it?
