### ISSUE TITLE
Overview blur does not work sometimes on dual monitors

### ISSUE THREAD

**Issue by Its-Juice** [aunetx/blur-my-shell#457]
Hi. I am on F38 on wayland and sometimes when i press the super key to go into the overview the primary monitor's blur doesn't activate. Here's a ss. I do not know how else to explain it.
![image](https://github.com/aunetx/blur-my-shell/assets/111902390/f9084cd2-adaf-4486-af77-f3016a66af39)

**Comment by lowgos** [comment]
I have the same problem.

**Comment by Its-Juice** [comment]
> 

thanks, it fixed itself. Not the ideal solution tho. I would love a wayland fix.

**Comment by Colon101** [comment]
I have some weird fix 
if you place your monitors in a different angle (the monitor that works is a little higher than the main monitor) so then both will work i have no idea why but it worked for me so in gnome settings just try to change the position of your monitors

**Comment by Its-Juice** [comment]
> 

as i said, while this might fix it, it isn't ideal.

**Comment by slayeh17** [comment]
Yeah, I am having the same issue (also using Fedora 38). Does anyone have any idea what could be causing this issue? That way I might try fixing it.

**Comment by Its-Juice** [comment]
> Yeah, I am having the same issue (also using Fedora 38). Does anyone have any idea what could be causing this issue on wayland? That way I might try fixing it.

I do not think there's a fix for it in wayland yet. I switched to X11 and had zero issues. It isn't the ideal fix but it works.

**Comment by kugelvlitz** [comment]
Same issue here on wayland. Using archlinux

**Comment by Its-Juice** [comment]
UPDATE: I have completely removed the extension since X11 is notoriously bad on multiple displays. Unless there's a fix on this i will not be using it anymore.

**Comment by bzwierz** [comment]
I have the same issue. When I use Super key the blur is working on both displays, it doesn't work when using hot corner.

**Comment by Laminaat** [comment]
I'm experiencing the same issue as OP. Also on F38 and Wayland. Interestingly Super key and moving the mouse to the upper left corner gives me an app drawer without blur but when I click Show Apps it (sometimes) does give me a blurred background in the app drawer.

**Comment by hschmiedhofer** [comment]
Same. Ubuntu 23.04, Wayland, dual monitor setup with 4K display on the left and ThinkPad on the right. Sometimes, Super key is giving me blur on both displays, other times the 4K display background remains black, only the laptop screen on the right gets the colored blur.

**Comment by Ascii67** [comment]
I am having the same issue on Fedora 38 and Wayland

**Comment by Its-Juice** [comment]
UPDATE 2: Nothing has happened with updating the extension.

**Comment by Its-Juice** [comment]
FIX: It's a weird one. Just move the monitors a microscopic bit out of alignment. It should work!

**Comment by stasys-hub** [comment]
I am experiencing the exact same Problem. I am on arch using wayland.

**Comment by aunetx** [comment]
Hello, could you try runnning blur-my-shell from the PR #546? I changed the way multiple monitors are managed so it should be better (maybe, I couldn't test it on multiple monitors hehe)

**Comment by joaocandre** [comment]
Issue still present on Gnome 46 (Wayland) + Archlinux

**Comment by DodoLeDev** [comment]
I found that the alignment of monitors seems to have an effect:

| ![Alignment 2](https://github.com/aunetx/blur-my-shell/assets/59477313/0ed9e477-0fb0-473a-97bb-65eecd8993f2) |  ![Alignment 1](https://github.com/aunetx/blur-my-shell/assets/59477313/2b1eb0f0-ce59-42ba-81ab-4989c2017e22) |
|---|---|
| ![Bottom aligned](https://github.com/aunetx/blur-my-shell/assets/59477313/33c8c2b0-c93e-458b-91a0-5519a37a6978) | ![Bottom overflow](https://github.com/aunetx/blur-my-shell/assets/59477313/fc189f4a-fad4-402f-b3e7-be429e6f2255) |

**Comment by DodoLeDev** [comment]
Moreover, it's buggy with the lockscreen, and only works when the display name is shown :

| Date & time shown | Username shown |
|---|---|
| ![Date & time](https://github.com/aunetx/blur-my-shell/assets/59477313/445fe388-fc4d-4ac3-89da-684b45d403c0) | ![Username](https://github.com/aunetx/blur-my-shell/assets/59477313/f7ca2fd8-f4e0-4a8f-8316-2c6bacbfc243) |

**Comment by joaocandre** [comment]
> I found that the alignment of monitors seems to have an effect:

That seems to be related to [@Colon101](https://github.com/aunetx/blur-my-shell/issues/457#issuecomment-1620057318) workaround? I found it to work at the moment, but forces me to have the display layout in a non-intuitive structure,

**Comment by Its-Juice** [comment]
UPDATE 3:  After a while i just stopped using the extension all together. This bug is way too annoying for me to keep using this extension.

**Comment by aunetx** [comment]
Fixed! @Its-Juice you may want to come back
