### ISSUE TITLE
[Feature Request] Add GNOME 45 Support

### ISSUE THREAD

**Issue by git-Hmmm** [aunetx/blur-my-shell#466]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

resources: [gjs.guide/extensions/upgrading/gnome-shell-45.html](https://gjs.guide/extensions/upgrading/gnome-shell-45.html)

**Comment by aunetx** [comment]
Working on it, there is a LOT of work (see #470).

I can't test gnome 45 for the moment, I'm trying to get a VM to launch...

**Comment by git-Hmmm** [comment]
no worries 👍🏻
thanks for your attention 🙂

**Comment by bennypowers** [comment]
I had success creating a VM with fedora silverblue and rebasing it to fedora 39

**Comment by KUPOinyourWINDOW** [comment]
Just in case its helpful, the RC of Fedora 39 is here and is a GO so it will be on their website on Tuesday
https://www.linuxcompatible.org/story/fedora-linux-39-beta-rc-11-released/
