### ISSUE TITLE
[Feature Request]: Blurring just a part of an app

### ISSUE THREAD

**Issue by Karol739** [aunetx/blur-my-shell#472]
I wonder if it's possible to add a function to blur a part of an application, not a whole one. The effect I want to achieve is marked with red arrow and frame on screenshot 1. Now Blur My Shell supports app blurring, but it blurs the whole window (screenshot 2). 
I suggest adding something like "what-to-blur-chooser", similar to a frame implemented in Gnome Screenshot tool, where you'll be able to choose what in an app you want to blur.
Have a good day!

Screenshot 1 (what may be blurred)
![Zrzut ekranu z 2023-09-21 12-58-33](https://github.com/aunetx/blur-my-shell/assets/65565502/db5db5ea-219f-43fe-a01a-70ec74d0136e)

Screenshot 2 (what Blur My Shell offers to blur now - the whole thing)
![Zrzut ekranu z 2023-09-21 13-03-39](https://github.com/aunetx/blur-my-shell/assets/65565502/baeaf50d-de89-4e40-aec4-45fd1519c487)

**Comment by CorvetteCole** [comment]
This would be extremely complex to do, especially with resizable sidebars and everything else. @aunetx can say for sure, but I'd close as not planned

**Comment by aunetx** [comment]
Yeah, that would sadly not be possible -- gnome-shell does not have access to the application's widgets, let alone blur-my-shell. Applications blurring from blur-my-shell is only a little hack that blurs the entire application actor :) 

So any attempt to have this kind of blurring would need to be done in gtk4 and mutter directly, and I don't know if there are plans for that.
