### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by gaetan1903** [aunetx/blur-my-shell#477]
![image](https://github.com/aunetx/blur-my-shell/assets/43904633/64cbad27-f6f2-4568-8969-eddf5fa416a9)

> OS: Fedora 39
> DE: Gnome 45

**Comment by gaetan1903** [comment]
I've change my OS to Manjaro, 

it's worked

**Comment by TahaCoder43** [comment]
Which gnome version are you using on Manjaro?

**Comment by TahaCoder43** [comment]
This same issue I Have also seen on other gnome extensions like dash to dock and one other that I can't remember, but they got fixed with 
> I had to run `sudo dnf install mutter mutter-devel`

**Comment by gaetan1903** [comment]
> Which gnome version are you using on Manjaro? 

4.45

**Comment by TahaCoder43** [comment]
For anyone facing this issue, this is how I solved it.

1.  run `sudo dnf update` (in case you didn't update the system right after install, or your system is a little outdated)
2.  run `sudo dnf install mutter mutter-devel`
3. restart your computer

**Comment by aunetx** [comment]
Hello, sorry for not replying earlier, to be honest I don't know why `Mtk` is not present by default in some distros (as is was on mine)... I could try to use something else (as I only need it for one particular task), but I don't know of any alternative either
