### ISSUE TITLE
Gnome flagging blur my shell as outdated - Ubuntu 22.04 Gnome 42.9

### ISSUE THREAD

**Issue by kris-rk** [aunetx/blur-my-shell#478]
![Screenshot from 2023-10-06 14-40-43](https://github.com/aunetx/blur-my-shell/assets/104695990/c2f046b7-0bec-42d3-9d47-4c66a4f4c562)

OS: Ubuntu 22.04
Gnome: 42.9

**Comment by aunetx** [comment]
You should not use version 51 (it is only for gnome 45), I guess you installed it from github so use previous version (version 47 is the latest for gnome 42).

Else you can install from extensions.gnome.org which will automatically choose the right version
