### ISSUE TITLE
blur doesn't update back after screen rotation on tablets

### ISSUE THREAD

**Issue by Dziban-dev** [aunetx/blur-my-shell#48]
![Screenshot from 2021-04-23 00-38-37](https://user-images.githubusercontent.com/36001673/115829954-d957d500-a3cc-11eb-8a39-46ab959bfdee.png)

so everything works great after last update, I'm using it on a 2in1 tablet, the blur on the topbar does cover the entire width after going back to landscape mode.

**Comment by aunetx** [comment]
Thanks for the report! I will try to find the appropriate signals so the panel is correctly updated :)

**Comment by aunetx** [comment]
This should maybe (unintentionally) be fixed in last commits (related to #47), feel free to test it :)

**Comment by Dziban-dev** [comment]
> This should maybe (unintentionally) be fixed in last commits (related to #47), feel free to test it :)

nice! let me see.

**Comment by Dziban-dev** [comment]
I'm closing this topic because issue has been resolved

**Comment by aunetx** [comment]
Cool, glad it worked :)
