### ISSUE TITLE
Invalid null pointer instance

### ISSUE THREAD

**Issue by AM-ash-OR-AM-I** [aunetx/blur-my-shell#485]
## Bug
While switching workspace with blur my shell on it works as expected but i get following logs in `journalctl -f` is there something wrong with it?
```
Oct 29 10:45:19 fedora gnome-shell[2186]: invalid (NULL) pointer instance
Oct 29 10:45:19 fedora gnome-shell[2186]: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 29 10:45:19 fedora gnome-shell[2186]: invalid (NULL) pointer instance
Oct 29 10:45:19 fedora gnome-shell[2186]: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
## Hardware Information:
- **Hardware Model:**                              HP HP Laptop 14s-dk0xxx
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 3500U with Radeon™ Vega Mobile Gfx × 8
- **Graphics:**                                    AMD Radeon™ Vega 8 Graphics
- **Disk Capacity:**                               1.3 TB

## Software Information:
- **Firmware Version:**                            F.64
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.0
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.6-300.fc39.x86_64

### BlurMyShell Version:
- 52

**Comment by aunetx** [comment]
Do you use noise/colour effects?

If so, yes, there is something wrong with it due to my poor implementation, but to be honest I could not find a better way to do it... I guess this will need to stay as it until the cogl pipeline bug is fixed in gnome-shell/mutter, as this is due to a hack I did in order not to eat all the ram on your machine :)

**Comment by asegarra** [comment]
I'm getting this as well, I unchecked 'Color and noise effects' but still get these errors. In my case just entering overview also gets these messages.

**Comment by AM-ash-OR-AM-I** [comment]
Thanks @aunetx for the response, also @asegarra I can confirm the same issue while entering overview. However it doesn't seem to have any noticeable impact on performance.

**Comment by jgdub** [comment]
Yep getting the same on mine. No issue with with stability but there is a lot of noise in the journal when troubleshooting other items.

Jan 29 21:33:49 larch-01 gnome-shell[1826]: invalid (NULL) pointer instance
Jan 29 21:33:49 larch-01 gnome-shell[1826]: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Jan 29 21:33:49 arch-01 gnome-shell[1826]: invalid (NULL) pointer instance
Jan 29 21:33:49 arch-01 gnome-shell[1826]: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Jan 29 21:33:50 arch-01 gnome-shell[1826]: invalid (NULL) pointer instance
Jan 29 21:33:50 arch-01 gnome-shell[1826]: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Jan 29 21:33:50 arch-01 gnome-shell[1826]: invalid (NULL) pointer instance
Jan 29 21:33:50 arch-01 gnome-shell[1826]: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

**Comment by aunetx** [comment]
Hello, #546 should fix this (or at least it fixed this for me)! Please reopen the issue if it still appears after the PR is merged
