### ISSUE TITLE
is blur my shell not available for gnome 42.9? 

### ISSUE THREAD

**Issue by nonresidentaliennico** [aunetx/blur-my-shell#487]
hey. i have gnome 42.9 and i managed to download the extension using git clone but when i go to extension manager it says it's incompatible with my current version of gnome. is this normal? or is something up with my gnome?

**Comment by aunetx** [comment]
Hello, sorry for the problem, I forgot to update the readme! You can use version 47, which is the last release that is compatible with gnome 44
