### ISSUE TITLE
blur-my-shell attempts to remove "" empty string class which is possibly leading to gnome-shell crash.

### ISSUE THREAD

**Issue by toppk** [aunetx/blur-my-shell#488]
As per this commit:

https://github.com/aunetx/blur-my-shell/commit/3d488b47322dbe62456f305885a49f6d6743b8a0

empty string "" is added to the list of styles that will get removed:

https://github.com/aunetx/blur-my-shell/blob/master/src/components/appfolders.js#L12

Removal code here:

https://github.com/aunetx/blur-my-shell/blob/master/src/components/appfolders.js#L177

It is suspected that this leads to corruption of the class list, and eventually if unlucky, a shell crash.  

Upstream is considering a patch to just ignore attempts to remove empty string "" classes:

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3006

some reports that hint this is an issue:

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7152
https://github.com/aunetx/blur-my-shell/issues/445

**Comment by aunetx** [comment]
Thank you very much for this summary! I will remove this right now, and push this to eog very soon (possibly tonight)

**Comment by aunetx** [comment]
I just fixed this in last commit! Now no empty strings shall ever be removed :) I will publish the release right now

**Comment by toppk** [comment]
here's the other location:

https://github.com/aunetx/blur-my-shell/blob/f479cb6ade4b91533926947eb132ff28bc62a3e5/src/components/overview.js#L9

**Comment by aunetx** [comment]
I'm sorry, I did not even look at other parts of the code, I will try to fix this tomorrow... Thank you so much!

**Comment by toppk** [comment]
Thanks.  Also, do you know how I can exercise this codepath (specifically the remove class) . I'm trying to trigger this under gdb so I can get the js_stacktrack and confirm it all.    Oddly I'm not doing anything in particular when the crash happens, so it seems all random to me.

**Comment by aunetx** [comment]
I don't really know, to be honest; and that's quite an issue... The background blur is updated quite often, everytime a gsetting changes for the wallpaper in gnome; so that might happen when you change workspace, when you open the overview, ... but to trigger it surely, you will need to either disable/reenable background blur, or change the overview components style in preferences.

I'm sorry, I could not do the required changes, I will try today but I'm not sure I can access my computer either

**Comment by aunetx** [comment]
Finally I fixed this, sorry for the delay. I will push this to eog after I find some issues to fix
