### ISSUE TITLE
option to disable panel blur 

### ISSUE THREAD

**Issue by kerrongordon** [aunetx/blur-my-shell#5]
option to have overview blur only the panel sims to be a bit too buggy at the moment

**Comment by aunetx** [comment]
I will try to add this, thanks for the suggestion

It should take me some time sorry, i don't have much time to do this...

**Comment by aunetx** [comment]
I added options for a lot of things, including panel blur disabling :)
(btw, the panel should be a lot less buggy if you select the right configuration, at the expense of CPU time)
