### ISSUE TITLE
Application Blur not working correctly

### ISSUE THREAD

**Issue by Ronak0020** [aunetx/blur-my-shell#505]
Hi!
I have been using blur my shell for a few days and I have noticed these 2 issues:
- Application blur doesn't work if the application is "windowed" [is not full screen/maximized]
- On full screen, the blur works but if I have any other application in background, which I did not minimize and is below my current window, the "outline" of the window keeps blinking on my current window which is quite irritating.

I tried to record a view for the second issue but after I completed recording it, I noticed that it is not visible in the video. In video, it seems to have no issue if I have any application in the background of my current window.

## Issue 1 Screenshots
Screenshot for the blur not working on windows that are not full screen:
![image](https://github.com/aunetx/blur-my-shell/assets/49647021/d1e6b53a-038b-4e9c-8c3d-bcc1d19c79c6)

Window when they are full screen:
![image](https://github.com/aunetx/blur-my-shell/assets/49647021/2e57c7dd-9dda-449a-bc79-d0d056beea98)

## Issue 2
For the 2nd issue, this is not exactly what happens but something similar to this [this is just a "demo" ss to show how the background window is visible/is blinking on my current window]
The "white" square is how they are visible, with shadows on the borders [basically, window shadows that all the windows have at the edges]
![image](https://github.com/aunetx/blur-my-shell/assets/49647021/36394c53-882f-4105-a4e2-1f068c65b3b5)
This blinks if I am moving my cursor/there is motion on the screen. And if there is no motion, they are either not visible or they are visible for a brief moment and return back the moment there is any motion on the screen.

## My system:
OS: **Fedora Linux 39 (Workstation Edition)**
Windowing System: **Wayland**
**Gnome Version: 45.2**
App Blur Settings:
![image](https://github.com/aunetx/blur-my-shell/assets/49647021/1a3e23b4-71e5-4eb7-897e-d0431dd5f666)
I have also set "Hack Level"  to "No Artifact"

**Comment by Ronak0020** [comment]
https://github.com/aunetx/blur-my-shell/assets/49647021/cf6c543b-2db4-4c94-bb11-a391e80cb95c

Here. Just recorded the 2nd issue using smartphone.
It happens when screen is idle as well just like this one:
![IMG20231204145133](https://github.com/aunetx/blur-my-shell/assets/49647021/3938e249-e106-4d47-8631-f34877c7b56e)
![IMG20231204145157](https://github.com/aunetx/blur-my-shell/assets/49647021/3159b02b-bbf7-4348-b247-696064968bad)

**Comment by extrange** [comment]
Not sure if similar but I see something like this:

![image](https://github.com/aunetx/blur-my-shell/assets/29305375/fb75ca51-49b0-4594-8b62-c4c3908dfdf0)

OS: NixOS 24.05 (Uakari)
Windowing System: Wayland
Gnome Version: 45.1
App Blur Settings: Enable all by default

**Comment by SVTA-OP** [comment]
Are you using the rounded corners extension? If yes, application blur works, but the BLUR part doesn't work.

**Comment by Ronak0020** [comment]
Actually, yes. I forgot to post here, the Rounded Corners extension is the one messing with the application blur. turning it off makes the application blur work perfectly fine.
