### ISSUE TITLE
not working on muiti-monitor

### ISSUE THREAD

**Issue by daachild** [aunetx/blur-my-shell#514]
Blur My shell seems to be stop working after i plug a second monitor in and even after i back to one monitor it won't work.
Turn on and off ỏ even re-install won't fix the issue.

**Comment by aunetx** [comment]
Hello, could you try runnning blur-my-shell from the PR #546? I changed the way multiple monitors are managed so it should be better (maybe, I couldn't test it on multiple monitors hehe)
