### ISSUE TITLE
GNOME Panel breaks (in half) on Login.

### ISSUE THREAD

**Issue by zenospeed** [aunetx/blur-my-shell#517]
![image](https://github.com/aunetx/blur-my-shell/assets/75566449/e981d170-cdd4-4375-b917-2ab96c1eb8b5)

Everytime I log into my user account, and press the Super key after the Workspace overview shows, the Top Panel blur literally seems to break itself in half. The only way to fix it, as far as I know, is to go into the Extension Settings, and retoggling the 'Panel blur' option off and on.

This project is excellent and I don't want to give up on it, so I'd like to see if anyone else has this issue and whether or not it can be solved. :)

**Comment by dmaglio** [comment]
same issue for me in Fedora 39

**Comment by RyzenDew** [comment]
this happens on arch linux and Fedora 38/39/40 also and ubuntu

**Comment by aunetx** [comment]
Hello, could you try runnning blur-my-shell from the PR #546? I changed the way multiple monitors are managed so it should be better (maybe, I couldn't test it on multiple monitors hehe)

**Comment by ryzendew** [comment]
> Hello, could you try runnning blur-my-shell from the PR #546? I changed the way multiple monitors are managed so it should be better (maybe, I couldn't test it on multiple monitors hehe)

it happens again

**Comment by aruraune** [comment]
I'm not sure if this helps but this issue only seems to happen when my left/secondary monitor is at 0,0 position. Changing my left/secondary monitor to 0,1 prevents this solid background.

If this is happening with only one monitor or the left monitor being the primary display, it could be a similar situation where the first monitor being at x: 0, y: 0 triggers the behaviour.

**Comment by jarek102** [comment]
With recent update, on/off doesn't fix issue

**Comment by aunetx** [comment]
I found the problem, I don't know precisely how to adress it right now but that should be done in a couple of days I guess!

**Comment by aunetx** [comment]
Hello @zenospeed, the bug should be resolved in last commits in the `master` branch, could you try it to tell me if everything works well?

**Comment by aunetx** [comment]
Fixed now!
