### ISSUE TITLE
Gnome shell crash SIGSEGV - st_theme_node_lookup_shadow

### ISSUE THREAD

**Issue by V-Mann-Nick** [aunetx/blur-my-shell#524]
## Description

I have issues with the entire Gnome shell crashing to GDM, loosing the session and having to login again. I've tracked down the issue to this extension. In particular the application blur. 

## Reproduction

I can consistently reproduce the issue with all extensions disabled except for this one and doing the following:

- Have a full screen Youtube video finish in Firefox
- Wait for suspend (I set `org.gnome.settings-daemon.plugins.power.sleep-inactive-battery-timeout` in dconf to something low for quicker testing)
- When I wake the Computer the Shell has crashed

## Context

- Kernel: Linux 6.7.0-zen3,
- Distro:  NixOS, 23.11 (Tapir), 23.11.20240124.a77ab16
- Blur my shell version: 54
- Gnome shell: 45.3

## Logs & Traces

[coredump.txt](https://github.com/aunetx/blur-my-shell/files/14070464/coredump.txt)
[gdb.txt](https://github.com/aunetx/blur-my-shell/files/14070465/gdb.txt)
[blur-logs.txt](https://github.com/aunetx/blur-my-shell/files/14070480/blur-logs.txt)

---

Thanks a lot for the great extension. I'm really liking it.

**Comment by neuromorph** [comment]
Some inputs for you and aunetx:
This seems like some issue with Gnome shell. It leads to Gnome crashing and restarting as you reported. 
To reproduce, you need any application in full-screen and then you can use Ctrl+L to lock the screen. Locking on full-screen will trigger it.
I am seeing this to happen with extensions that style the Top panel in some way. So it seems like a Gnome issue. Though it would be prudent for the extensions to provide some workaround, if possible.

For the current case, can you please try disabling any Panel color/style overrides in Blur my shell preferences? That might prevent the crash (of course at the cost of losing the style).

**Comment by voidanix** [comment]
I am having this issue since GNOME 46 (on Fedora).

There is no need to have open applications to trigger this: by Ctrl+L, you can crash the shell from the app drawer or overview.

Disabling styling for the panel did not help. Both version 59 and master have the same behavior.

**Comment by voidanix** [comment]
Could you guys try https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252 ? The issue seems to be gone w/ this patch applied.

**Comment by neuromorph** [comment]
Well, Open Bar had this issue (in fullscreen) and I was thus using a workaround to avoid crash. However, for the past week or so, on an updated system with Gnome 42 (or 45), the issue could not be reproduced. So, I assumed it is fixed upstream. Not tested on 46 but expect to be same.
From what I gather, the crash on locking screen related issues were raised and closed earlier too in shell/mutter. But it can have many different causes resulting in the multiple issues. 
Maybe, someone who is still facing the issue can try with the patch you mentioned as it does seem relevant. If it helps in your case, you can add a comment on the merge request as well, with the details.

**Comment by V-Mann-Nick** [comment]
Really sorry for the late response. But weirdly enough the issue hasn't appeared again in a long time. I can't say what exactly made the difference. I also haven't applied the patch you noted. Not sure 🤷‍♂️. Closing this issue.

**Comment by Nakamerica** [comment]
For people in the future who stumble upon this issue but may not have blur-my-shell installed: this crash can also be caused by (in my case) dash to dock. It seems like the only viable solutions are to either disable the extension or build mutter with that patch include.d

**Comment by neuromorph** [comment]
> For people in the future who stumble upon this issue but may not have blur-my-shell installed: this crash can also be caused by (in my case) dash to dock.

This is true! This can happen with any extension that styles a desktop element with a stylesheet. Gnome disables the extensions on lock/logout and at that point the extension stylesheets are unloaded. Due to a bug in Gnome/Mutter, some nodes are left pointing to the old references in memory causing a seg-fault crash. Ubuntu has applied the said patch but not Gnome. It seems a better* solution to reset cache is needed but the issue may not be getting priority. If someone is facing it, raising an issue in Gnome Gitlab, linking to the patch, may be a good idea.
