### ISSUE TITLE
Configure from script/CLI?

### ISSUE THREAD

**Issue by NeoMatrixJR** [aunetx/blur-my-shell#527]
I've been working to automate my setup.  I've been getting most of my gnome config set via `gsettings set org.gnome.shell.extensions.whatever setting value`  When I try that with blur-my-shell I just get "No such schema "org.gnome.shell.extensions.blur-my-shell"

Is there any way to config this from a script/CLI?  I haven't been able to find anything so far.

**Comment by aunetx** [comment]
Yes there is! I'm sorry I can't find it right now (I don't have my computer with me) but if I did not answer by tonight, please ping me so I give you the command

**Comment by NeoMatrixJR** [comment]
I found it.  I needed to use this style instead: `dconf write /org/gnome/shell/extensions/blur-my-shell/panel/customize true`  Not sure why this works but gsettings doesn't....but this works as long as I log out/back in when done.
