### ISSUE TITLE
Broken application blur on Wayland if fractional scaling is off

### ISSUE THREAD

**Issue by FelixFourcolor** [aunetx/blur-my-shell#528]
~~v55, when fractional scaling is off, unfocused windows are incorrectly blurred~~

~~The window on the left is focused. On the unfocused windows, the entire thing is blurred instead of only the background.~~ 
(See EDIT below.)

![Screenshot from 2024-02-19 02-11-08](https://github.com/aunetx/blur-my-shell/assets/34260584/cd6ea893-403f-43ce-bfbd-ba124e0ff2ff)

I think commit e2426578f5651dce33616cb3ba22e4339f199cc7 is the culprit, because when I revert it the problem disappears. But the commit fixes #362. So basically the situation is:

|| With e2426578f5651dce33616cb3ba22e4339f199cc7  | Without e2426578f5651dce33616cb3ba22e4339f199cc7 |
|- | ------------- | ------------- |
| Fractional scaling on | working  | broken (#362) |
| Fractional scaling off | broken (this issue) | working |

----------------
EDIT: I had an incorrect understanding of the issue (thanks to @alesya-h for pointing it out). It's not inherently about blurring of unfocused windows, but about the size and placement of the blur box. This screenshot shows it more clearly.
![Screenshot from 2024-02-20 17-05-24](https://github.com/aunetx/blur-my-shell/assets/34260584/fd1d70f2-7a4d-46ea-85e4-feb6505f0085)

If there are multiple windows on-screen, the unfocused ones will be put behind the blur box of the focused window, thus it looks like unfocused windows are incorrectly blurred.
![Screenshot from 2024-02-20 17-05-58](https://github.com/aunetx/blur-my-shell/assets/34260584/ea5443a8-3ce5-4568-8542-f9a7243753ea)

**Comment by aunetx** [comment]
Thanks for the testing, so I'm not alone with this issue!

I will try to find a variable to know whether or not the user uses fractional scaling, and change the behaviour accordingly. That's a shame though that it is so hard to get right...

**Comment by FelixFourcolor** [comment]
Is it better to revert the commit for the time being until a solution is found? After all, fractional scaling is an experimental feature, it's better to break it than to break the default.

**Comment by alesya-h** [comment]
@aunetx I just checked and if "scale-monitor-framebuffer" experimental feature is turned off the size of blur actors is double the size of what it should be. Presumably that's what it should have branched on. On the screenshot I assume that's also what happened - the blur actor from the left window extended to the right one over the right terminal and the background between terminals on the screenshot is also blurred. So this bug I assume is incorrect, it has nothing to do with blurring unfocused windows, probably just looked that way because of tiling

**Comment by FelixFourcolor** [comment]
@alesya-h 

> So this bug I assume is incorrect, it has nothing to do with blurring unfocused windows, probably just looked that way because of tiling.

I agree. I will edit the title accordingly.

**Comment by aunetx** [comment]
Hello, does #534 works for you? It should check if the experimental feature is enabled before using the scaling divisor!

**Comment by alesya-h** [comment]
Works well for me, both with and without scale-monitor-framebuffers. I didn't test x11 apps though, would be good if someone else checks it

**Comment by FelixFourcolor** [comment]
I checked both on x11 session and wayland session; the latter both with native wayland and xwayland apps, with and without scale-monitor-framebuggers. Everything works.

(Other than what I assume is a missing import, as I wrote in the #534 discussion. I had to add a line `import Gio from 'gi://Gio'` in `src/components/applications.js` otherwise the extension wouldn't run.)
