### ISSUE TITLE
Panel bottom in the center of the screen with multiple monitors

### ISSUE THREAD

**Issue by swyknox** [aunetx/blur-my-shell#53]
![2021-04-26_14-25](https://user-images.githubusercontent.com/52772425/116125042-69cb3980-a69b-11eb-8631-ecd7257876f3.png)

For some reason, when I connect my second monitor, the bottom of the panel is in the center of the screen (or almost so).
My primary monitor has a resolution of 1366x768 and the secondary 1920x1080.
When I set my primary monitor to 1920x1080 the panel is not centered, but it is not [blurred](https://iili.io/BFED6F.png).

_I apologize for my terrible English_

**Comment by CorvetteCole** [comment]
this might be related to #47 , @aunetx is the expert here so I'll let them take a look at this

**Comment by aunetx** [comment]
Yeah, I need to test multi-monitor support a lot more than what I did... Sorry for the inconvenience :/

**Comment by swyknox** [comment]
Okay, if you have any way to help, I'm here! 😁

**Comment by swyknox** [comment]
I just installed update 13 and it looks like the panel bug is gone. 😄
![Captura de tela de 2021-05-26 18-59-54](https://user-images.githubusercontent.com/52772425/119739310-68d32680-be58-11eb-9a08-2625cd8b65aa.png)

**Comment by aunetx** [comment]
Cool! Sorry not to have tried to solve your problem, but this was unexpectedly fixed :)
