### ISSUE TITLE
Not working on gnome 46

### ISSUE THREAD

**Issue by Neo-29** [aunetx/blur-my-shell#547]
The extension is on but none of the settings can be applied> no result 

Archlinux gnome 46.0 wayland

**Comment by AndusDEV** [comment]
+1

**Comment by khaitranhq** [comment]
+1

**Comment by Hydranet** [comment]
They are already working on it in another issue.
https://github.com/aunetx/blur-my-shell/issues/532

**Comment by tux-wclp** [comment]
On Arch (use Endeavour OS who uses Arch repositories) does not work at all: it does not start !!!
I updated my OS and went from Gnome 45 to Gnome 46: upon restarting the system, the extension does not start.
Can you implement support for Gnome 46?

**Comment by AndusDEV** [comment]
> Hello, support for GNOME 46 has not landed yet because I use Fedora and version 40 beta is not out yet, so it will need to wait some more days!
> 
> There is an open PR for this, but it lacks support for the new style added in GNOME 46 yet. If you want to add it, don't hesitate to participate, else I will of course do it as soon as possible :)

Maybe you could develop extensions on GNOME's distro (a VM for example) and daily drive Fedora? You would get latest GNOME the same day it releases (at least as far as I remember), and the updates would come out faster. And you don't need to repair Fedora if anything goes wrong for some reason

**Comment by kaushiksahu18** [comment]
> On Arch (use Endeavour OS who uses Arch repositories) does not work at all: it does not start !!!
> I updated my OS and went from Gnome 45 to Gnome 46: upon restarting the system, the extension does not start.

yes, same.
there are many extension not working and one of them is **"blur my shell"**

![Screenshot from 2024-03-25 00-20-51](https://github.com/aunetx/blur-my-shell/assets/113049724/46b74542-6954-4e31-b9b3-d440da7b6171)

**Comment by Neo-29** [comment]
> > On Arch (use Endeavour OS who uses Arch repositories) does not work at all: it does not start !!!
> > I updated my OS and went from Gnome 45 to Gnome 46: upon restarting the system, the extension does not start.
> 
> yes, same. there are many extension not working and one of them is **"blur my shell"**
> 
> ![Screenshot from 2024-03-25 00-20-51](https://private-user-images.githubusercontent.com/113049724/316333745-46b74542-6954-4e31-b9b3-d440da7b6171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDcxMzQsIm5iZiI6MTcxMTMwNjgzNCwicGF0aCI6Ii8xMTMwNDk3MjQvMzE2MzMzNzQ1LTQ2Yjc0NTQyLTY5NTQtNGUzMS1iOWIzLWQ0NDBkYTdiNjE3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxOTAwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjI3ODdjMTFhMDIwY2MxMGM5MzkwMjcyYjkxMmUwNzNiYWY2Mzc3NzJjZTI1NDEzYTYyZjFiNDAyMDNmNTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yK5dwBQxpaWl4I_ZqNFGS51eaujd-thC-FVi34TsXsc)

It's not on the subject but...
For dash to dock you can build it from source.
It works smoothly

**Comment by aunetx** [comment]
> > Hello, support for GNOME 46 has not landed yet because I use Fedora and version 40 beta is not out yet, so it will need to wait some more days!
> > 
> > There is an open PR for this, but it lacks support for the new style added in GNOME 46 yet. If you want to add it, don't hesitate to participate, else I will of course do it as soon as possible :)
> 
> Maybe you could develop extensions on GNOME's distro (a VM for example) and daily drive Fedora? You would get latest GNOME the same day it releases (at least as far as I remember), and the updates would come out faster. And you don't need to repair Fedora if anything goes wrong for some reason

I tried to do it, unfortunately I don't have a powerful enough PC to make this development workflow smooth enough to be confortable.

Of course everything is technically possible, but I develop this extension on my free time so the "funny" part of development really is what permits this extension to grow little by little! And testing everything in a VM would entirely remove this, which is unfortunate. So, I try to provide updates as fast a possible when it is needed, but that could still mean some days of latency after a new version!

**Comment by AndusDEV** [comment]
> > > Hello, support for GNOME 46 has not landed yet because I use Fedora and version 40 beta is not out yet, so it will need to wait some more days!
> > > 
> > > There is an open PR for this, but it lacks support for the new style added in GNOME 46 yet. If you want to add it, don't hesitate to participate, else I will of course do it as soon as possible :)
> > 
> > Maybe you could develop extensions on GNOME's distro (a VM for example) and daily drive Fedora? You would get latest GNOME the same day it releases (at least as far as I remember), and the updates would come out faster. And you don't need to repair Fedora if anything goes wrong for some reason
> 
> I tried to do it, unfortunately I don't have a powerful enough PC to make this development workflow smooth enough to be confortable.
> 
> Of course everything is technically possible, but I develop this extension on my free time so the "funny" part of development really is what permits this extension to grow little by little! And testing everything in a VM would entirely remove this, which is unfortunate. So, I try to provide updates as fast a possible when it is needed, but that could still mean some days of latency after a new version!

That's a bummer. Atleast Blur My Shell is a purely visual extension and doesn't add anything that dramatically changes the Shells features for example dash to panel/dock or GSconnect.

You know, you can live a couple days without a blur, but dash extensions change the experience drastically so it's hard to live without them.

Glad you're having fun when developing things though! Half of my projects ended just because it wasn't fun.

**Comment by EisregenHaha** [comment]
> Hello, support for GNOME 46 has not landed yet because I use Fedora and version 40 beta is not out yet, so it will need to wait some more days!
> 
> There is an open PR for this, but it lacks support for the new style added in GNOME 46 yet. If you want to add it, don't hesitate to participate, else I will of course do it as soon as possible :)

just as a hint, you can already upgrade to the 40 release even though it aint "officially" released the beta yet, i did the same. it will cause no problems most likely as it was supposed to be released anyway and the blockers for the release were mainly just arm issues, so if you run a normal pc it will be fine im very sure. 

sudo dnf system-upgrade download --releasever=40

**Comment by aunetx** [comment]
Hello everyone, could you please test the master branch before I publish the extension? Thanks a lot!

**Comment by aunetx** [comment]
Version 59 uploaded, should be reviewed soon :)

**Comment by EisregenHaha** [comment]
> Hello everyone, could you please test the master branch before I publish the extension? Thanks a lot!

works fine for me, thanks for the update

**Comment by Neo-29** [comment]
No transparency on app icons in overview.
