### ISSUE TITLE
Every time i unlock the extension crashes

### ISSUE THREAD

**Issue by JoaquimCarneiro** [aunetx/blur-my-shell#55]
As the title says, every time i unlock the screen the extension crashes and the extension manger reports the error: "actor is null". I have to refresh the shell to re-enable the extension.
I'm using Arch Linux, Gnome 40 and not using Wayland.
log | grep "blur-my-shell":

[log.txt](https://github.com/aunetx/blur-my-shell/files/6384894/log.txt)

It's possible that this is a duplicate of Extension bug "actor is null" with a different theme #51

**Comment by aunetx** [comment]
Ok, I guess I understand where it comes from (nearly the same as #51 effectively...)

Fixing the crash is easy, but I don't know which effects it will have on the extension... I mean, it would mean that some parts of the dash would not be correctly updated, so it may create even more artefacts
So I will fix that crash, but the bug in itself still will not be :)

**Comment by aunetx** [comment]
Btw, are you using a different theme, or an extension which modify the dash, other than dash-to-dock?

**Comment by JoaquimCarneiro** [comment]
Sorry if i caused any trouble. I'm using dash to dock and I'm using Matcha theme. Can this be caused by the theme?

**Comment by JoaquimCarneiro** [comment]
Strangely after disabling all extensions, one by one, enabling blur-my-shell and then enabling all other extensions, the issue goes away. I do not understand why... And I was able to replicate this in another machine.

**Comment by aunetx** [comment]
That's weird... Which extensions do you have?

**Comment by JoaquimCarneiro** [comment]
just did the same with a 3th computer...
extensions:
Just Perfection
Tray Icons: reloaded
User Themes
Vitals
Dash to Dock (69+443+ga2d40e2-1)
Blur my shell

**Comment by aunetx** [comment]
Should be fixed in last commit, although I don't know why the bug happened... Please reopen if still not working :)
