### ISSUE TITLE
Feature Request: blur divison of workspaces

### ISSUE THREAD

**Issue by Dziban-dev** [aunetx/blur-my-shell#56]
![2021-04-27_08-54](https://user-images.githubusercontent.com/36001673/116263009-41dce400-a736-11eb-9cca-bcf2ebcaffef.png)

it would be be neat to show the blur background when sliding through workspaces,

**Comment by CorvetteCole** [comment]
If you have the static blur checkbox turned off, this should do what you desire. Can you confirm that?

**Comment by saaditory** [comment]
> If you have the static blur checkbox turned off, this should do what you desire. Can you confirm that?

`Static panel blur` just moves the blurred version of the gray area through panel along with workspaces. But the request here is that to **make that separator(gray area) between workspaces transparent/blur**.

**Comment by CorvetteCole** [comment]
Wow, I see what you mean now. I hardly even see that. Well maybe @aunetx would have some ideas about this. I have no idea what part of the shell that is

**Comment by aunetx** [comment]
I really don't know how to change this, but will try to find this :)

However, I don't really know if it would be a good idea to do this... I mean, what should we blur behind it? Should it be a blurred version of the wallpaper, but then which part? It we are changing workspace, then the wallpaper is not static, and I don't know how it would visually look like...

**Comment by CorvetteCole** [comment]
I personally think this should be a very low priority since it is just a gray part. Also not sure what would put there as well

**Comment by Dziban-dev** [comment]
> I really don't know how to change this, but will try to find this :)
> 
> However, I don't really know if it would be a good idea to do this... I mean, what should we blur behind it? Should it be a blurred version of the wallpaper, but then which part? It we are changing workspace, then the wallpaper is not static, and I don't know how it would visually look like...
Well yeah i figured it would be complecated, my idea is just being able to see the blurbackground , so it would look like paralax when workspaces move over it. i mean the blur background would be static , and workpaces are just moving over it. kind of like they do in the overview but fullscreen.

**Comment by Dziban-dev** [comment]
> I personally think this should be a very low priority since it is just a gray part. Also not sure what would put there as well
yeah probably is not even possible to do.

**Comment by CorvetteCole** [comment]
@Dziban-dev did you delete a comment here? I can't see it posted but got an email regarding it. Not a terrible idea, parallax

**Comment by tommytran732** [comment]
> I really don't know how to change this, but will try to find this :)
> 
> However, I don't really know if it would be a good idea to do this... I mean, what should we blur behind it? Should it be a blurred version of the wallpaper, but then which part? It we are changing workspace, then the wallpaper is not static, and I don't know how it would visually look like...

Maybe you can just calculate the average color of the wallpaper and set that area to thaat color?

**Comment by aunetx** [comment]
I honestly now really would like to include this, with the blurred wallpaper behind... But I still don't have any idea how to access it :(

Will ask gnome devs soon, they surely have an idea where these widgets are

**Comment by aunetx** [comment]
Fixed thanks to @Schneegans :)
