### ISSUE TITLE
Blur effect randomly disables when clicking "Show Apps" button

### ISSUE THREAD

**Issue by pocoraven** [aunetx/blur-my-shell#566]
### Hardware
Dell Latitude E5470
### Software
Fedora Linux 39 with GNOME 45.5

### Description
When using the extension [Dash to Dock](https://micheleg.github.io/dash-to-dock/) and clicking on its Show Apps button, the blur effect has a 50/50 chance of either applying or not.

Pressing `Super` twice does not trigger this bug.

**The bug only occurs when multiple monitors are connected.** 

https://github.com/aunetx/blur-my-shell/assets/139316717/1baa81e5-fc0a-413b-8769-c0c8211bb4e4

**Comment by gaussandhisgun** [comment]
can confirm, happens on arch with gnome 46

**Comment by ChrisLauinger77** [comment]
I noticed the same:
I have 2 screen setup.
1 with the gnome top bar and dash and the 2nd.
It always works on the 2nd screen.
On the 1st it works randomly.
There are 4 ways to open the overview / apps menu.
1. Hotcorner top left
2. Click on the icon top left
3. Super button 
4. Icon in dash

I use all of the 4 ways and you can see sometimes I get the blur and sometimes not.

https://github.com/aunetx/blur-my-shell/assets/3518684/d9cfc638-1939-4932-85ee-dd71e39a5cfd

**Comment by amir-reza-bijandi** [comment]
> I noticed the same: I have 2 screen setup. 1 with the gnome top bar and dash and the 2nd. It always works on the 2nd screen. On the 1st it works randomly. There are 4 ways to open the overview / apps menu.
> 
> 1. Hotcorner top left
> 2. Click on the icon top left
> 3. Super button
> 4. Icon in dash
> 
> I use all of the 4 ways and you can see sometimes I get the blur and sometimes not.
> 
>  Bildschirmaufzeichnung.vom.2024-04-25.19-48-27.mp4 
> List of extensions: ![Bildschirmfoto vom 2024-04-25 19-54-47](https://private-user-images.githubusercontent.com/3518684/325719757-03ce7443-b656-4e8a-a8ab-0a2efadd0c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwOTIsIm5iZiI6MTcxNDQxMDc5MiwicGF0aCI6Ii8zNTE4Njg0LzMyNTcxOTc1Ny0wM2NlNzQ0My1iNjU2LTRlOGEtYThhYi0wYTJlZmFkZDBjOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTcxMzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZhMjZhNTk1ZTZlNjc0ZmFmMjk2NTkzNGE2YzE2MTlmMGQ2ZmI2YTQ5MmU3ZWJhNzhlMGI2MGUwM2E4MjZhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PKFbIW0J1mZKqxMiJuB7wPjjtGDvc9ocsoP-Ra3M9ro)

I also have 2 screens and it's happening to me as well!

**Comment by Alex24768** [comment]
So, is there a solution to this issue?

I have not a quite the same problem, but it seems, if this issue of yours is fixed, it might fix mine.}

My problem, is that after booting, the blur effect works but, after some time, the effect start to adjust to the window. Like, blocks of glass effect trying to adjust the effect all of the place of the window.

**Comment by gaussandhisgun** [comment]
also happens with https://extensions.gnome.org/extension/5928/logo-activities/ - might be something in the way extensions invoke overview that isn't getting hooked by BMS in time
