### ISSUE TITLE
Overview layout slightly off when extension used with `Hide Top Bar`

### ISSUE THREAD

**Issue by foundObjects** [aunetx/blur-my-shell#58]
The overview layout is initially incorrect when blur-my-shell is used in combination with the hidetopbar extension and "jumps" jarringly to the correct layout when mousing over a window or switching workspaces.

Not a showstopper or anything but it's definitely annoying and can make it hard to quickly mouse to a window because the target moves slightly while you're selecting it.

Reproduction:

* with blur-my-shell installed and active install https://extensions.gnome.org/extension/545/hide-top-bar/ and enable
* Open the overview
* Move the mouse over a window or switch to any other workspace
* The layout should jump to include the top bar above the search box.

edit:

Sorry, I should clarify -- this only happens when the top bar is collapsed at the desktop. If the top bar is displayed normally everything's fine when you open the overview.

**Comment by aunetx** [comment]
Thanks for the report :)

I initially used this extension with 3.38, but it still does not seem seem stable for gnome 40... Is it really support yet?
I will try to test it, but that's a clear bug from Blur my Shell!

**Comment by foundObjects** [comment]
Thanks for looking into it!

I'm running Gnome 40 after upgrading from 3.38; I think the configuration screen for hidetopbar is still busted on 40 but it functions normally otherwise and hasn't stopped working. I guess you could say it's "compatible" with 40 if "compatible" means "works but the configuration UI is broken."

You can manually configure the extension by directly editing its dconf keys as a workaround, I can post mine if you're also on 40 and it'd be helpful (they live under `/org/gnome/shell/extensions/hidetopbar/`.) I use `dconf-editor` for things like this, it makes life easier.

Give me a shout if there's anything I can do or test; I'm happy to help.

**Comment by aunetx** [comment]
Sorry for the delay :/

I just tested this extension (it's now stable for gnome 40), but did not see the issue... The overview layout effectively 'jumps' to include the topbar when entering overview, but even without Blur my Shell right?
Or else, could you send me a screen record of the issue?

BTW, are you using 'static-blur' option or without it? It definitively looks much better with it enable, but I initially created this extension to have dynamic blur with Hide my Topbar so that would be sad not to entirely support it now...

**Comment by foundObjects** [comment]
I think you're right, it seems like this is happening even when blur-my-shell is disabled. I guess I only started really noticing the behavior at the same time I installed your extension, sorry for the mis-report!

**Comment by aunetx** [comment]
Don't worry and thanks for the return!
Hope this behaviour will be fixed anyway, it's now hard to use this extension in gnome 40 without dislinking this :/

**Comment by foundObjects** [comment]
@aunetx Just a quick followup since I know this bugs you too:

I worked around the janky overview animation by changing the Hide Top Bar setting > Animation tab > "Slide animation time when entering/leaving overview" to 0 and it's a non-issue for me now.
