### ISSUE TITLE
Bug Blur-My-Shel not fedora 40

### ISSUE THREAD

**Issue by serial02** [aunetx/blur-my-shell#583]
Hello Blur Team

 Below is an error message after updating Fedora 40.

```
ImportError: Unable to load file from: file:///home/edson/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/effects/effects.js (Erro ao abrir arquivo /home/edson/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/effects/effects.js: Arquivo ou diretório inexistente)

Stack trace:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
  
![Captura de tela de 2024-04-23 19-53-10](https://github.com/aunetx/blur-my-shell/assets/32621790/5dfa986e-cc5c-4af6-bfd7-c8e3bf404e88)

**Comment by aunetx** [comment]
How did you install the extension? Please try uninstalling it and re-installing from extensions.gnome.org, this file should not be missing :)

**Comment by serial02** [comment]
> How did you install the extension? Please try uninstalling it and re-installing from extensions.gnome.org, this file should not be missing :)

Hello @aunetx 

Sorted out!  Thank you very much for your feedback.

 Strong hug
