### ISSUE TITLE
[Feature Request] Blur search components

### ISSUE THREAD

**Issue by saaditory** [aunetx/blur-my-shell#60]
What about blurring search box and search results?

**Comment by CorvetteCole** [comment]
that sounds like a cool idea. @aunetx is a bit busy right now, but if they want to they can work on this when they can or I will once I'm done integrating blur-provider

**Comment by aunetx** [comment]
I don't really understand the request, do you mean adding more blur to the search results? For me, the results are transparent, so we see the blur behind... Is it the case for you?

I don't think that blurring the already-blurred overview would be great, but maybe you think about something else

**Comment by saaditory** [comment]
Yeah, I just noticed that there is slight blur behind gray search results area. I don't think search box is blurred.
![image](https://user-images.githubusercontent.com/38633812/116869778-c80f9380-ac2a-11eb-8f55-d46cffaa3d3d.png)

But that grayish tint doesn't look good. I would be good if these things could match dash blur.

**Comment by aunetx** [comment]
OK, I will see what I can do with it, but it will probably be just a little css change! Hopefully it will be enough, but tell me if not

**Comment by aunetx** [comment]
What theme are you using? Just checked, on adwaita it definitively is transparent... Not sure if my extension should add transparency, I can't modify everything that is not right from user themes...

![Capture d’écran de 2021-05-04 18-04-31](https://user-images.githubusercontent.com/31563930/117034135-4b041d00-ad03-11eb-80f6-46e764723ecd.png)

**Comment by CorvetteCole** [comment]
I think this might be theme dependent to a degree. Although perhaps they were suggesting the search bar should have additional blur applied to it to help it stand out? Not sure if this issue is actually our issue

**Comment by saaditory** [comment]
> What theme are you using?

I'm using 'Adwaita-dark' as gtk+ theme with 'Default' user theme.

**Comment by saaditory** [comment]
> the search bar should have additional blur applied to it to help it stand out?

![Screenshot from 2021-05-15 03-01-40](https://user-images.githubusercontent.com/38633812/118335874-feea8100-b529-11eb-8fe5-af1a3ddcc754.png)

Actually, for reference, I found [this extention](https://extensions.gnome.org/extension/3518/transparent-shell/) which allowed to apply different opacity to search bar from css.

Also, I tried different gtk themes and Adwaita theme as well but I couldn't get that blur for search results..

**Comment by saaditory** [comment]
Well, I tried a different user-theme than the Default one,
![Screenshot from 2021-05-15 04-06-21](https://user-images.githubusercontent.com/38633812/118339679-03fffe00-b533-11eb-815b-2d7974db1de2.png)

**Comment by aunetx** [comment]
What was the shell theme you used before? Are you sure it was adwaita, or maybe some pop theme or yaru... I don't know which one, but I don't think it was adwaita before you changed (mine really is transparent, so...)

The textbox for the search has more opacity on my computer btw, so I guess you are using something else (that may be packaged as "default" by the distribution)

**Comment by saaditory** [comment]
Hmm, I get it. Then I think I might be using `Yaru` theme listed as `Default` because I'm using Ubuntu with GNOME session. 

Thanks for your time.

**Comment by aunetx** [comment]
Ok, thanks!
