### ISSUE TITLE
Not covering all shell

### ISSUE THREAD

**Issue by agecode-debug** [aunetx/blur-my-shell#607]
Good morning ! I noticed that blur my shell was not going over the entire shell. I don't know if I'm alone with this problem.

Thank you for your wonderful plugin!
![image](https://github.com/aunetx/blur-my-shell/assets/99119244/17ecd9a3-b666-4c3d-ab8c-560ea92e7a34)

**Comment by HearseDev** [comment]
happening to me as well, latest fedora. 
![image](https://github.com/aunetx/blur-my-shell/assets/28695977/95c5e7fc-9020-4cc0-ac7d-af5ea454c7df)

**Comment by ryzendew** [comment]
> Good morning ! I noticed that blur my shell was not going over the entire shell. I don't know if I'm alone with this problem.
> 
> Thank you for your wonderful plugin! ![image](https://private-user-images.githubusercontent.com/99119244/335680206-17ecd9a3-b666-4c3d-ab8c-560ea92e7a34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzk2NzUsIm5iZiI6MTcxNzI3OTM3NSwicGF0aCI6Ii85OTExOTI0NC8zMzU2ODAyMDYtMTdlY2Q5YTMtYjY2Ni00YzNkLWFiOGMtNTYwZWE5MmU3YTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDIyMDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2RjMzNmYTUxMjg4YzZhNDJhYjE1Y2JiZGM5ZjhlMWZiNzhhNGZiNjJhNjliZTQ4Y2Q4ZGQzYTMyZjkyMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rxeKMcP55GRqLxnMq8Ijhn3dAhh-lB62sA_uN7AgB6o)

oh honey just change the settings on main page 
![image](https://github.com/aunetx/blur-my-shell/assets/84041391/5edec69e-d9e6-4b3c-a1e3-90769bd3c1ff)
 then it works

**Comment by agecode-debug** [comment]
Oh thank's !
