### ISSUE TITLE
Problem with open and use Blur my Shell

### ISSUE THREAD

**Issue by OskarTDI** [aunetx/blur-my-shell#635]
I hope you can help me.
Fedora 40 Workstation GNOME 46

Error message:

TypeError: deprecated_component is undefined

Stack trace:
  update_from_old_settings/<@file:///home/cslab/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/conveniences/settings_updater.js:29:21
  update_from_old_settings@file:///home/cslab/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/conveniences/settings_updater.js:25:100
  fillPreferencesWindow@file:///home/cslab/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:35:33
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by aunetx** [comment]
Thanks, sorry I missed this! This is fixed in very next release (probably in less than an hour)
