### ISSUE TITLE
Blur for panel is offset when adding vertical monitor to layout

### ISSUE THREAD

**Issue by Roccoriu** [aunetx/blur-my-shell#641]
I am using Gnome 46.4 and blur my shell 64. For some reason the background for the top panel which is to be blurred is offset by some amount of pixels from the actual background. This does only happen when I add my vertical monitor to the layout.

To show the issue more clearly I have created a pipeline without any effects so this issue is more visible.

![Screenshot from 2024-08-19 00-09-01](https://github.com/user-attachments/assets/45a150f6-e1b2-4cf7-b56a-9de39b7d116d)

Again this only happens when a vertical monitor is added to a multi monitor setup. What is rather strange is that this worked fine up until some recent update from either Gnome or Blur My Shell. 

Here some more information regarding my system. 
Gnome 46.4
Blur My Shell 64
Fedora Workstation 40
Linux Kernel 6.10.4
GPU: AMD Radeon 6900xt
CPU: Ryzen 9 7950x

Thanks for your help

**Comment by ZhenyaGoroh** [comment]
Blur doesn't work when I connect the second monitor, this bug appeared after recent update.

Ubuntu 24.04
Gnome 46
Blur my shell 64

**Comment by aunetx** [comment]
Hello, this should be fixed in very-next update (probably today). Please tell me if it does not!

**Comment by ZhenyaGoroh** [comment]
Now it works well, thanks!
