### ISSUE TITLE
Issue with dual monitor fedora 40 gnome 46 everything is upto date 23-08-2024

### ISSUE THREAD

**Issue by sagarbangade** [aunetx/blur-my-shell#648]
problem I am facing is like it is blurifying my builtin laptop monitor but not working properly with 2nd monitor look in screenshot
![image](https://github.com/user-attachments/assets/0d2dd51f-ae06-4dd6-9721-104768f50c8c)
![image](https://github.com/user-attachments/assets/c0244cfc-c482-483a-9b16-f564bb854c1d)
 I really want it to work properly please help me :..)

**Comment by leogzyl** [comment]
Same here. It happens only on Wayland, though. With Xorg it's working fine.

**Comment by aunetx** [comment]
Hello @leogzyl, could you try installing from the latest commit in github?

**Comment by leogzyl** [comment]
> Hello @leogzyl, could you try installing from the latest commit in github?

Works like a charm after uninstalling the extension completely and re-installing from the latest commit in master!

Thanks a lot @aunetx !!!!

**Comment by SamuelWolfang** [comment]
> Hello @leogzyl, could you try installing from the latest commit in github?

@aunetx Had the same issue and can confirm building and installing from master fixes the issue!
Thanks a million!
