### ISSUE TITLE
[Bug] Error when enabling extension

### ISSUE THREAD

**Issue by mambucodev** [aunetx/blur-my-shell#659]
I'm running on Arch Linux 6.10.9-arch1-2 with gnome-shell 46.4 on Wayland, my computer recently lost power in the meanwhile that I was gaming and when I turned it on many issues appeared, for example now my Blur My Sheel extension gives this error:
```
Error: Property GaussianBlurEffect.chained-effect is not writable
```
![image](https://github.com/user-attachments/assets/dd34bf7a-333b-4fbc-8b28-25cfcc7990ea)

**Comment by aunetx** [comment]
Thanks for the issue, I just fixed it in the last commit and it will be included in the next release!

By the way, I advise you not to use the non-native gaussian blur effect as it is really way slower than the native one, and there is absolutely no difference between the two... I will probably remove it in a later version but that's just to improve your perfs!
