### ISSUE TITLE
Can't access blur my shell settings

### ISSUE THREAD

**Issue by TheCultLeader666** [aunetx/blur-my-shell#66]
When I try to access the blur my shell settings in the extensions app, I get this error:
```
Error: Type name PrefsWidget is already registered

Stack trace:
  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
  _init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:74:32
  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
  @/home/thecultleader666/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:10:29
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by jakewvincent** [comment]
I'm getting the exact same message.

```
Error: Type name PrefsWidget is already registered

Stack trace:
  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
  _init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:74:32
  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
  @/home/jake/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:10:29
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by TheCultLeader666** [comment]
@jakewvincent , have you installed any forks of the  Blur My Shell extension? I only encountered this problem after installing the Blur Me extension, although the problem persisted even after I had removed Blur Me.

**Comment by jakewvincent** [comment]
I did indeed! I installed Blur Me as well, but immediately switched to this one because Blur Me created sharp corners on my windows. I removed that extension before I got this error.

**Comment by aunetx** [comment]
I will see why it is causing this, and ultimately will change the name (that is maybe too generic...)
Did you uninstall entirely Blur Me, or just deactivated it? And did you restart gnome-shell/your computer before trying to reopen the settings?

**Comment by TheCultLeader666** [comment]
I have uninstalled it as much as one can from the extensions app, although I'm sure there are some files I could delete, and I have restarted since, if that's what you're asking.

**Comment by aunetx** [comment]
This may have been fixed in last commit, tell me if it works...
Sorry for the close, I reopen this for the moment

**Comment by jakewvincent** [comment]
> This may have been fixed in last commit, tell me if it works...
> Sorry for the close, I reopen this for the moment

Yes, it's working for me now. Thanks so much!

**Comment by aunetx** [comment]
Cool, closing this, I will push to extensions.gnome.org soon :)

**Comment by jakewvincent** [comment]
> Cool, closing this, I will push to extensions.gnome.org soon :)

Embarrassingly, I assumed you'd pushed the change to extensions.gnome.org and that it had updated itself when I logged out of gnome shell, because it was working. (I didn't actually install it from your repo.) This must mean that logging out and back in fixed the issue.

**Comment by CorvetteCole** [comment]
@jakewvincent I'm working on the sharp corners for window blurring. Eventually application blurring will be merged in #39 but there is a lot of work to do :)

**Comment by chapdel** [comment]
Same error here
`The settings of extension blur-my-shell@aunetx had an error:
```
Error: Type name PrefsWidget is already registered
```

Stack trace:
```
_construct@resource:///org/gnome/gjs/modules/script/_legacy.js:536:31
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
@/home/chapdel/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/prefs.js:18:19
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`

**Comment by aunetx** [comment]
Are you using the extension Blur Me too? It is a fork from Blur My Shell, and caused issue (although it should be resolved now)... And which version of the extension are you using, on which version of gnome?

**Comment by chapdel** [comment]
After reboot my PC it's work now! Thank!!!
