### ISSUE TITLE
Panel doesn't extent all the way to window when maximized [Static]

### ISSUE THREAD

**Issue by d3vilguard** [aunetx/blur-my-shell#661]
![image](https://github.com/user-attachments/assets/6806e754-6ee7-4323-816b-9fa32c8dd7ee)

Screenshot pretty much explains it. This is under Static blur for the panel. Never before had this issue. Dynamic fixes it but I'd rather be as low powered as possible on the notebook. Running on gnome 46 wayland, arch linux.

**Comment by Meincrakker** [comment]
This issue has already been reported on here: https://github.com/aunetx/blur-my-shell/issues/650

**Comment by d3vilguard** [comment]
Closing as duplicate.
