### ISSUE TITLE
Overview background not updated on background change

### ISSUE THREAD

**Issue by aunetx** [aunetx/blur-my-shell#7]
When the wallpaper is changed, overview's background is not changed.

It seems like the `changed` notification is not fired on Wayland, I might need to look at other ways to detect a wallpaper change.

**Comment by aunetx** [comment]
Hum, seems resolved without change... I will wait before closing the issue, please report if this bug currently applies to you.

**Comment by NGStaph** [comment]
just posted my query on the extension page. Could i somehow cause an update with a script/command?

**Comment by NGStaph** [comment]
nevermind,  solved with genrating a random wallpaper name in my script. Sorry for the bother.
