### ISSUE TITLE
Fix utilities ES6 standard non-compliance

### ISSUE THREAD

**Issue by CorvetteCole** [aunetx/blur-my-shell#71]
Apparently I didn't set up the utilities file completely correctly because ES6 is throwing warnings in the log
```
Some code accessed the property 'setTimeout' on the module 'utilities'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```

This needs to be fixed and I'll fix it when I have a few minutes

**Comment by aunetx** [comment]
I just pass there, so: thank you for your time :)
I will be able to correct some bugs in 2 days (exams right now) ^^

**Comment by CorvetteCole** [comment]
> I just pass there, so: thank you for your time :)
> I will be able to correct some bugs in 2 days (exams right now) ^^

no rush! This week is my finals week as well so I am quite inactive :)

**Comment by aunetx** [comment]
> > I just pass there, so: thank you for your time :)
> > I will be able to correct some bugs in 2 days (exams right now) ^^
> 
> no rush! This week is my finals week as well so I am quite inactive :)

Still not final weeks for me sadly, just exams sitting there but I will still have and month and half of class after that :(
But good luck to you! :p

**Comment by CorvetteCole** [comment]
thanks! I'm not really a JS dev so I'm not always sure what I'm doing haha.
