### ISSUE TITLE
not working in ubuntu 21.04 wayland gnome 3.38 

### ISSUE THREAD

**Issue by anishkumar127** [aunetx/blur-my-shell#79]
after install its show errors 

dash.get_child_at_index(...).get_child_at_index(...) is null  

// screenshots  <a href="https://ibb.co/K0wYFgy"><img src="https://i.ibb.co/K0wYFgy/Screenshot-from-2021-05-20-15-09-05.png" alt="Screenshot-from-2021-05-20-15-09-05" border="0"></a>

**Comment by aunetx** [comment]
What version of the extension are you using? I don't support anymore gnome 3.38, but version 6 is still compatible.

**Comment by nonvieri** [comment]
same here, but a different error

this.background_parent.get_parent() is null

**Comment by aunetx** [comment]
Is this working with latest version from [pre_40](/aunetx/blur-my-shell/tree/pre_40) branch? Try installing it from github if extensions.gnome.org is still not refreshed.

If not, I think I have a simple workaround that I will push tomorrow.

**Comment by aunetx** [comment]
I close this as this seems not to happen anymore, please reopen if needed
