### ISSUE TITLE
Extension stops working after waking from sleep

### ISSUE THREAD

**Issue by elmagio** [aunetx/blur-my-shell#80]
I'm using Ubuntu 21.04 with X as my display server.

The error returned is: `this.background_parent.get_parent() is null`

Note: Simply restarting the shell with the "r" command in `alt+f2` effectively fixes the issue, until the next sleep, so it's not a super big deal, but if it's something you can identify and fix, that'd be awesome.

**Comment by aunetx** [comment]
Which version of the extension are you using? Version 6?

Could you give me the result of `sudo journalctl /usr/bin/gnome-shell | grep "blur-my-shell"` to see if there are any related error logs?

**Comment by elmagio** [comment]
Yes, I'm using version 6.

Here is the result of the command you suggested: 
`JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 24 11:07:32 XPS-Ubuntu gnome-shell[3957]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 24 15:45:13 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 24 17:18:20 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 24 17:24:58 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 24 23:15:38 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 25 10:52:35 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 25 16:34:51 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 25 23:39:38 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 26 11:14:58 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 26 16:27:46 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 26 23:12:48 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
mai 27 11:47:19 XPS-Ubuntu gnome-shell[3855]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: this.background_parent.get_parent() is null
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/panel.js:118:32
                                              disable@/home/elmagio/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:60:26
`

**Comment by aunetx** [comment]
Thanks, I will investigate more into this soon

**Comment by elmagio** [comment]
Thanks, let me know if you need more logs !

**Comment by aunetx** [comment]
I will try to fix this tomorrow, I recently updated codebase for gnome 3.36/3.38 so I just have some testing to do now :)

**Comment by elmagio** [comment]
I got an extension update and it seems to have fixed it ! Thanks !

**Comment by aunetx** [comment]
Cool, really glad it worked! I close this, but if the bug reappears please reopen this issue :)

**Comment by aunetx** [comment]
Cool, really glad it worked! I close this, but if the bug reappears please reopen this issue :)
