### ISSUE TITLE
Panel blur with multiple monitors - not entirely blured

### ISSUE THREAD

**Issue by NoeDeMontard** [aunetx/blur-my-shell#81]
Might be a similar issue as #68, but seams sufficiently different for another issue.
The panel is blurred only until the length of the second, smaller screen.

Output of the commands in in looking glass from the other issue :
```
Main.layoutManager.monitors[0].width
r(0) = 1920
Main.panel.get_parent().get_children()[0].get_children()[0].width
r(1) = 1360
Main.layoutManager.monitors[1].width
r(2) = 1360
Main.panel.get_parent().get_children()[0].get_children()[1].width
r(3) = <exception TypeError : Main.panel.get_parent().get_children()[0].get_children()[1] is undefined>
```
And 
```
a = Main.panel.get_parent().get_child_at_index(0).get_child_at_index(0)
a.set_x(1920) 
```
put the blur on the second monitor for me (but it is my secondary monitor). When I change the primary monitor, the panel seams to never blur (not with a set_x(0), nor with a positive or a negative value)

**Comment by aunetx** [comment]
This is similar to (if not the same as) #47 right?
If yes, could you give me the results of the last comment I put there? I need to have a lot of informations to investigate about this, sorry...

**Comment by NoeDeMontard** [comment]
Yes it seams to be the same issue, I didn't thought about checking closed ones. 
I'm still on version 11 from gnome extensions, so I can try installing from the source as it seams it solved the issue.
I'm in the same case as guihkx (2 screens, first one 1920x1080, second one 1360x768)

```
Main.layoutManager.monitors[0].x
0
Main.layoutManager.monitors[0].width
1920
Main.panel.get_parent().get_children()[0].get_children()[0].width
1360
Main.panel.get_parent().get_children()[0].get_children()[0].width
1360

Main.layoutManager.monitors[1].x
1920
Main.layoutManager.monitors[1].width
1360
Main.panel.get_parent().get_children()[0].get_children()[1].width
<exception TypeError : Main.panel.get_parent().get_children()[0].get_children()[1] is undefined>
Main.panel.get_parent().get_children()[0].get_children()[1].width
<exception TypeError : Main.panel.get_parent().get_children()[0].get_children()[1] is undefined>
```

**Comment by Caliel666** [comment]
version 11 has this bug, update to version 12 on gnome extensions (just got released) or from source

**Comment by NoeDeMontard** [comment]
It works, thanks!
Sorry for the duplicate.

**Comment by aunetx** [comment]
OK thanks!
