### ISSUE TITLE
Top system bar bug

### ISSUE THREAD

**Issue by matt-hu** [aunetx/blur-my-shell#83]
After updating to version 12, there is now a bug that causes the system bar at the top to stop being blurred about 2/3rds of the way along (between time and quick actions - see below)
 
![image](https://user-images.githubusercontent.com/70395217/119714777-265f1900-be5b-11eb-81b5-78520749d8f8.png)

System details:
- Arch Linux
- Gnome 40.1.0
- Using Wayland
- Extension version 12 (as reported in Gnome extensions)

**Comment by aunetx** [comment]
Thanks for reporting! Is this fixed in last commit from master?

**Comment by matt-hu** [comment]
Yes thanks!

**Comment by aunetx** [comment]
Cool thanks!
It is pushed to extensions.gnome.org, hope it will be reviewed soon :)
