### ISSUE TITLE
Update breaks

### ISSUE THREAD

**Issue by mende1** [aunetx/blur-my-shell#84]
I followed instruction from Actor which is reinstall if have errors during update, and yet doesn't worked.
Still break, the extension.

I have Gnome 40, on Arch Linux, with Wayland.

**Comment by mende1** [comment]
I have to install the previous version (12) manually to back the normal and works.
Hint for anyone that have same problem:
Go to blur my shell's page on GNOME Extensions, select your gnome version and the extension version, which is 12.
It is download a .zip, Unzip, and move the folder to ~/.local/share/gnome-shell/extensions, then reload gnome or reboot your pc, and done.

**Comment by aunetx** [comment]
Sorry for this! I reopen this issue because it should not break like this, and that's weird...

Does using the last version works now? You might need to reboot/reload shell for it to work

**Comment by mende1** [comment]
Hi @aunetx, the last version works great. the break was caused by the version 13 if I'm not wrong. But the 14 not break to me, works great, and extension is really wonderful, make my gnome pretty, thanks for support extension. I hope it is alive for long time.

By me, the issue is closes I suppose. Later.

**Comment by aunetx** [comment]
Ok cool, thanks!
