### ISSUE TITLE
Panel background doesn't update

### ISSUE THREAD

**Issue by shemgp** [aunetx/blur-my-shell#85]
Using version 13 here:

![image](https://user-images.githubusercontent.com/1734126/120100803-50734c80-c175-11eb-9560-6e1e8360f4d2.png)

**Comment by shemgp** [comment]
If I restart gnome-shell (alt-f2 r) then it updates. However, after a lock, it gets stuck at the background of the lock. The bug is just with the top panel and not with dash to dock.

**Comment by KristianUSN** [comment]
Same issue, reverting to version 12 fixes it however

**Comment by aunetx** [comment]
Sorry for not answering before... Looks like you found a way to solve this, will merge it soon!
