### ISSUE TITLE
Feature request: make top panel blur dynamic.

### ISSUE THREAD

**Issue by Antoshka1488** [aunetx/blur-my-shell#90]
Blur when there is no maximized window and window on top. Solid in other cases.

**Comment by Ferryistaken** [comment]
Yes please this would make the extension way more enjoyable to use

**Comment by aunetx** [comment]
I will see what is possible to do, my other extension (Smart Transparent Topbar, still not compatible with gnome 40) did this so implement it would not be too hard.

**Comment by aunetx** [comment]
When you talk about a solid topbar, do you think about a "normal" topbar (black, with adwaita), or eg a transparent topbar? The first option is a lot easier, because I would not have to manage the transitions, but the second option seems more enjoyable to me (but ofc, if I implement the transparent option, it would be optionnal)

What would you want? Just solid, or "solid-or-transparent"?

**Comment by Ferryistaken** [comment]
To me just a normal topbar when an application is maximized would be fine, but if you think that it would be more enjoyable to make it normal-or-transparent I think that that is fine too, since I would still be able to make it solid.

**Comment by aunetx** [comment]
Ok thanks!
Well, I will first try to implement the behaviour with the normal topbar colour, and after maybe see for something else (although... this may actually not be my job, as another theme/extension could change the topbar colour too) :p

Will try to begin tomorrow if possible!

**Comment by Ferryistaken** [comment]
Perfect, thanks for your effort in making this extension

**Comment by aunetx** [comment]
I will work on this as soon as I merge the branches `window-list` and `blur-onscreen-keyboard` (first should be very quick, as everything works (see #103), but the second needs some more work, although I could add this later as no issue is opened about that).

**Comment by aunetx** [comment]
`window-list` is done now, and `blur-onscreen-keyboard` is too hard to be finished by me alone... So I begin to work on this, but idk when I will have something that works :p

**Comment by aunetx** [comment]
I began the work in branch `dynamic-blur`, but I have a hard time understanding why I can't get my extension to update itself when its position is changed...

I will need some time to get is done, but at least I only have bugs to fix now!

**Comment by aunetx** [comment]
This will be fixed very soon by #272 :)

**Comment by aunetx** [comment]
Fixed :)
