### ISSUE TITLE
Make panel settings play nice with dash to panel gradient options

### ISSUE THREAD

**Issue by KristianOde** [aunetx/blur-my-shell#93]
Dash to panel has an option to apply gradients to the panel, which I like to use to give a nice 3D effect to the panel. Using both of these extensions together, it works initially but when you go into overview the gradient display will be ignored until you go into DtP-settings again and reapply them. I would love it if you could make this extension respect that setting <3

**Comment by aunetx** [comment]
I tried to make blur-my-shell respect this setting, but I did not find a way to do so... The gradient works well when you go back from overview, unless you use trackpad gesture; and I find this behaviour very weird... I will try to investigate into this some little more, but I suspect the DtP code not to support well the gradient option yet, as I bugs for me even when I do not use blur my shell :/

**Comment by aunetx** [comment]
This seems to work nicely now, at least with last DtP update for gnome 41! Closing this, but if the issue persists please reopen :)
