### ISSUE TITLE
Sometimes the blur effect isn't applied on overview; wayland (fedora 34).

### ISSUE THREAD

**Issue by afkniladri** [aunetx/blur-my-shell#95]
There are a few instances when the blur effect isn't applied on the overview screen. Works impeccably while using touchpad gestures, but when using dash to dock or activities using an external mouse it causes problem.

The video has been attached, please check it out. 

https://user-images.githubusercontent.com/31654012/122940656-49b1b100-d392-11eb-9f69-177e12997697.mp4

**Comment by aunetx** [comment]
Thanks for the issue, and for the video, it helps a lot to understand :)
In looking glass (`alt+f2`, type `lg`), could you give me the result of this command, when it works and then when it does not?

```js
Main.layoutManager.overviewGroup.get_children()[0].get_content()
```

I don't know why these extensions would mess up with the overview, they should not be connected to it in any way... But I will try to fix this!

**Comment by afkniladri** [comment]
r(0) = [object instance wrapper GIName:Meta.BackgroundContent jsobj@0x155d00c60130 native@0x55fe7347db80]
The command returns this.

**Comment by aunetx** [comment]
OK thanks, even when it does not work?

**Comment by afkniladri** [comment]
Sorry buddy I didn't quite understood. The outcome (object instance wrapper GIName:Meta.BackgroundContent jsobj@0x155d00c60130 native@0x55fe7347db80] ) I think is in json format and contain bunch of keys and its values as some linked js files. But overall actions are the same, unpredictable. If you need those json values please say so! And thanks for your mad js skills, we are blessed 😇

**Comment by aunetx** [comment]
No worry! But sorry I did not explain, what I meant is:
When you launch the overview and it works, and enter to looking glass etc, you have this output
But when you enter overview and it does not work, and then type the command in looking glass, what is the output? The same keys or something else (or "undefined" for example)?

And you're kind but I'm really not great in js or with my coding skills! It took me months to get this extension to work tbh 😅

**Comment by afkniladri** [comment]
Sure mate. Once I reach home, I'll update you. 

You're too humble to acknowledge your achievements. Keep up the good work!

**Comment by afkniladri** [comment]
[object instance wrapper GIName:Meta.BackgroundContent jsobj@0x293a53a54550 native@0x556c7a0774e0]

This is what I got. js object address is different, although I think it has been dynamically allocated after reboot. Also I've checked for blur and no blur conditions, output remains the same. Well is there any way to generate logs as this might not help?

**Comment by LukeVader-IV** [comment]
I noticed that this is not an issue of the plugin, rather an issue with gnome wayland

this can easily be seen in the lock screen, the blur on the main display acts the same way even with this plugin disabled, this can be easily seen of you have an animated background, the blur starts flashing exactly like it does with the plugin

you should open an issue on their code and mark this issue as an upstream issue

**Comment by afkniladri** [comment]
Yes I totally agree. When using Manjaro I didn't face any issues. Thus I am closing the issue.

**Comment by aunetx** [comment]
OK, thanks for the follow-up, I hope this will be resolved in gnome shell!

**Comment by Varad-Codes** [comment]
I am facing the same issue, is there a work around or something like that?
