### ISSUE TITLE
Static panel blur makes primary screen just the blurry background with no windows

### ISSUE THREAD

**Issue by Araly** [aunetx/blur-my-shell#97]
after blur-my-shell got updated, if "the static panel blur" option is toggled on, my primary screen is just the blurry background and nothing else. I can still go into overview and see what's going on, but when I come back to the screen, it's just blank, no windows. The top bar is there though. My second screen works without issues. You can see on the image that the top bar still has the firefox icon and name of the window, so the windows are still there,  it's really just that you can't see anything.

![image](https://user-images.githubusercontent.com/24990801/123822152-eecd0c00-d8f3-11eb-8394-8673e3832453.png)

**Comment by guihkx** [comment]
Not sure if the issue I'm also having after updating to v15 is related to this, but there's something weird happening when I switch resolutions then switch back.

I'll provide an example using `xrandr`, but beware that if you actually run this, blur my shell will create big "square" and you won't be able to bring any window forward to see what's happening:

```
$ xrandr --output DVI-D-0 --mode 1920x1080 --scale-from 1024x768 --primary
```

The after I go back to my native resolution (1920x1080), the "square" stays there:

![Untitled2](https://user-images.githubusercontent.com/626206/123836907-9d675180-d8e0-11eb-9589-e6e00604304a.png)

For comparison purposes, this is how it should look:

![Untitled](https://user-images.githubusercontent.com/626206/123836940-a6f0b980-d8e0-11eb-9801-5cae7b836c8f.png)

**Comment by aunetx** [comment]
f*ck, I was sure this update was going to be messy at some point... :/

Could you give me the resolutions of your monitors? I think I now exactly where this could come from, but I currently do not have any external monitor to test it...

For the moment, the best thing would be of course to switch back to last version, either via github or via extensions.gnome.org; and I will see what I can do to solve this issue asap :)

**Comment by lcsvcn** [comment]
Happening with me too. This happens with my 3840x2160 resolution monitor:

**Comment by mfreri** [comment]
Hi, I have the same problem. My laptop's display is 1366x768 and the external monitor is 1920x1080.

**Comment by aunetx** [comment]
Thanks for the comments, I will see what I can do to debug this...

**Comment by aunetx** [comment]
This should be fixed in last commit, could you please try and tell me what works and what is not right?

**Comment by mfreri** [comment]
It's working now. Thanks.

**Comment by aunetx** [comment]
Cool, thanks! I will push to extensions.gnome.org now
