### ISSUE TITLE
Blur don't work on the COSMIC dock 

### ISSUE THREAD

**Issue by PauloVBettio** [aunetx/blur-my-shell#99]
I'm using Pop!_OS 21.04

The new COSMIC dock doesn't get any blur effect
 
![image](https://user-images.githubusercontent.com/74562432/124357331-e3762b00-dbe8-11eb-907e-e2459bca11bb.png)

Changing the brightness and sigma does not affect the background neither.
![image](https://user-images.githubusercontent.com/74562432/124357375-2506d600-dbe9-11eb-8222-3ab4653eac8d.png)

**Comment by aunetx** [comment]
Thanks for the report!
I will test this soon, seems like a little issue with the bg opacity of the cosmic Dock... Is there any option around to change its opacity?

**Comment by PauloVBettio** [comment]
> Thanks for the report!
> I will test this soon, seems like a little issue with the bg opacity of the cosmic Dock... Is there any option around to change its opacity?

No, the dock customization is very basic. I tried changing the shell theme too (tested with Orchis and WhiteSur), doesn't seem to have any effect neither.

**Comment by aunetx** [comment]
Ok thanks, so I will probably need to have an option to force to remove styling of the dock, or even detect if COSMIC is working to remove the background color... This does not seem a very great fix, but better than nothing I guess

**Comment by your-local-developer** [comment]
We have the same problem with the app drawer. The top bar, workspace overview and lockscreen seem to work as intended. It's just the app overview and dock that don't seem to work. I think it's because COSMIC is changing themselves quite a lot through extensions.

**Comment by aunetx** [comment]
Hello all, is the cosmic dock blur working with last commit on `pre_40` branch?

I almost got the overview to work, just need to include it in the code, test it again and it will be good

**Comment by aunetx** [comment]
@your-local-developer @PauloVBettio would it be possible for you to test this? So I am sure this works before pushing to extensions.gnome.org

**Comment by your-local-developer** [comment]
@aunetx Hey, I did test it today. And while the dash and lock screen work, the panel (if that's the bar up top) and overview don't. Furthermore I get the following error when I try to enable the extension. "Main.overview._updateBackgroundsBlur is not a function". I try to have look a the source code the following days too.  But I'm pretty inexperienced with gnome stuff.

In addition the dash does not keep it's rounded corners and floating appearance but I don't know if that's something that would be even possible.

**Comment by your-local-developer** [comment]
@aunetx After installing the Pop Os Cosmic update of today, the extension works flawlessly! Thank you so much for the work and your commitment!

**Comment by aunetx** [comment]
Cool, thanks a lot for the reply! And no need to thank me, that's an honor to serv this community :)

I will push to extensions.gnome.org soon :p
